function htmlTagRevision(a,b,c){if(0<KEDITORTOP.G_CURRKEDITOR._config.htmlCorrectionLimitLength&&a.length>KEDITORTOP.G_CURRKEDITOR._config.htmlCorrectionLimitLength)return a;var e=a;if(""!=e&&(KEDITORTOP.RAONKEDITOR.browser.ie&&11>=KEDITORTOP.RAONKEDITOR.browser.ieVersion||KEDITORTOP.RAONKEDITOR.browser.gecko))try{var d=e.toLowerCase().indexOf("<body"),f=e.toLowerCase().lastIndexOf("<body");if(-1<d&&-1<f&&d!=f)return a;if(-1<e.indexOf("mso-fareast-font-family")){var g=RegExp("<[^>]+style=(.*?)>",
"gi"),h="",d=!1;try{var l=e.match(g);if(l){for(var k=l.length,g=0;g<k;g++)e=e.replace(l[g],"_KE_T_S{"+g+"}_");for(g=0;g<k;g++){var m=l[g];-1<m.indexOf("-font-family")&&(m=m.replace("-font-family","-font-ktemp-family"));f=!1;0>m.indexOf("font-family")&&(f=!0);-1<m.indexOf("-font-ktemp-family")&&(m=m.replace("-font-ktemp-family","-font-family"));f&&(m=m.replace(/mso-fareast-font-family/gi,"font-family"));e=e.replace("_KE_T_S{"+g+"}_",m)}}}catch(t){d=!0}d&&(e=a)}b&&(e=RAONK_EDITOR.HTMLParser.RemoveOfficeTag(e,
c));var h=e.toLowerCase(),p=realValue2=e,n=h.lastIndexOf("<body"),q=h.indexOf("</body");if(-1<n&&-1<q)try{var r=p.substring(q),u=p.substring(n).indexOf(">"),v=p.substring(0,n+u+1),e=p.substring(n+u+1,q)}catch(w){n=q=-1,e=realValue2}realValue2=null;e=RAONK_EDITOR.HTMLParser.HTMLtoXML(e,c);-1<n&&-1<q&&(e=v+e+r)}catch(x){return a}else if(e="1"==KEDITORTOP.G_CURRKEDITOR._config.removeComment?e.replace(/(<style[^>]*>\s*\x3c!--)|(\x3c!--.*?--\x3e)|(\x3c!--[\w\W\n\s]+?--\x3e)/gi,"$1"):e.replace(/--\x3e\s</gi,
"--\x3e<"),"1"==KEDITORTOP.G_CURRKEDITOR._config.removeCarriageReturnInTag)try{for(g=RegExp("(<[^>]*?)\n([^]*?>)","gi");g.test(e);)e=e.replace(g,"$1 $2")}catch(y){}return e}var G_wordProcessorType="";
function SetCorrectOfficeHtml(a){var b=a;if(-1<a.indexOf("<meta name=ProgId content=Word.Document>")||-1<a.indexOf('<meta name=Generator content="Microsoft Word'))G_wordProcessorType="DOC",a=GetMsWordHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=Excel.Sheet>"))G_wordProcessorType="XLS",a=GetMsExcelHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=PowerPoint.Slide>")){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==KEDITORTOP.G_CURRKEDITOR._config.removeTdStyleInPastePpt){for(var c=
RegExp("<(td|th)([^>]*?)style='([^']*?)(font-size:18.0pt;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-size:18.0pt;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">');for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-family:Arial;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-family:Arial;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">')}}else if(-1<
a.indexOf('<meta name=Generator content="Jungum Global">'))G_wordProcessorType="GUL",a=GetJungumHtml(a);else if(isHwpPasteAction(a))G_wordProcessorType="HWP",a=GetHanHwpHtml(a);else if(-1<a.indexOf(' xmlns:m="http://schemas.microsoft.com/office/')){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==KEDITORTOP.G_CURRKEDITOR._config.removeTdStyleInPastePpt){for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-size:18.0pt;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-size:18.0pt;)([^"]*?)">',
"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">');for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-family:Arial;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-family:Arial;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">')}}else-1<a.indexOf('<meta name=Generator content="Microsoft')?(G_wordProcessorType="DOC",a=GetMsWordHtml(a)):KEDITORTOP.RAONKEDITOR.browser.ie||(b=a.indexOf("\x3c!--StartFragment--\x3e"),c=
a.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<b&&-1<c&&(b=a.substr(b+20),c=b.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<c&&(a=b=b.substring(0,c))));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !supportEmptyParas]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--[if !supportEmptyParas]--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--[if !supportLists]--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--[endif]--\x3e",
"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");return a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if ppt]>","")}
function GetMsWordHtml(a){var b=a,c,b=a.indexOf("/* Style Definitions */"),e=a.indexOf("</head>");-1<b&&-1<e&&(b=a.substr(b+23),e=b.indexOf("</head>"),-1<e&&(c=b.substring(0,e),c=GetStyleMap(c)));var b=a,e=!1,d="\x3c!--StartFragment--\x3e",f="\x3c!--EndFragment--\x3e",g=a.indexOf(d),h=a.indexOf(f);if(-1==g&&-1==h){var d="<body ",f="</body>",l=a.indexOf(d);-1<l&&(h=a.indexOf(">",l),d=a.Mid(l,h-l+1),g=a.indexOf(d),h=a.indexOf(f))}if(-1<g&&-1<h&&(b=a.substr(g+d.length),h=b.indexOf(f),-1<h)){for(;;)if(a=
b.indexOf(f,h+f.length),-1<a)h=a;else break;a=b=b.substring(0,h);e=!0}if(e){a=b;var k="<div class=WordSection1>",f=a.indexOf(k);-1==f&&(k='<div class="WordSection1">',f=a.indexOf(k));-1<f&&(k=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,k,""),k.length!=a.length&&(a=k,k=a.lastIndexOf("/"),-1<k&&(a=a.substring(0,k-1))));d="\x3c!--[if supportFields]>";for(f="<![endif]--\x3e";;){g=a.indexOf(d);-1<g&&(h=a.indexOf(f,g+d.length));k=a.length;if(g>k||h>k)break;if(-1<g&&-1<h){if(g<h){var m,b=a.substring(0,g);m=
a.substr(h+f.length);a=b+m}}else break;h=-1}}if(e){d="\x3c!--[if gte vml 1]>";f="<![if !vml]>";try{g=a.indexOf(d),-1<g&&(h=a.indexOf(f,g+d.length)),-1<g&&-1<h&&(a=a.replace(/\x3c!--\[if gte vml 1\]>(.|\s|\n)*?<!\[if !vml\]>/gi,""))}catch(t){}}d="\x3c!--[if gte mso 9]>";f="<![endif]--\x3e";try{for(;;){g=a.indexOf(d);-1<g&&(h=a.indexOf(f,g+d.length));k=a.length;if(g>k||h>k){a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,d,"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,f,"");break}if(-1<g&&-1<h)g>h?(b=a.substring(0,
g),m=a.substr(g),b=KEDITORTOP.RAONKEDITOR.util.replaceAll(b,f,"")):(b=a.substring(0,g),m=a.substr(h+f.length)),a=b+m;else break}}catch(p){}e&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"><![endif]></span>"," /></span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]></span>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</span><![endif]>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !vml]>",""));a=RepaireSpanInImageTag4MsWord(a);
if(0<KEDITORTOP.G_CURRKEDITOR._config.clipImageHex.length){try{var n=RegExp("<img[^>]+file://[^>]+>","gi"),q=a.match(n);if(q){var r=q.length;if(r==KEDITORTOP.G_CURRKEDITOR._config.clipImageHex.length)for(m=0;m<r;m++){var u=KEDITORTOP.RAONKEDITOR.util.hexToBytes(KEDITORTOP.G_CURRKEDITOR._config.clipImageHex[m].hex),u=KEDITORTOP.RAONKEDITOR.util.bytesToBase64(u),n=/<img[^>]*src=["']?([^>"']+)["']?[^>]*>/;if(n.test(q[m])){var v=q[m].replace(RegExp.$1,"data:"+KEDITORTOP.G_CURRKEDITOR._config.clipImageHex[m].type+
";base64,"+u);a=a.replace(q[m],v)}}}}catch(w){}KEDITORTOP.G_CURRKEDITOR._config.clipImageHex=[]}a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:rect ","<div ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:rect>","</div>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:shadow ","<hr ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:shape ","<span ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:shape>","</span>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:imagedata","<img border=0");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"<![if !supportLists]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>","");return a=setPasteClassStyle(c,a,!0)}
function GetMsExcelHtml(a){var b=a,c,b=a.indexOf("<style>"),e=a.indexOf("</head>");-1<b&&-1<e&&(b=a.substr(b+7),e=b.indexOf("</head>"),-1<e&&(c=b.substring(0,e),c=GetStyleMap(c)));var b=a,e=!1,d="</body>",f=a.indexOf("<table"),g=a.indexOf(d);-1<f&&-1<g&&(b=a.substr(f),g=b.indexOf(d),-1<g&&(b=b.substring(0,g),e=!0));if(e){e=!1;a=b;b="\x3c!--[if gte vml 1]>";d="<![if !vml]>";try{f=a.indexOf(b),-1<f&&(g=a.indexOf(d,f+b.length)),-1<f&&-1<g&&(a=a.replace(/\x3c!--\[if gte vml 1\]>(.|\s|\n)*?<!\[if !vml\]>/gi,
""))}catch(h){}}e&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"></span><![endif]>"," /></span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</span><![endif]>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>",""),b=_T("<![if !vml]>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,b,""));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:rect ","<div ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:rect>","</div>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:shadow ","<hr ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"<v:shape ","<span ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:shape>","</span>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:imagedata","<img border=0");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");b=a.indexOf("<col ");-1<b&&(a=a.substring(0,b)+"\n<colgroup>\n"+a.substring(b,a.length+1));b=a.indexOf("<tr ");-1<b&&(a=a.substring(0,b)+"\n<tbody>\n"+a.substring(b,a.length+1),b=a.lastIndexOf("</table>"),
-1<b&&(a=a.substring(0,b)+"\n</tbody>\n"+a.substring(b,a.length+1)));a=setPasteClassStyle(c,a);"1"==KEDITORTOP.G_CURRKEDITOR._config.officeLineFix&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-left:none;",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-top:none;",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-right:none;",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-bottom:none;",""));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\r","");return a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"\n","")}
function GetMsPptHtml2(a){var b=a,c,b=a.indexOf("\x3c!--tr"),e=a.indexOf("</head>");-1<b&&-1<e&&(b=a.substr(b+6),e=b.indexOf("</head>"),-1<e&&(c=b.substring(0,e),c=GetStyleMap(c)));b=a.indexOf("\x3c!--StartFragment--\x3e");e=a.indexOf("\x3c!--EndFragment--\x3e");if(-1<b&&-1<e&&(b=a.substr(b+20),e=b.indexOf("\x3c!--EndFragment--\x3e"),-1<e)){for(;;)if(a=b.indexOf("\x3c!--EndFragment--\x3e",e+18),-1<a)e=a;else break;a=b=b.substring(0,e)}a=setPasteClassStyle(c,a);"1"==KEDITORTOP.G_CURRKEDITOR._config.officeLineFix&&(a=
KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-right:none;",""));c=RegExp("<spanstyle","ig");a=a.replace(c,"<span style");return a=a.replace(c,"<p style")}
function GetJungumHtml(a){if("1"==KEDITORTOP.G_CURRKEDITOR._config.useHtmlProcessByWorker)return a;var b=a.indexOf("<body>"),c=a.indexOf("</body>"),e=!1;-1<b&&-1<c&&(strTemp=a.substr(b+6),c=strTemp.indexOf("</body>"),-1<c&&(a=strTemp=strTemp.substring(0,c),e=!0));if(e){b=document.createElement("div");b.innerHTML=a;a=b.getElementsByTagName("table");for(var c=a.length,d,f,e=0;e<c;e++)""!=a[e].getAttribute("width")&&(d=parseInt(a[e].getAttribute("width"),10)),""!=a[e].getAttribute("height")&&(f=parseInt(a[e].getAttribute("height"),
10)),d&&(a[e].style.width=d+"px"),f&&(a[e].style.height=f+"px");a=b.innerHTML}return a}
function GetHanHwpHtml(a){var b=a,b=">\x3c!--p.0",c="</head>",e,d=a.indexOf(b),f=a.indexOf(c);-1==d&&(b=">\r\n\x3c!--p.0",d=a.indexOf(b));-1==d&&(b="\x3c!--p.0",d=a.indexOf(b));-1==f&&(c="</HEAD>",f=a.indexOf(c));-1<d&&-1<f&&(b=a.substr(d+(b.length-3)),f=b.indexOf(c),-1<f&&(e=b.substring(0,f),e=GetStyleMap(e)));var b=a,g=!1,h="\x3c!--StartFragment--\x3e",c="\x3c!--EndFragment--\x3e",f=a.indexOf(h),d=a.indexOf(c);if(-1<f&&-1<d&&(b=a.substr(f+h.length),d=b.indexOf(c),-1<d)){for(;;)if(g=b.indexOf(c,
d+c.length),-1<g)d=g;else break;b=b.substring(0,d);g=!0}if(g){g=!1;a=b;h="\x3c!--[if gte vml 1]>";c="<![if !vml]>";try{for(;;){f=a.indexOf(h);-1<f&&(d=a.indexOf(c,f+h.length));var l=a.length;if(l>f||l>d){a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,h,"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,c,"");break}if(-1<f&&-1<d)if(f>d){var k,b=a.substring(0,f);k=a.substr(f);b=KEDITORTOP.RAONKEDITOR.util.replaceAll(b,c,"");a=b+k}else b=a.substring(0,f),k=a.substr(d+c.length),a=b+k,g=!0;else break}}catch(m){}}a=
setPasteClassStyle(e,a);g&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"/><![endif]>"," />"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</span><![endif]>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !vml]>",""));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !supportEmptyParas]>&nbsp;<![endif]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"background:#ffffff;",
"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"mso-fareast-","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"mso-hansi-","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"mso-ascii-","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"mso-bidi-","");return a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"mso-","")}
function GetStyleMap(a){var b={};a=a.split("}");for(var c="",e=a.length,d=0;d<e;d++){var f=a[d].split("{"),g=f.length;if(2==g)for(var h=0;h<g-1;h++){var l=f[h],k=f[h+1],l=l.replace(/\r\n/g,""),l=l.replace(/\r/g,""),l=l.replace(/\n/g,""),l=l.replace(/\t/g,""),k=k.replace(/\r\n/g,""),k=k.replace(/\r/g,""),k=k.replace(/\n/g,""),k=k.replace(/\t/g,"");""==c&&"td"==l&&(c=k=KEDITORTOP.RAONKEDITOR.util.replaceAll(k,"'",'"'));0<l.length&&(k=KEDITORTOP.RAONKEDITOR.util.replaceAll(k,"'",'"'),"."==l.substring(0,
1)&&0<c.length?(k=k.replace(/font-family:&quot,/g,"font-family:"),b[l]=c+k):b[l]=k)}}return b}
function RepaireSpanInImageTag4MsWord(a){for(var b,c,e,d,f;;)if(b="<v:shape ",c=a.indexOf(b),-1==c&&(b="<v:shape\r\n",c=a.indexOf(b)),-1<c)if(e=a.indexOf("</v:shape>",c+b.length),d=a.indexOf("<v:imagedata",c+b.length),-1<e&&-1<d&&d<e)if(f=a.indexOf("/>",d+12),-1<f)d=a.substring(0,c),c=a.substr(c,f-c+2),a=a.substr(e+10),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,"<v:imagedata"," "),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,b,"<v:imagedata "),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,">"," "),c=KEDITORTOP.RAONKEDITOR.util.rtrim(c),
c+=">",c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,"/>"," />"),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,"  "," "),a=d+c+a;else break;else break;else break;return a}
function setPasteClassStyle(a,b,c){for(var e in a){var d=a[e],d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d,"hairline ","dotted "),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d," hairline;"," dotted;"),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d,"dot-dot-dash ","dotted "),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d," dot-dot-dash;"," dotted;"),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d,"dot-dash ","dotted "),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d," dot-dash;"," dotted;"),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d,
"dot-dash-slanted ","dotted "),d=KEDITORTOP.RAONKEDITOR.util.replaceAll(d," dot-dash-slanted;"," dotted;");e=e.split(",")[0];e=e.substring(e.indexOf("."));if("."==e.substring(0,1)){var f=new RegExp("<[^>]*class=(\"|'|)"+e.substr(1)+"(\"|'|) [\\s\\S]*?>","i");b=setStyleToClass(b,f,e,d);f=new RegExp("<[^>]*class=(\"|'|)"+e.substr(1)+"(\"|'|)>","i");b=setStyleToClass(b,f,e,d)}if(c&&(f=e.toLowerCase(),(-1<f.indexOf("h1")||-1<f.indexOf("h2")||-1<f.indexOf("h3")||-1<f.indexOf("h4")||-1<f.indexOf("h5")||
-1<f.indexOf("h6")||-1<f.indexOf("em"))&&""!=d&&(f=new RegExp("<"+e+"[^>]*>","igm"),f=b.match(f))))for(var g=f.length,h=0;g>h;h++){var l=b.substring(0,b.indexOf(f[h])),k=f[h];b=b.substring(b.indexOf(f[h])+f[h].length);var m=/(style=("|'|))/i,k=1==m.test(k)?k.replace(m,RegExp.$1+d):k.replace(new RegExp("<"+e,"i"),"<"+e+" style='"+d+"'");b=l+k+b}}return b}
function setStyleToClass(a,b,c,e){for(var d;d=b.exec(a);){var f=a.substring(0,d.index),g=d[0].toString();a=a.substr(d.index+d[0].length);d=/style=("|'|)/i;if(1==d.test(g)){var h=RegExp.$1;"'"==h?e=e.replace(/'/gi,'"'):'"'==h&&(e=e.replace(/"/gi,"'"));g=g.replace(d,"style="+h+e+" ");d=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i");g=g.replace(d,"")}else d=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i"),g=g.replace(d,"style='"+e+"'");a=f+g+a}return a}
function GetFontSizeForWordH1ToH7Tag(a){var b="",c=a.indexOf("font-size");-1<c&&(a=a.substr(c),c=a.indexOf(";"),-1<c&&(b=a.substring(0,c),b+=";"));return b}function isHwpPasteAction(a){return-1<a.indexOf(">\x3c!--p.")||-1<a.indexOf('<META NAME="Generator" CONTENT="Hancom HWP')||-1<a.indexOf("\x3c!--[if !supportEmptyParas]--\x3e")?!0:!1}
"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.officeClean&&(KEDITORTOP.RAONKEDITOR.util.officeClean=function(a,b){if(""==a||void 0==a)return"";var c=null,e=[];a=a.replace(/\.0px/g,"px");a=a.replace(/\t/g,"");a=KEDITORTOP.RAONKEDITOR.util.removeOfficeDummyTag(a,"\x3c!--[if supportFields]>","<![endif]--\x3e");c=RegExp("<o:p></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");
a=a.replace(c,"");c=RegExp("<w:sdt[^>]*>","gi");a=a.replace(c,"");c=RegExp("</w:sdt>","gi");a=a.replace(c,"");c=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi");if(c=a.match(c))for(var e=c.length,d=0;d<e;d++){var f=c[d],g=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),f=f.replace(g,"");a=a.replace(c[d],f)}c=RegExp("<[^>]+(mso)[^>]*>","gi");if(c=a.match(c))for(e=c.length,d=0;d<e;d++)f=c[d],"1"==KEDITORTOP.G_CURRKEDITOR._config.removeMsoClass&&(g=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),f=f.replace(g,
"")),f=f.replace(/&quot;/gi,"^"),g=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',"gi"),f=f.replace(g,""),g=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),f=f.replace(g,""),g=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?","gi"),f=f.replace(g,""),g=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),f=f.replace(g,"$1"),f=f.replace(/\^/gi,"&quot;"),a=a.replace(c[d],f);a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"hairline","dotted");for(d=0;5>d;d++){e=["o:p",
"span","font"];g=e.length;for(f=0;f<g;f++)c=new RegExp("<"+e[f]+"[^>]*></"+e[f]+">","gi"),a=a.replace(c,""),c=new RegExp("<"+e[f]+"[^>]*>&nbsp;</"+e[f]+">","gi"),a=a.replace(c,"&nbsp;"),"span"!=e[f]&&(c=new RegExp("<"+e[f]+"[^>]*> </"+e[f]+">","gi"),a=a.replace(c,"&nbsp;"));e=["o","v","w","m","x"];g=e.length;for(f=0;f<g;f++)0==f&&(a=a.replace(/<o:p/gi,"<raonko:p")),-1<a.indexOf("<"+e[f])&&(c=new RegExp("<"+e[f]+":[^/>]+/>","gi"),a=a.replace(c,""),c=new RegExp("<"+e[f]+":[^>]+>[^<]*</"+e[f]+":[^>]+>",
"gi"),a=a.replace(c,""),"v"==e[f]&&(c=new RegExp("<"+e[f]+":[^>]+>","gi"),a=a.replace(c,""),c=new RegExp("</"+e[f]+":[^>]+>","gi"),a=a.replace(c,""))),f==g-1&&(a=a.replace(/<raonko:p/gi,"<o:p"))}a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=a.replace(/\s>/gi,">");a=KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp(a);a=a.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");a=a.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");a=a.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");a=a.replace(/<\/th>&nbsp;<\/th>/g,
"</th></th>");if(KEDITORTOP.RAONKEDITOR.browser.ie&&10>KEDITORTOP.RAONKEDITOR.browser.ieVersion){var c=a.length,f=e=!1,h=g="",l="";if(-1==a.indexOf("<")&&-1==a.indexOf(">"))for(d=0;d<c;d++)g=a.charAt(d),h=a.charAt(d+1)," "!=g&&32!=g.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(g="&nbsp;"),l+=g;else for(d=0;d<c;d++)g=a.charAt(d),h=a.charAt(d+1),"<"==g?(e=!1,f="p"==h.toLowerCase()?!0:!1):">"==g&&1==f?e=!0:1!=e||" "!=g&&32!=g.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(g="&nbsp;"),l+=g;a=l}0==b&&(a=
KEDITORTOP.RAONKEDITOR.util.removeLocalFileImage(a));return a});"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.removeLocalFileImage&&(KEDITORTOP.RAONKEDITOR.util.removeLocalFileImage=function(a){return""==a||void 0==a?"":a=a.replace(RegExp("<img[^>]+file:///[^>]+>","gi"),"")});
"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.removeOfficeDummyTag&&(KEDITORTOP.RAONKEDITOR.util.removeOfficeDummyTag=function(a,b,c){var e=a;try{for(var d=a.indexOf(b),f=a.indexOf(c);-1<d&&-1<f;)var g=e.substring(0,d),h=e.substring(f+c.length),e=g+h,d=e.indexOf(b),f=e.indexOf(c)}catch(l){e=a}return e});"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.replaceAll&&(KEDITORTOP.RAONKEDITOR.util.replaceAll=function(a,b,c){a&&""!=a&&(a=a.split(b).join(c));return a});
"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp&&(KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp=function(a){if(3==KEDITORTOP.G_CURRKEDITOR.agentPasteFormatType&&"0"==KEDITORTOP.G_CURRKEDITOR._config.replaceOneSpaceToNbspInExcel)return a;var b=a,c,e="";try{for(var d="span font a b strong i em strike u sup sub".split(" "),f=d.length,g=0;g<f;g++){var h=!0,l=d[g];("font"==l||"b"==l||"em"==l||"sup"==l||"sub"==l)&&0>b.toLowerCase().indexOf("<"+l)&&(h=!1);if(h)for(var k=0;k<f;k++){e=
b;c=new RegExp("<"+d[g]+" *([^>?+])*>(\\s+)</"+d[k]+">","gi");reg_exp2="u"==d[k]?new RegExp("</"+d[g]+">(\\s+)<"+d[k]+"[^l]","gi"):new RegExp("</"+d[g]+">(\\s+)<"+d[k]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+d[g]+" *([^>?+])*>(\\s+)<"+d[k]+">","gi");reg_exp4="u"==d[k]?new RegExp("</"+d[g]+">(\\s+)</"+d[k]+"[^l]","gi"):new RegExp("</"+d[g]+">(\\s+)</"+d[k]+" *([^>?+])*>","gi");try{var m=b.match(c);if(m)for(var t=m.length,p=0;p<t;p++){var n=m[p];if(!("b"==d[g]&&-1<n.toLowerCase().indexOf("<br")))var q=
/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n)}if(m=b.match(reg_exp2))for(t=m.length,p=0;p<t;p++)n=m[p],"b"==d[k]&&-1<n.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n));if(m=b.match(reg_exp3))for(t=m.length,p=0;p<t;p++)n=m[p],"b"==d[g]&&-1<n.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,
r),b=b.replace(m[p],n));if(m=b.match(reg_exp4))for(t=m.length,p=0;p<t;p++)n=m[p],q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n)}catch(u){b=e}}}for(g=0;g<f;g++)if(h=!0,l=d[g],("font"==l||"b"==l||"em"==l||"sup"==l||"sub"==l)&&0>b.toLowerCase().indexOf("<"+l)&&(h=!1),h){"b"==l?(b=b.replace(/<br/gi,"<temp_br"),b=b.replace(/<\/br/gi,"</temp_br")):"u"==l&&(b=b.replace(/<ul/gi,"<temp_ul"),b=b.replace(/<\/ul/gi,"</temp_ul"));for(k=0;k<f;k++)c=new RegExp("/"+
d[g]+">\\s<"+d[k],"gi"),b=b.replace(c,"/"+d[g]+">&nbsp;<"+d[k]),c=new RegExp("/"+d[g]+">\\s\\n<"+d[k],"gi"),b=b.replace(c,"/"+d[g]+">&nbsp;<"+d[k]);"b"==l?(b=b.replace(/<temp_br/gi,"<br"),b=b.replace(/<\/temp_br/gi,"</br")):"u"==l&&(b=b.replace(/<temp_ul/gi,"<ul"),b=b.replace(/<\/temp_ul/gi,"</ul"))}}catch(v){b=a}return b});"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.rtrim&&(KEDITORTOP.RAONKEDITOR.util.rtrim=function(a){return""==a?a:a.replace(/\s+$/,"")});
"undefined"!=typeof KEDITORTOP.RAONKEDITOR&&"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.hexToBytes&&(KEDITORTOP.RAONKEDITOR.util.hexToBytes=function(a){for(var b=[],c=a.length/2,e=0,e=0;e<c;e++)b.push(parseInt(a.substr(2*e,2),16));return b});
"undefined"!=typeof KEDITORTOP.RAONKEDITOR&&"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.bytesToBase64&&(KEDITORTOP.RAONKEDITOR.util.bytesToBase64=function(a){for(var b="",c=a.length,e=0;e<c;e+=3){var d=a.slice(e,e+3),f=d.length,g=[],h=void 0;if(3>f)for(h=f;3>h;h++)d[h]=0;g[0]=(252&d[0])>>2;g[1]=(3&d[0])<<4|d[1]>>4;g[2]=(15&d[1])<<2|(192&d[2])>>6;g[3]=63&d[2];for(h=0;4>h;h++)b+=h<=f?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g[h]):"="}return b});
var htmlProcessUtilFunctionList={};htmlProcessUtilFunctionList.htmlTagRevision=htmlTagRevision;htmlProcessUtilFunctionList.SetCorrectOfficeHtml=SetCorrectOfficeHtml;htmlProcessUtilFunctionList.GetMsWordHtml=GetMsWordHtml;htmlProcessUtilFunctionList.GetMsExcelHtml=GetMsExcelHtml;htmlProcessUtilFunctionList.GetMsPptHtml2=GetMsPptHtml2;htmlProcessUtilFunctionList.GetJungumHtml=GetJungumHtml;htmlProcessUtilFunctionList.GetHanHwpHtml=GetHanHwpHtml;htmlProcessUtilFunctionList.GetStyleMap=GetStyleMap;
htmlProcessUtilFunctionList.RepaireSpanInImageTag4MsWord=RepaireSpanInImageTag4MsWord;htmlProcessUtilFunctionList.setPasteClassStyle=setPasteClassStyle;htmlProcessUtilFunctionList.setStyleToClass=setStyleToClass;htmlProcessUtilFunctionList.GetFontSizeForWordH1ToH7Tag=GetFontSizeForWordH1ToH7Tag;htmlProcessUtilFunctionList.isHwpPasteAction=isHwpPasteAction;
