(function(){try{var b={pluginName:"spellcheck"};G_KPlugin.spellcheck=b;var l=KEDITORTOP.RAONKEDITOR.util.xml;if(KEDITORTOP.RAONKEDITOR.browser.ie&&7>=KEDITORTOP.RAONKEDITOR.browser.ieVersion){var m=KEDITORTOP.G_CURRKEDITOR._config.toolbarArr1.indexOf("p_spellcheck"),n=KEDITORTOP.G_CURRKEDITOR._config.toolbarArr2.indexOf("p_spellcheck");-1<m&&KEDITORTOP.G_CURRKEDITOR._config.toolbarArr1.splice(m,1);-1<n&&KEDITORTOP.G_CURRKEDITOR._config.toolbarArr2.splice(n,1)}b.onClickToolIcon=function(){1!=b.isProcess&&
(b.isProcess=!0,showProcessingBackground(),setTimeout(function(){g_findRepalceRange=null;_k_editor._LastRange=null;doSetCaretPosition(_iframeDoc.body.firstChild,0);var q=T.toString(),q=q.replace(/,/gi,""),e=function(){if("Y"==G_SC){var a=KEDITORTOP.G_CURRKEDITOR._BODY.innerText,a=a.replace(/\u00a0/gi,""),a=a.replace(/&nbsp/gi,""),a=a.replace(/ /gi,""),a=a.replace(/\r\n/gi,""),a=a.replace(/\n/gi,""),a=a.replace(/\r/gi,""),a=a.replace(/\s/gi,"");if(""==a||null==a||void 0==a)alert(RAONKEditor_lang.plugins.spellcheck.no_content),
b.isProcess=!1,hideProcessingBackground();else{var a=KEDITORTOP.G_CURRKEDITOR._BODY.innerHTML,a=a.replace(/&nbsp;/gi," "),a=a.replace(/\+/gi,"%2B"),a=a.replace(/&amp;/gi,""),a=a.replace(/style[^>]*(.*?)/gi,""),a=a.replace(/<p><br><\/p>/gi,"\n"),a=a.replace(/<br>/gi,"\n"),a=a.replace(/<br >/gi,"\n"),a=a.replace(/<o:p>/gi,"\n"),a=a.replace(/<\/o:p>/gi,"\n"),a=a.replace(/<\/p>/gi,"\n"),a=a.replace(/<\/td>/gi,"\n"),h=new RegExp(KEDITORTOP.G_CURRKEDITOR._config.unitAttributeDelimiter,"gi"),a=a.replace(new RegExp(KEDITORTOP.G_CURRKEDITOR._config.unitDelimiter,
"gi"),""),a=a.replace(h,""),a=a.replace(/<[^>]+>/gi,""),a=a.replace(/&lt;/gi,"<"),a=a.replace(/&gt;/gi,">");b.chkWordArr=[];var a=a.split("\n"),h=a.length,f=b.checkLineCount?b.checkLineCount:h,e=b.handlerURL,e=KEDITORTOP.RAONKEDITOR.util.setProtocolBaseDomainURL(e),m=!1;for(i=0;i<h;i+=f){var d=i,c=i+f;c>=h&&(c=h);d=a.slice(d,c).join("\n");c=___;-1<c.indexOf("?")&&(c=c.substring(0,c.indexOf("?")));var k=c.indexOf("//"),c=-1<k?c.substring(0,c.substring(k+2).indexOf("/")+(k+2)+1):c.substring(0,c.indexOf("/")+
1);if(void 0==b.weakRule||null==b.weakRule||""==b.weakRule)b.weakRule=!1;d="s01"+KEDITORTOP.G_CURRKEDITOR._config.unitAttributeDelimiter+"KE"+KEDITORTOP.G_CURRKEDITOR._config.unitDelimiter+"s02"+KEDITORTOP.G_CURRKEDITOR._config.unitAttributeDelimiter+KEDITORTOP.G_CURRKEDITOR._config.productKey+KEDITORTOP.G_CURRKEDITOR._config.unitDelimiter+"s03"+KEDITORTOP.G_CURRKEDITOR._config.unitAttributeDelimiter+c+KEDITORTOP.G_CURRKEDITOR._config.unitDelimiter+"s04"+KEDITORTOP.G_CURRKEDITOR._config.unitAttributeDelimiter+
d+KEDITORTOP.G_CURRKEDITOR._config.unitDelimiter+"s05"+KEDITORTOP.G_CURRKEDITOR._config.unitAttributeDelimiter+b.weakRule;d=encodeURI("s00="+KEDITORTOP.RAONKEDITOR.util.makeEncryptParamEx(d));d=KEDITORTOP.RAONKEDITOR.util.makeDecryptReponseMessageEx(KEDITORTOP.RAONKEDITOR.ajax.postData(e,d));if(null==d||-1==d.indexOf("<?xml")&&""!=d){m=!0;break}else d=d.split("\f");for(c=0;c<d.length;c++)for(var k=KEDITORTOP.RAONKEDITOR.util.stringToXML(d[c]),n=l.count(k,"PnuErrorWord"),r=0;r<n;r++){for(var g=l.getNodeIdx(k,
"PnuErrorWord",r),t=[],p=l.count(g,"CandWord"),u=0;u<p;u++)t.push(l.getNodeValueIdx(g,"CandWord",u));g={word:l.getNodeValue(g,"OrgStr"),suggestions:t};""!=t&&-1==g.word.indexOf("\n")&&-1!=KEDITORTOP.G_CURRKEDITOR._BODY.innerText.indexOf(g.word)&&b.chkWordArr.push(g)}}if(m)return alert("HandlerURL\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \n\nspellcheck/js/config.js\uc758 handlerURL\uc758 \uac12\uc744 \ud655\uc778\ud558\uc138\uc694."),b.isProcess=!1,hideProcessingBackground(),
!1;0==b.chkWordArr.length?(alert(RAONKEditor_lang.plugins.spellcheck.compMsg),b.isProcess=!1,hideProcessingBackground()):RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,"spellcheck/editor_popup.html")}}else"N"==G_SC&&(alert(q+KEDITORTOP.RAONKEDITOR.util.makeDecryptReponseMessage(M5)),b.isProcess=!1,hideProcessingBackground())};if(""==G_SC)var f=setInterval(function(){""!=G_SC&&(e(),hideProcessingBackground(),clearInterval(f))},100);else e()},100))};b.onInit=function(){p("../js"+
(KEDITORTOP.RAONKEDITOR.isRelease?"":"_dev")+"/aes.js");var b="../plugin/spellcheck/js"+(KEDITORTOP.RAONKEDITOR.isRelease?"":"_dev")+"/config.js",b="1"==KEDITORTOP.G_CURRKEDITOR._config.useConfigTimeStamp?b+("?t="+KEDITORTOP.RAONKEDITOR.util.getTimeStamp()):b+("?ver="+KEDITORTOP.RAONKEDITOR.ReleaseVer);p(b)};var p=function(b){var e=document.getElementsByTagName("head")[0],f=document.createElement("script");f.type="text/javascript";f.src=b;e.appendChild(f)};b.onInit()}catch(v){}})();
