--------------------------------------------------------
--  颇老捞 积己凳 - 荐夸老-1岿-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SITE_USER_INFO
--------------------------------------------------------

  CREATE TABLE "WCADMIN"."SITE_USER_INFO" 
   (	"OBJ_ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(255 BYTE), 
	"CREATE_USER_NM" VARCHAR2(255 BYTE), 
	"SITE_CD" VARCHAR2(255 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(255 BYTE), 
	"UPDATE_USER_NM" VARCHAR2(255 BYTE), 
	"USE_YN" VARCHAR2(255 BYTE), 
	"USER_INFO_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into WCADMIN.SITE_USER_INFO
SET DEFINE OFF;
Insert into WCADMIN.SITE_USER_INFO (OBJ_ID,CREATE_DATE,CREATE_USER_ID,CREATE_USER_NM,SITE_CD,UPDATE_DATE,UPDATE_USER_ID,UPDATE_USER_NM,USE_YN,USER_INFO_ID) values ('966044042b1e49df93a9e814cb55105e',to_date('23/01/12','RR/MM/DD'),'wcadmin','包府磊','SU-2023-01-00004',to_date('23/01/12','RR/MM/DD'),'wcadmin','包府磊','Y','test1-2@naver.com');
--------------------------------------------------------
--  DDL for Index SYS_C0010759
--------------------------------------------------------

  CREATE UNIQUE INDEX "WCADMIN"."SYS_C0010759" ON "WCADMIN"."SITE_USER_INFO" ("OBJ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SITE_USER_INFO
--------------------------------------------------------

  ALTER TABLE "WCADMIN"."SITE_USER_INFO" ADD PRIMARY KEY ("OBJ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("OBJ_ID" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("CREATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("CREATE_USER_NM" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("SITE_CD" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("UPDATE_USER_NM" NOT NULL ENABLE);
  ALTER TABLE "WCADMIN"."SITE_USER_INFO" MODIFY ("USE_YN" NOT NULL ENABLE);
