(function(){try{var b={pluginName:"autogrow"};G_KPlugin.autogrow=b;b.onInit=function(){var a="../plugin/autogrow/js"+(KEDITORTOP.RAONKEDITOR.isRelease?"":"_dev")+"/config.js",a="1"==KEDITORTOP.G_CURRKEDITOR._config.useConfigTimeStamp?a+("?t="+KEDITORTOP.RAONKEDITOR.util.getTimeStamp()):a+("?ver="+KEDITORTOP.RAONKEDITOR.ReleaseVer),c=document.getElementsByTagName("head")[0],b=document.createElement("script");b.type="text/javascript";b.src=a;c.appendChild(b)};b.onLoaded=function(){"0"!=KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode&&
(G_KPlugin.autogrow.autoGrowMode=KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode);-1<KEDITORTOP.G_CURRKEDITOR._config.style.height.indexOf("%")&&(KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode="0",G_KPlugin.autogrow.autoGrowMode="0");"2"==KEDITORTOP.G_CURRKEDITOR._config.ruler.mode&&(KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode="0",G_KPlugin.autogrow.autoGrowMode="0");KEDITORTOP.RAONKEDITOR.browser.ie&&9>KEDITORTOP.RAONKEDITOR.browser.ieVersion&&(KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode="0",G_KPlugin.autogrow.autoGrowMode=
"0");KEDITORTOP.KEDITORWIN!=top&&"1"==KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode&&(KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode="0",G_KPlugin.autogrow.autoGrowMode="0");"0"!=G_KPlugin.autogrow.autoGrowMode&&"0"!=KEDITORTOP.G_CURRKEDITOR._config.autoGrowMode&&(KEDITORTOP.G_CURRKEDITOR._config.useLineBreak="1",KEDITORTOP.G_CURRKEDITOR._config.wordWrapType="1",KEDITORTOP.G_CURRKEDITOR._config.resize_bar="0")};b.onChange=function(){b.autogrow(KEDITORTOP.G_CURRKEDITOR)};b.onCommand=function(){b.autogrow(KEDITORTOP.G_CURRKEDITOR)};
b.autogrow=function(a){if("0"!=G_KPlugin.autogrow.autoGrowMode&&void 0!=G_KPlugin.autogrow.autoGrowMode)if("full_size"==a.FrameStatus||"design"!=a._currentMode)a._DOC.documentElement.style.overflow="auto";else{var b=a._DOC.documentElement,c=a._BODY,e=KEDITORTOP.KEDITORDOC.documentElement,g=KEDITORTOP.KEDITORDOC.body;if(void 0==G_KPlugin.autogrow.configHeight||null==G_KPlugin.autogrow.configHeight||""==G_KPlugin.autogrow.configHeight)G_KPlugin.autogrow.configHeight=0>a._defaultHeight?parseInt(a._config.style.height,
10)-a._defaultHeight:parseInt(a._config.style.height,10),G_KPlugin.autogrow.initHeight=0<=a._defaultHeight?a._defaultHeight:0,b.style.overflowY="hidden",G_KPlugin.autogrow.initParentHeight=e.scrollHeight;else{b.style.overflowY="hidden";G_KPlugin.autogrow.previousParentTop=Math.max(e.scrollTop,g.scrollTop);setHeight(G_KPlugin.autogrow.configHeight,a);var f=Math.max(b.scrollHeight,c.scrollHeight),d;if(G_KPlugin.autogrow.initHeight<f){d=0==G_KPlugin.autogrow.initHeight?G_KPlugin.autogrow.configHeight+
(f-a._defaultHeight):G_KPlugin.autogrow.configHeight+(f-G_KPlugin.autogrow.initHeight);setHeight(d,a);try{b.scrollHeight>b.clientHeight?(d+=b.scrollHeight-b.clientHeight+1,setHeight(d,a)):c.scrollHeight>c.clientHeight&&(d+=c.scrollHeight-c.clientHeight+1,setHeight(d,a))}catch(l){}}else setHeight(G_KPlugin.autogrow.configHeight,a);G_KPlugin.autogrow.currHeight=f-G_KPlugin.autogrow.initHeight;G_KPlugin.autogrow.diffHeight=G_KPlugin.autogrow.currHeight-G_KPlugin.autogrow.preHeight;G_KPlugin.autogrow.preHeight=
f-G_KPlugin.autogrow.initHeight;2!=G_KPlugin.autogrow.autoGrowMode&&(e.scrollTop=G_KPlugin.autogrow.previousParentTop+(e.scrollHeight-G_KPlugin.autogrow.initParentHeight),g.scrollTop=G_KPlugin.autogrow.previousParentTop+(e.scrollHeight-G_KPlugin.autogrow.initParentHeight),G_KPlugin.autogrow.previousParentTop=Math.max(e.scrollTop,g.scrollTop),G_KPlugin.autogrow.initParentHeight=e.scrollHeight);if(2==G_KPlugin.autogrow.autoGrowMode)try{"function"===typeof KEDITORTOP.KEDITORWIN.RAONKEDITOR_AutoGrowEvent&&
KEDITORTOP.KEDITORWIN.RAONKEDITOR_AutoGrowEvent(a,{diffHeight:G_KPlugin.autogrow.diffHeight})}catch(m){}}}};b.onInit()}catch(c){}})();
function setHeight(b,c){var a=c.ID;c=KEDITORTOP.RAONKEDITOR.util._setEditor(a);if(void 0==a||""==a)a=c.ID;var h=KEDITORTOP.KEDITORDOC.getElementById("raonk_frame_holder"+a),a=KEDITORTOP.KEDITORDOC.getElementById("raonk_frame_"+a).contentWindow.document.getElementById("ue_editor_holder_"+a),k=0,k=c.baseMenuToolbarHeight;isViewMode(c)?c._defaultHeight=parseInt(b,10)-4:c._defaultHeight=parseInt(b,10)-k;-1<b.toString().indexOf("%")||-1<b.toString().indexOf("px")?h.style.height=b:h.style.height=b+"px";
a.style.height=c._defaultHeight+"px";1==G_KPlugin.autogrow.autoGrowMode&&(c._config.style.height=b+"px","1"==c._config.ruler.view&&"design"==c._currentMode&&c._FRAMEWIN.showRuler(c),"1"==c._config.autoBodyFit&&(c._BODY.style.minHeight=(c._defaultHeight-parseIntOr0(c._config.defaultBodySpace.value))/c._defaultHeight*100+"%"))};
