(function(){try{var g={pluginName:"forbiddenword"};G_KPlugin.forbiddenword=g;if(KEDITORTOP.RAONKEDITOR.browser.ie&&7>=KEDITORTOP.RAONKEDITOR.browser.ieVersion){var m=KEDITORTOP.G_CURRKEDITOR._config.toolbarArr1.indexOf("p_forbiddenword"),n=KEDITORTOP.G_CURRKEDITOR._config.toolbarArr2.indexOf("p_forbiddenword");-1<m&&KEDITORTOP.G_CURRKEDITOR._config.toolbarArr1.splice(m,1);-1<n&&KEDITORTOP.G_CURRKEDITOR._config.toolbarArr1.splice(n,1)}g.onClickToolIcon=function(){try{if(1!=g.isProcess){g.isProcess=
!0;showProcessingBackground();var p=KEDITORTOP.G_CURRKEDITOR._BODY.innerText;if(KEDITORTOP.RAONKEDITOR.IsEmpty(KEDITORTOP.G_CURRKEDITOR.ID))return alert(RAONKEditor_lang.plugins.forbiddenword.no_content),g.isProcess=!1,hideProcessingBackground(),!1;var d=KEDITORTOP.G_CURRKEDITOR._config.forbiddenWord,a=d.split(","),f=[];a.sort(function(c,f){if(c.length<f.length)return 1;if(c.length>f.length)return-1;var a=c,b=f,d=null,g="number"==typeof b&&"number"==typeof a;if(!g){for(var h=a.length,k=b.length,p=
"",l="",r="",e=0;e<h&&!(e+1>k);e++){var m=a.substring(e,e+1),n=b.substring(e,e+1);if(m==n)p=a.substring(e+1),l=b.substring(e+1),r=isNaN(parseInt(m,10))||isNaN(parseInt(n,10))?"":r+m;else break}""!=p&&(a=r+p);""!=l&&(b=r+l);if(!isNaN(parseInt(a.substring(0,1),10))&&!isNaN(parseInt(b.substring(0,1),10)))if(parseInt(b,10)!=parseInt(a,10))d=parseInt(b,10)>parseInt(a,10);else{h=a.length;for(e=d=0;e<h;e++)if(isNaN(parseInt(a.substring(e,e+1),10))){d=e;break}h=b.length;for(e=k=0;e<h;e++)if(isNaN(parseInt(b.substring(e,
e+1),10))){k=e;break}d=k<d}}null==d&&(d=g?b>a:KEDITORTOP.RAONKEDITOR.browser.opera||KEDITORTOP.RAONKEDITOR.browser.chrome?0>a.localeCompare(b,"en-us"):0>a.localeCompare(b));return d?1:-1});if(""!=d&&null!=d&&void 0!=d)for(d=0;d<a.length;d++){var h=null;if(h=p.match(new RegExp(a[d],"ig")))for(var c=0,b=0;b<h.length;b++){var c=p.indexOf(h[b],c),l={word:h[b],indexOf:c},c=c+a[d].length;f.push(l);for(var k=0;k<f.length-1;k++)-1<f[k].word.indexOf(l.word)&&f[k].indexOf<=l.indexOf&&f[k].indexOf+f[k].word.length>=
l.indexOf&&f.splice(f.length-1,1)}}if(0==f.length)return alert(RAONKEditor_lang.plugins.forbiddenword.compMsg),g.isProcess=!1,hideProcessingBackground(),!1;f.sort(function(a,b){return a.indexOf>b.indexOf?1:a.indexOf<b.indexOf?-1:0});g.chkWordArr=f;RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,"forbiddenword/editor_popup.html");hideProcessingBackground()}}catch(m){g.isProcess=!1,hideProcessingBackground()}};g.setPopup=function(g,d,a){try{var f=KEDITORTOP.KEDITORDOC.getElementById("raonk_frame_"+
KEDITORTOP.G_CURRKEDITOR.ID).contentWindow,h=f.rangy.createRange(a.document.getElementById("copycontent").contentWindow.document);if(0==g.length)return!1;for(var c=0;c<g.length;c++)if(h.findText(g[c].word)){h.deleteContents();var b=a.document.createElement("span");b.setAttribute("id","cnt"+c);b.setAttribute("class","cnt");b.setAttribute("onmouseover","parent.forbidden_word_over(this)");b.setAttribute("onmouseout","parent.forbidden_word_out(this)");var l=document.createElement("span");l.setAttribute("class",
"wordspan");l.innerText=g[c].word;var k=a.document.createElement("sup"),m=a.document.createTextNode(c+1+")");k.appendChild(m);b.appendChild(k);b.appendChild(l);h.insertNode(b);h.selectNode(b);d?h.collapse(!1):h.collapse(!0);var q=a.document.createElement("dl");q.setAttribute("id","list"+c);q.setAttribute("value",c);-1!=f.G_KPlugin.forbiddenword.chkWordArr[c].word.indexOf("'")?q.innerHTML='<div class="forbiddenDiv"><div class="forbiddenWord" onclick="scroll_to_text_click(this)"><p>'+(c+1)+") "+f.G_KPlugin.forbiddenword.chkWordArr[c].word+
'</p></div><div class="forbiddenBtn"><button onclick="delete_btn_click(this)" class="forbiddenDBtn">'+RAONKEditor_lang.plugins.forbiddenword.word_delete+'</button> <button onclick="permit_btn_click(this)" class="forbiddenPBtn">'+RAONKEditor_lang.plugins.forbiddenword.permit+"</button>":q.innerHTML+="<div class='forbiddenDiv'><div class='forbiddenWord' onclick='scroll_to_text_click(this)'><p>"+(c+1)+") "+f.G_KPlugin.forbiddenword.chkWordArr[c].word+"</p></div><div class='forbiddenBtn'><button onclick='delete_btn_click(this)' class='forbiddenDBtn'>"+
RAONKEditor_lang.plugins.forbiddenword.word_delete+"</button> <button onclick='permit_btn_click(this)' class='forbiddenPBtn'>"+RAONKEditor_lang.plugins.forbiddenword.permit+"</button>";a.document.getElementById("wordlist").appendChild(q)}hideProcessingBackground()}catch(n){}}}catch(t){}command_forbidden_word=function(m,d,a){g.callbackType=a;g.onClickToolIcon()}})();
