var G_RW_GRID=function(p,l){var q=function(a){return a.replace(/[^-\.0-9]/g,"").replace(/(?!^.*)-/,"")};document.getElementsByTagName("head")[0].appendChild(document.createElement("style"));var t=document.styleSheets[document.styleSheets.length-1],m=function(a,b){"insertRule"in t?t.insertRule(".gridTable "+a+"{"+b+"}",0):"addRule"in t&&t.addRule(".gridTable "+a,b,1)},v=function(a){};l||(l={});l.data||(l.rowSize||(l.rowSize=2),l.columnSize||(l.columnSize=4));l.event||(l.event={});var e,d,g,u,n=[],
c;this.setSaveInSession=function(a){l.saveInSession=a?!0:!1};this.isSaveInSession=function(){return l.saveInSession};this.setEditable=function(a){l.editable=a?!0:!1};this.isEditable=function(){return l.editable};this.setShowRowIndex=function(a){l.showRowIndex=a?!0:!1;this.fillTable()};this.isShowRowIndex=function(){return l.showRowIndex};this.getRowIndexFlag=function(){return this.isShowRowIndex()?1:0};this.setShowColumnIndex=function(a){l.showColumnIndex=a?!0:!1;d.refreshHead()};this.isShowColumnIndex=
function(){return l.showColumnIndex};this.getColumnIndexFlag=function(){return this.isShowColumnIndex()?1:0};this.setIndexDraggable=function(a){l.indexDraggable=a?!0:!1};this.isIndexDraggable=function(){return l.indexDraggable};this.setShowRowTitle=function(a){l.showRowTitle=a?!0:!1;if(!a){a=this.getRowSize();for(var b=this.getColumnTitleFlag();b<a;b++)g[b][0]=q(g[b][0])}this.fillTable()};this.isShowRowTitle=function(){return l.showRowTitle};this.getRowTitleFlag=function(){return this.isShowRowTitle()?
1:0};this.setShowColumnTitle=function(a){l.showColumnTitle=a?!0:!1;if(!a){a=this.getColumnSize();for(var b=this.getRowTitleFlag();b<a;b++)g[0][b]=q(g[0][b])}this.fillTable()};this.isShowColumnTitle=function(){return l.showColumnTitle};this.getColumnTitleFlag=function(){return this.isShowColumnTitle()?1:0};this.setColumnResizable=function(a){l.columnResizable=a?!0:!1};this.isColumnResizable=function(){return l.columnResizable};this.selectedCell=this.modifyingCell=null;this.setData=function(a){if(a){g=
a;a=this.getRowSize();for(var b=this.getColumnSize(),f=0;f<a;f++)if(g[f].length<b)for(var c=g[f].length;c<b;c++)g[f][c]="";for(f=0;f<b;f++)n[f]=60}else g=[];this.isSaveInSession()&&sessionStorage.setItem("gridData",g);return g};this.getSessionData=function(){this.isSaveInSession()&&sessionStorage.getItem("gridData")};this.getData=function(){return g};this.getRowData=function(a){return g[a]};this.getColumnData=function(a){for(var b=[],f=0;f<this.getRowSize();f++)b.push(g[f][a]);return b};this.getRowSize=
function(){return g.length};this.setRowSize=function(a){if(this.isShowRowTitle()&&this.isShowColumnTitle()&&2>a)return!1;for(var b=this.getRowSize(),f=this.getColumnSize();a!=b;){if(a<b)g.pop();else{g[b]=[];for(var c=0;c<f;c++)g[b][c]=""}b=this.getRowSize()}this.fillTable()};this.getColumnSize=function(){for(var a=g[0].length,b=this.getRowSize(),f=1;f<b;f++)a<g[f].length&&(a=g[f].length);return a};this.setColumnSize=function(a){if(this.isShowRowTitle()&&this.isShowColumnTitle()&&2>a)return!1;for(var b=
this.getRowSize(),f=this.getColumnSize();a!=f;){if(a<f){n[f-1]&&n.pop();for(var c=0;c<b;c++)g[c].pop()}else for(n[f]||(n[f]=60),c=0;c<b;c++)g[c][f]="";f=this.getColumnSize()}this.fillTable()};this.insertRow=function(){var a=d.createRow();g[this.getRowSize()]=[""];for(var b=this.getColumnSize(),f=0;f<b;f++){var c=d.insertCell(a);this.setCellValue("",c)}};this.insertColumn=function(){for(var a=this.getRowSize(),b=this.getColumnSize(),f=0;f<a;f++){var c=d.insertCell(d.getRow(f));n[b]||(n[b]=60);c.style.width=
n[f];this.setCellValue("",c)}};this.removeLastRow=function(){var a=this.getRowSize()-1;if(0==a)return!1;d.removeRow(a);g.pop()};this.removeLastColumn=function(){this.getColumnSize();for(var a=this.getRowSize(),b=0;b<a;b++){var f=d.getRow(b);f.removeChild(f.lastChild);g[b].pop()}};this.getCellValue=function(a,b){return g[a][b]?g[a][b]:""};this.setCellValue=function(a,b){var f=d.getRowIndex(b),c=d.getColumnIndex(b),e={value:a,rowIndex:f,columnIndex:c,afterCallback:function(a){}};if(g[f][c]!=a){if(0==
this.onCellChange(e))return!1;a=e.value;if(f!=e.rowIndex||c!=e.columnIndex)f=e.rowIndex,c=e.columnIndex,b=d.getCell(f,c);this.isSaveInSession()&&sessionStorage.setItem("gridData",JSON.stringify(g))}g[f][c]=a;3<b.innerHTML.length&&(b.scrollLeft=0);b.innerHTML=a;b.title=a;e.afterCallback(e)};this.fillTable=function(a){if(!u&&!a)return!1;d.emptyBody();a=this.getColumnSize();if(this.isShowColumnTitle()){var b=d.createRow();b.className+=" title";this.isShowRowTitle()&&(d.insertCell(b).className+=" blank");
for(var f,c=this.getRowTitleFlag();c<a;c++)f=d.insertCell(b),f.innerHTML=g[0][c],f.title=g[0][c];f.className+=" end"}for(var b=this.getRowSize(),e,k,l=this.isShowRowTitle(),m=this.getRowTitleFlag(),c=this.getColumnTitleFlag();c<b;c++){e=d.createRow();l&&(f=d.insertCell(e),f.className+=" title",f.innerHTML=g[c][0],f.title=g[c][0]);for(f=m;f<a;f++)if(k=d.insertCell(e),value=g[c][f])k.innerHTML=value,k.title=value;k.className+=" end"}e.className+=" end";this.isShowColumnIndex()&&d.refreshHead(!0)};this.modifyCell=
function(a,b){(b.modifying=a)?(this.modifyingCell=b,this.selectCell(b)):this.modifyingCell=null};this.saveCell=function(){var a=this.modifyingCell;a&&(this.modifyCell(!1,a),this.setCellValue(a.childNodes[0].value,a))};this.selectCell=function(a){this.selectedCell&&(this.selectedCell.className=this.selectedCell.className.replace(/ selectedCell/g,""),this.selectedCell.tabIndex=-1);this.selectedCell=a;a.tabIndex=0;a.className+=" selectedCell";a.focus()};this.changeRow=function(a,b){var c=d.getRowIndex(a),
e=d.getRowIndex(b);this.saveCell();for(var r=this.getColumnSize(),k=0;k<r;k++){var l=g[e][k];this.setCellValue(g[c][k],d.getCell(e,k));this.setCellValue(l,d.getCell(c,k))}l=b.innerHTML;b.innerHTML=a.innerHTML;a.innerHTML=l};this.changeColumn=function(a,b){var c=d.getColumnIndex(a),e=d.getColumnIndex(b);this.saveCell();for(var r=this.getRowSize(),k=0;k<r;k++){var l=g[k][e];this.setCellValue(g[k][c],d.getCell(k,e));this.setCellValue(l,d.getCell(k,c))}d.refreshHead()};this.rotateTable=function(){this.saveCell();
for(var a=[],b=this.getRowSize(),c=this.getColumnSize(),e=0;e<b;e++)for(var d=0;d<c;d++)a[d]||(a[d]=[]),a[d][e]=g[e][d];this.setData(a);this.fillTable()};this.Table={createTable:function(){if(this.table)return!1;l.parent?(this.table=document.createElement("table"),this.table.id=p,l.parent.appendChild(this.table)):u?(this.table=document.createElement("table"),this.table.id=p,document.body.appendChild(this.table)):(document.write('<table id="'+p+'"></table>'),this.table=document.getElementById(p));
if(!this.table)return!1;this.table.className="gridTable";this.table.tabIndex=0;this.table.createTHead();e.isShowColumnIndex()&&this.table.tHead.insertRow();this.table.appendChild(document.createElement("tbody"));this.table.onmousedown=this.tableMouseDown;var a=this.table.ownerDocument,b=this.documentMouseMove;a.addEventListener?a.addEventListener("mousemove",b):a.attachEvent("onmousemove",b);a=this.table.ownerDocument;b=this.documentMouseUp;a.addEventListener?a.addEventListener("mouseup",b):a.attachEvent("onmouseup",
b);this.table.onkeydown=this.tableKeyDown;this.table.onkeyup=this.tableKeyUp;return this.table},createRow:function(){var a=document.createElement("tr");this.table.tBodies[0].appendChild(a);if(e.isShowRowIndex()){var b=document.createElement("th");b.innerHTML=a.rowIndex;a.appendChild(b);e.isIndexDraggable()&&(1==a.rowIndex&&e.isShowColumnTitle()||this.setDragHandler(b))}return a},insertCell:function(a){var b=document.createElement("td");e.isEditable()&&(b.onclick=this.cellClick);a.appendChild(b);return b},
refreshHead:function(a){if(!u&&!a)return!1;this.table.tHead.deleteRow(0);if(e.isShowColumnIndex()){a=document.createElement("tr");this.table.tHead.appendChild(a);if(e.isShowRowIndex()){var b=document.createElement("th");b.className+=" blank";b.style.width="40px";a.appendChild(b)}for(var b=e.getColumnSize(),c=0;c<b;c++){var d=document.createElement("th");d.style.width=n[c]+"px";a.appendChild(d);if(e.isColumnResizable()){var g=document.createElement("span");g.className+=" resize";g.draggable=!0;g.innerHTML=
"&nbsp;";d.appendChild(g)}e.isIndexDraggable()&&(1==d.cellIndex&&e.isShowRowTitle()||this.setDragHandler(d));d.innerHTML+=c+1}}},emptyBody:function(){this.table.removeChild(this.table.tBodies[0]);e.selectedCell=null;this.table.appendChild(document.createElement("tbody"))},getRow:function(a){return this.table.tBodies[0].childNodes[a]},getCell:function(a,b){return this.table.tBodies[0].childNodes[a].childNodes[b+e.getRowIndexFlag()]},getRowIndex:function(a){return a.parentElement.rowIndex-e.getColumnIndexFlag()},
getColumnIndex:function(a){return a.cellIndex-e.getRowIndexFlag()},removeRow:function(a){this.table.tBodies[0].removeChild(this.getRow(a))},editCell:function(a){if(a.modifying)return!1;e.saveCell();if(-1<a.className.indexOf("blank"))return e.selectCell(a),!1;var b=a.clientWidth-9+"px",c=a.clientHeight-10+"px";e.modifyCell(!0,a);a.cellValue=a.innerHTML;a.innerHTML="<input/>";var d=a.childNodes[0];-1==a.className.indexOf("title")&&-1==a.parentElement.className.indexOf("title")&&(d.className+=" number");
d.style.width=b;d.style.height=c;d.onkeydown=this.inputKeyDown;d.onkeyup=this.inputKeyUp;d.onblur=this.inputBlur;d.focus();d.value=a.cellValue},makeDragDummy:function(){switch(c.type){case "columnIndex":c.index=d.getColumnIndex(c.target);var a=c.dummy=document.createElement("table");a.id="dummyTable";a.className="gridTable";a.style.position="fixed";a.style.width=n[c.index]+"px";c.targetRect=c.target.getBoundingClientRect();c.lastTarget=c.target;a.style.left=c.targetRect.left+"px";d.table.parentElement.insertBefore(a,
d.table);var b=a.createTHead(),f=document.createElement("tr");b.appendChild(f);b=document.createElement("th");b.style.cursor="move";b.innerHTML=c.target.innerHTML;b.style.backgroundColor="yellow";f.appendChild(b);var h=document.createElement("tbody");a.appendChild(h);for(var r=e.getRowSize(),k=e.isShowColumnTitle(),a=0;a<r;a++)b=d.getCell(a,c.index),b.innerHTML="",f=document.createElement("tr"),0==a&&k&&(f.className="title"),h.appendChild(f),b=document.createElement("td"),b.style.borderColor="transparent",
b.innerHTML=g[a][c.index],f.appendChild(b);f.className+=" end";c.lastIndex=c.index;break;case "rowIndex":c.index=d.getRowIndex(c.target);a=c.dummy=document.createElement("table");a.id="dummyTable";a.className="gridTable";a.style.position="fixed";c.targetRect=c.target.getBoundingClientRect();c.lastTarget=c.target;a.style.top=c.targetRect.top+"px";d.table.parentElement.insertBefore(a,d.table);h=document.createElement("tbody");a.appendChild(h);f=document.createElement("tr");h.appendChild(f);b=document.createElement("th");
b.innerHTML=c.target.innerHTML;b.style.width="40px";b.style.backgroundColor="yellow";f.appendChild(b);h=e.getColumnSize();r=e.isShowRowTitle();for(a=0;a<h;a++)b=d.getCell(c.index,a),b.innerHTML="",b=document.createElement("td"),0==a&&r&&(b.className="title"),b.style.border="0px",b.style.width=n[a]+"px",b.style.borderColor="transparent",b.innerHTML=g[c.index][a],f.appendChild(b);c.lastIndex=c.index;break;case "columnResize":c.index=d.getColumnIndex(c.target),a=c.dummy=document.createElement("div"),
a.style.border="1px dashed black",a.style.position="fixed",c.tableRect=d.table.getBoundingClientRect(),c.targetRect=c.target.getBoundingClientRect(),a.style.height=c.tableRect.bottom-c.tableRect.top-2+"px",a.style.width="1px",a.style.left=c.targetRect.right-3+"px",d.table.parentElement.insertBefore(a,d.table)}},tableMouseDown:function(a){a=a||event;var b=a.target||a.srcElement;if("input"==b.tagName.toLowerCase())return!0;if(e.isIndexDraggable()&&b.draggable){e.modifyingCell&&e.saveCell();c&&c.dummy&&
c.dummy.parentElement.removeChild(c.dummy);c={target:b};c.action=a.altKey?"alt":"move";if("th"==c.target.tagName.toLowerCase())"thead"==c.target.parentElement.parentElement.tagName.toLowerCase()?c.type="columnIndex":c.type="rowIndex";else if("span"==c.target.tagName.toLowerCase())if(c.target=c.target.parentElement,"thead"==c.target.parentElement.parentElement.tagName.toLowerCase())c.type="columnResize";else return c=!1;else return c=!1;d.makeDragDummy();return!1}if(e.modifyingCell)return e.modifyingCell.childNodes[0].focus(),
!1;e.selectedCell?e.selectCell(e.selectedCell):e.selectCell(d.getCell(0,0));return!1},documentMouseMove:function(a){if(c){a=a||event;var b=a.target||a.srcElement;switch(c.type){case "columnIndex":if("th"==c.target.tagName.toLowerCase()&&("th"==b.tagName.toLowerCase()||"td"==b.tagName.toLowerCase())&&b.parentElement.parentElement.parentElement==c.target.parentElement.parentElement.parentElement){a=d.getColumnIndex(b);if(a<e.getRowTitleFlag())return!1;var f=e.getRowSize(),b=b.getBoundingClientRect();
c.dummy.style.top=c.targetRect.top+"px";c.dummy.style.left=b.left+"px";c.dummy.style.width=n[a]+"px";if(a==c.lastIndex)return!1;if("move"==c.action)if(c.lastIndex>a){for(b=c.lastIndex;b>a;b--){var h=d.table.tHead.childNodes[0].childNodes[b+e.getRowIndexFlag()],g=d.table.tHead.childNodes[0].childNodes[b-1+e.getRowIndexFlag()];h.innerHTML=g.innerHTML;g.innerHTML=""}for(var k=0;k<f;k++)for(b=c.lastIndex;b>a;b--)h=d.getCell(k,b),g=d.getCell(k,b-1),h.innerHTML=g.innerHTML,g.innerHTML=""}else{for(b=c.lastIndex;b<
a;b++)h=d.table.tHead.childNodes[0].childNodes[b+e.getRowIndexFlag()],g=d.table.tHead.childNodes[0].childNodes[b+1+e.getRowIndexFlag()],h.innerHTML=g.innerHTML,g.innerHTML="";for(k=0;k<f;k++)for(b=c.lastIndex;b<a;b++)h=d.getCell(k,b),g=d.getCell(k,b+1),h.innerHTML=g.innerHTML,g.innerHTML=""}else if("alt"==c.action)for(h=d.table.tHead.childNodes[0].childNodes[a+e.getRowIndexFlag()],g=d.table.tHead.childNodes[0].childNodes[c.lastIndex+e.getRowIndexFlag()],b=h.innerHTML,h.innerHTML=g.innerHTML,a!=c.index?
(h=d.table.tHead.childNodes[0].childNodes[c.index+e.getRowIndexFlag()],g.innerHTML=h.innerHTML,h.innerHTML=b):g.innerHTML=b,k=0;k<f;k++)h=d.getCell(k,a),g=d.getCell(k,c.lastIndex),b=h.innerHTML,h.innerHTML=g.innerHTML,a!=c.index?(h=d.getCell(k,c.index),g.innerHTML=h.innerHTML,h.innerHTML=b):g.innerHTML=b;c.lastIndex=a}break;case "rowIndex":if("th"==c.target.tagName.toLowerCase()&&("th"==b.tagName.toLowerCase()||"td"==b.tagName.toLowerCase())&&b.parentElement.parentElement==c.target.parentElement.parentElement){a=
d.getRowIndex(b);if(a<e.getColumnTitleFlag())return!1;b=b.getBoundingClientRect();c.dummy.style.top=b.top+"px";if(a==c.lastIndex)return!1;f=c.target.parentElement.parentElement;if("move"==c.action)if(c.lastIndex>a)for(b=c.lastIndex;b>a;b--)g=d.getRow(b),k=d.getRow(b-1),f.insertBefore(k,g.nextSibling);else for(b=c.lastIndex;b<a;b++)g=d.getRow(b),k=d.getRow(b+1),f.insertBefore(k,g);else"alt"==c.action&&(g=d.getRow(a),b=g.nextSibling,k=d.getRow(c.lastIndex),h=k.nextSibling,a<c.lastIndex?b?f.insertBefore(k,
g):f.appendChild(k):b?f.insertBefore(k,b):f.appendChild(k),c.index!=c.lastIndex?a!=c.index?(b=d.getRow(c.index),k=b.nextSibling,f.insertBefore(b,g),k?f.insertBefore(g,k):f.appendChild(g)):h?f.insertBefore(g,h):f.appendChild(g):h?f.insertBefore(g,h):f.appendChild(g));c.lastIndex=a}break;case "columnResize":f=c.target.getBoundingClientRect(),c.dummy.style.top=f.top+"px",c.dummy.style.left=a.clientX>c.targetRect.left+16?a.clientX+"px":c.targetRect.left+16+"px"}}},documentMouseUp:function(a){if(c){switch(c.type){case "columnIndex":a=
e.getColumnData(c.index);var b=e.getRowSize();if("move"==c.action)if(c.index>c.lastIndex)for(var f=0;f<b;f++){for(var h=c.index;h>c.lastIndex;h--)e.setCellValue(g[f][h-1],d.getCell(f,h));e.setCellValue(a[f],d.getCell(f,c.lastIndex))}else for(f=0;f<b;f++){for(h=c.index;h<c.lastIndex;h++)e.setCellValue(g[f][h+1],d.getCell(f,h));e.setCellValue(a[f],d.getCell(f,c.lastIndex))}else if("alt"==c.action)for(f=0;f<b;f++)e.setCellValue(g[f][c.lastIndex],d.getCell(f,c.index)),e.setCellValue(a[f],d.getCell(f,
c.lastIndex));c.dummy.parentElement.removeChild(c.dummy);d.refreshHead();break;case "rowIndex":a=e.getRowData(c.index).slice();b=e.getColumnSize();if("move"==c.action)if(c.index>c.lastIndex)for(h=0;h<b;h++){for(f=c.index;f>c.lastIndex;f--)e.setCellValue(g[f-1][h],d.getCell(f,h));e.setCellValue(a[h],d.getCell(c.lastIndex,h))}else for(h=0;h<b;h++){for(f=c.index;f<c.lastIndex;f++)e.setCellValue(g[f+1][h],d.getCell(f,h));e.setCellValue(a[h],d.getCell(c.lastIndex,h))}else if("alt"==c.action)for(h=0;h<
b;h++)e.setCellValue(g[c.lastIndex][h],d.getCell(c.index,h)),e.setCellValue(a[h],d.getCell(c.lastIndex,h));c.dummy.parentElement.removeChild(c.dummy);e.fillTable();break;case "columnResize":n[c.index]=c.dummy.offsetLeft-c.targetRect.left,d.refreshHead(),c.dummy.parentElement.removeChild(c.dummy)}c=!1}},tableKeyDown:function(a){a=a||event;if("input"==(a.target||a.srcElement).tagName.toLowerCase())return!0;switch(a.keyCode){case 9:if(!e.selectedCell)return e.selectCell(d.getCell(0,0)),!1;var b=e.selectedCell,
c=d.getRowIndex(b),b=d.getColumnIndex(b);if(a.shiftKey)if(--b,0>b){c--;if(0>c)break;a=d.getCell(c,e.getColumnSize()-1)}else a=d.getCell(c,b);else if(b+=1,b>=e.getColumnSize()){c++;if(c>=e.getRowSize())break;a=d.getCell(c,0)}else a=d.getCell(c,b);e.selectCell(a);return!1;case 13:if(!e.selectedCell)return!1;b=e.selectedCell;d.editCell(b);return!1;case 37:if(!e.selectedCell)return e.selectCell(d.getCell(0,0)),!1;b=e.selectedCell;c=d.getRowIndex(b);b=d.getColumnIndex(b)-1;if(a.ctrlKey)b=0;else if(0>b)return!1;
a=d.getCell(c,b);e.selectCell(a);return!1;case 38:if(!e.selectedCell)return e.selectCell(d.getCell(0,0)),!1;b=e.selectedCell;c=d.getRowIndex(b)-1;b=d.getColumnIndex(b);if(a.ctrlKey)c=0;else if(0>c)return!1;a=d.getCell(c,b);e.selectCell(a);return!1;case 39:if(!e.selectedCell)return e.selectCell(d.getCell(0,0)),!1;b=e.selectedCell;c=d.getRowIndex(b);b=d.getColumnIndex(b)+1;if(a.ctrlKey)b=e.getColumnSize()-1;else if(b>=e.getColumnSize())return!1;a=d.getCell(c,b);e.selectCell(a);return!1;case 40:if(!e.selectedCell)return e.selectCell(d.getCell(0,
0)),!1;b=e.selectedCell;c=d.getRowIndex(b)+1;b=d.getColumnIndex(b);if(a.ctrlKey)c=e.getRowSize()-1;else if(c>=e.getRowSize())return!1;a=d.getCell(c,b);e.selectCell(a);return!1;case 46:if(!e.selectedCell)return!1;b=e.selectedCell;e.setCellValue("",b);b.focus();return!1}},tableKeyUp:function(a){a=a||event;switch(a.keyCode){case 27:a.stopImmediatePropagation()}},inputKeyDown:function(a){a=a||event;-1<this.className.indexOf("number")&&(this.value=q(this.value));var b=this.parentElement;switch(a.keyCode){case 9:var c=
d.getRowIndex(b),b=d.getColumnIndex(b);if(a.shiftKey)if(b--,0>b){c--;if(0>c){e.saveCell();break}a=d.getCell(c,e.getColumnSize()-1)}else a=d.getCell(c,b);else if(b++,b>=e.getColumnSize()){c++;if(c>=e.getRowSize()){e.saveCell();break}a=d.getCell(c,0)}else a=d.getCell(c,b);d.editCell(a);return!1;case 13:return b.focus(),!1;case 27:return e.modifyCell(!1,b),b.innerHTML=b.cellValue,b.focus(),!1;case 38:return c=d.getRowIndex(b),b=d.getColumnIndex(b),0<=c-1&&(a=d.getCell(c-1,b),d.editCell(a)),!1;case 40:return c=
d.getRowIndex(b),b=d.getColumnIndex(b),c+1<e.getRowSize()&&(a=d.getCell(c+1,b),d.editCell(a)),!1}if(-1<this.className.indexOf("number")){this.value=q(this.value);if(109==a.keyCode||173==a.keyCode||189==a.keyCode)return-1<this.value.indexOf("-")||(this.value=q("-"+this.value)),!1;if(107==a.keyCode||(61==a.keyCode||187==a.keyCode)&&a.shiftKey)this.value=this.value.replace(/-/g,"");if(110==a.keyCode||190==a.keyCode)return-1<this.value.indexOf(".")?!1:!0;switch(a.keyCode){case 8:case 9:case 13:case 27:case 35:case 36:case 37:case 38:case 39:case 40:case 46:return!0;
case 65:case 67:case 86:case 88:case 90:if(a.ctrlKey||a.metaKey)return!0}if(!(47<a.keyCode&&58>a.keyCode||95<a.keyCode&&106>a.keyCode))return!1}},inputKeyUp:function(a){-1<this.className.indexOf("number")&&(this.value=q(this.value))},inputBlur:function(a){-1<this.className.indexOf("number")&&(this.value=q(this.value));e.saveCell()},cellClick:function(a){d.editCell(this)},setDragHandler:function(a){a.draggable=!0;a.style.cursor="move"}};this.onCellChange=l.event.onCellChange||v;p||(p="grid");this.id=
p;e=this;d=this.Table;m("","width:50px; padding: 0px; border: 1px solid #d5d5d5; border-spacing: 0px; empty-cells: show; border-collapse: collapse; line-height:normal; table-layout: fixed;  text-align: left; vertical-align: middle; font-size: 12px; font-family: Tahoma,'\ub3cb\uc6c0',Dotum,AppleGothic,sans-serif !important;");m("th","height: 20px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-indent: 3px; padding: 0px;");m("td","height: 20px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-indent: 3px; padding: 0px;");
m("th","background-color: #f2f2f2; height: 20px; color: #bfbfbf; text-align: center; cursor: default;");m("span.resize","float: right; width: 8px; height: 18px; cursor: col-resize; margin: -2px -2px -2px 0;");m("thead .blank","border-right: 1px solid #ffffff; border-bottom: 1px solid #ffffff;");m("tbody th","border-right: 1px solid #535353; width: 16px;");m("tbody tr","border-right: 1px solid #535353;");m("tr.title td","border-top: 1px solid #535353;");m(".title","background-color: #d1d1d1;");m("td",
"border-right: 1px solid #b4b4b4; border-bottom: 1px solid #b4b4b4; color: #252525; cursor: cell;");m("td.end","border-right: 1px solid #535353;");m("tr.end td","border-bottom: 1px solid #535353;");m("input","border-color: transparent; margin: 0px; background-color: transparent; font-size: 11px; font-family: Tahoma, \ub3cb\uc6c0, Dotum, AppleGothic, sans-serif;");m(".selectedCell","box-shadow: 0 0 4px 1px #80a2d9 inset;");d.createTable();this.setData(l.data);l.data||(this.setRowSize(l.rowSize),this.setColumnSize(l.columnSize));
this.fillTable(!0);u=!0};
