(function(){try{var E=function(){c.G_TABLE_TO_CHART_CURSOR=GetParentbyTagName(getFirstRange().range.startContainer,"table",!0);var b=v(),h=b.length,g=C(b);4>=b.length||b.length==g||b.length==b.length/g?alert(c.lang.message.not_enough_data):(c.G_TABLE_TO_CHART_ROW=h/g,c.G_TABLE_TO_CHART_COLUMN=g,c.G_TABLE_TO_CHART_DATA=b,c.G_TABLE_TO_CHART_CURSOR=GetParentbyTagName(getFirstRange().range.startContainer,"table",!0),RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,"chart/editor_popup.html"))},
v=function(){var b=GetTableSelectionCells(KEDITORTOP.G_SELECTED_ELEMENT,!0);if(1>b.length){var h,b=[];h=navigator.userAgent.toLowerCase();if(-1<h.indexOf("chrome")||-1<h.indexOf("firefox")||-1<h.indexOf("safari")){h=ActiveCurrTable;for(var c=h.rows.length,f=0,a=0;a<c;a++)for(var n=h.firstElementChild.children[a].childElementCount,e=0;e<n;e++)b[f]=h.firstElementChild.children[a].childNodes[e],f++}else for(h=ActiveCurrTable.cells,c=0;c<h.length;c++)b[c]=h[c]}return b},F=function(){for(var b=v(),c=/colspan="[2-9][0-9]*"/,
g=/rowspan="[2-9][0-9]*"/,f=0;f<b.length;f++)if(null!=b[f].outerHTML.match(c)||null!=b[f].outerHTML.match(g))return!0;return!1},C=function(b){for(var c=w=A=0,g=0,f,a,n=0,e=0;e<b.length;e++)0==e?(f=b[e].cellIndex,a=b[e].cellIndex+b[e].colSpan-1,1<b[e].rowSpan&&A++,1<b[e].colSpan&&(w++,n=b[e].colSpan-1)):(a<b[e].cellIndex+b[e].colSpan-1+n&&(a=b[e].cellIndex+b[e].colSpan-1+n),f==b[e].cellIndex&&(n=0),1<b[e].rowSpan&&(A++,G.push({cellIndex:b[e].cellIndex,rangeIdx:e}),c++),1<b[e].colSpan&&(w++,H.push({cellIndex:b[e].cellIndex,
rangeIdx:e}),g++));for(b=0;b<c;b++);for(b=0;b<g;b++);return a-f+1},c={pluginName:"chart"};G_KPlugin.chart=c;c.isSupportBrowser=!0;c.onShowTopMenu=function(b,h){if(!c.isSupportBrowser)return null;switch(b){case "m_insert":return h.push("p_chart"),h;case "m_table":return null;default:return null}};c.onResize=function(b){if("end"==b.cmd&&(void 0!=b.isResize||void 0!=b.target)&&c.isSupportBrowser){var h=b.isResize;b=b.target;h&&b&&"img"==b.nodeName.toLowerCase()&&b.getAttribute("raon_chart")?(h={element:b},
c.G_TABLE_TO_CHART_CURSOR=null,c.insertChart(h)):!h&&b.getAttribute("raon_chart")&&(h={element:b},c.G_TABLE_TO_CHART_CURSOR=null,c.insertChart(h))}};c.insertChart=function(b,h){var g=function(a){var b=a.split(",");4==b.length?(b[3]="0.7)",a=b.join()):(a=a.replace(/b/,"ba"),a=a.replace(/\)/,",0.7)"));return a},f=b.element,a=b.chart,n=b.preview;if(null!=f&&!a&&!n){var e=KEDITORTOP.RAONKEDITOR.util.makeDecryptReponseMessage(f.getAttribute("raon_chart")),a=JSON.parse(e.replace(/&quot;/g,'"')).data;a.width=
f.clientWidth;a.height=f.clientHeight}var e="line",m={},k={responsive:!1},y=!0,D=!1,t,p,q,z,v,x,w;yStack=xStack=!1;m.labels=[];for(var d=1;d<a.data.length;d++)m.labels.push(a.data[d][0]);d=a.type.split("-");e=d[0];d=d[1];switch(e){case "line":e="line";t=!1;p=a.color.column;if(2==d||4==d)x=0;if(3==d||4==d)w=0;break;case "bar":e=3==d||4==d?"horizontalBar":"bar";q=a.color.column;if(2==d||4==d)yStack=xStack=!0;break;case "area":e="line";q=a.color.column;t=!0;if(2==d||4==d)x=0;if(3==d||4==d)yStack=!0;
break;case "circle":y=!1;1==d?e="pie":2==d&&(e="doughnut");q=a.color.column;break;case "radar":5==d?(e="polarArea",y=!1,q=a.color.column,k.layout={padding:{top:5,bottom:5}}):(e="radar",1==d?z=q=p=a.color.column:2==d?(q=p=a.color.column,x=0):3==d?(p=a.color.column,t=!1,q=a.color.column,x=0):4==d&&(p=["rgba(0,0,0,0)"],t=!1,v=z=q=a.color.column));break;case "scatter":e=1==d?"scatter":"bubble",D=!0,q=a.color.column}m.datasets=[];var u=0;if(y)for(d=1;d<a.data[0].length;d++){var l={};if(D)if(l.label=a.data[0][d],
q&&(l.backgroundColor=q[u]),l.data=[],"scatter"==e)for(var r=1;r<a.data.length;r++)l.data.push({x:a.data[r][0],y:a.data[r][d]});else{if("bubble"==e){for(r=1;r<a.data.length;r++)l.data.push({x:a.data[r][0],y:a.data[r][d],r:a.data[r][d+1]});d++}}else{l.label=a.data[0][d];l.data=[];for(r=1;r<a.data.length;r++)l.data.push(a.data[r][d]);l.fill=t;l.pointRadius=x;l.lineTension=w;p&&(l.borderColor=p[u]?p[u]:p);q&&(l.backgroundColor=q[u]?g(q[u]):q);z&&(l.pointBorderColor=z[u]);v&&(l.pointBackgroundColor=g(v[u]))}m.datasets.push(l);
u++}else{m.labels=a.data[0];l={data:a.data[1],fill:t,pointRadius:x};p&&(l.borderColor=p);if(q)for(l.backgroundColor=[];u<a.data[0].length;)l.backgroundColor.push(g(q[u++]));m.datasets.push(l)}g=parseFloat(a.axes.max);t=parseFloat(a.axes.min);p=parseFloat(a.axes.step);if(y&&"radar"!=e)k.scales={xAxes:[{stacked:xStack,gridLines:{display:a.grid},scaleLabel:{display:0<a.axes.x.text.length,labelString:a.axes.x.text,fontFamily:a.axes.x.fontFamily,fontSize:a.axes.x.fontSize,fontStyle:a.axes.x.fontStyle,
fontColor:a.axes.x.fontColor},ticks:{}}],yAxes:[{stacked:yStack,gridLines:{display:a.grid},scaleLabel:{display:0<a.axes.y.text.length,labelString:a.axes.y.text,fontFamily:a.axes.y.fontFamily,fontSize:a.axes.y.fontSize,fontStyle:a.axes.y.fontStyle,fontColor:a.axes.y.fontColor},ticks:{}}]},"horizontalBar"==e?(""!=a.axes.max&&(k.scales.xAxes[0].ticks.max=g),""!=a.axes.min&&(k.scales.xAxes[0].ticks.min=t),""!=a.axes.step&&(k.scales.xAxes[0].ticks.stepSize=p)):"scatter"==e||"bubble"==e?(""!=a.axes.max&&
(k.scales.xAxes[0].ticks.max=g,k.scales.yAxes[0].ticks.max=g),""!=a.axes.min&&(k.scales.xAxes[0].ticks.min=t,k.scales.yAxes[0].ticks.min=t),""!=a.axes.step&&(k.scales.xAxes[0].ticks.stepSize=p,k.scales.yAxes[0].ticks.stepSize=p)):(""!=a.axes.max&&(k.scales.yAxes[0].ticks.max=g),""!=a.axes.min&&(k.scales.yAxes[0].ticks.min=t),""!=a.axes.step&&(k.scales.yAxes[0].ticks.stepSize=p));else if("radar"==e||"polarArea"==e)k.scale={ticks:{}},""!=a.axes.max&&(k.scale.ticks.max=g),""!=a.axes.min&&(k.scale.ticks.min=
t),""!=a.axes.step&&(k.scale.ticks.stepSize=p);k.title={display:0<a.title.text.length,position:a.title.position,text:a.title.text,fontFamily:a.title.fontFamily,fontSize:a.title.fontSize,fontStyle:a.title.fontStyle,fontColor:a.title.fontColor};k.legend={display:a.legend.display,position:a.legend.position,labels:{fontFamily:a.legend.fontFamily,fontSize:parseFloat(a.legend.fontSize),fontStyle:a.legend.fontStyle,fontColor:a.legend.fontColor}};canvas=document.createElement("canvas");a.width=0<parseIntOr0(a.width)?
a.width:400;a.height=0<parseIntOr0(a.height)?a.height:200;canvas.width=a.width;canvas.height=a.height;k.animation={duration:0,onComplete:function(b,e){var d=document.createElement("canvas");d.width=a.width;d.height=a.height;d.getContext("2d").fillStyle=a.color.background;d.getContext("2d").fillRect(this.chartArea.left,this.chartArea.top,this.chartArea.right-this.chartArea.left,this.chartArea.bottom-this.chartArea.top);d.getContext("2d").drawImage(this.canvas,0,0,d.width,d.height);var g=d.toDataURL();
if(n)f.width=582<d.width?582:d.width,f.height=300<d.height?300:d.height,f.src=g;else{if(f)hideDialog(h);else{f=_iframeDoc.createElement("img");d={pluginName:c.pluginName,action:"insert_image",image:f,closeDialog:!!h};if(c.G_TABLE_TO_CHART_CURSOR){var k=c.G_TABLE_TO_CHART_CURSOR;if(!k.nextSibling){var l=_iframeDoc.createElement("p");k.parentNode.appendChild(l)}var l=getFirstRange(),m=l.range;m.setStart(k.nextSibling,0);m.setEnd(k.nextSibling,0);l.sel.removeAllRanges();l.sel.addRange(m);_k_editor._LastRange=
m}event_kplugin_action(d,h)}"upload"==KEDITORTOP.G_CURRKEDITOR._config.uploadMethod?"1"==KEDITORTOP.G_CURRKEDITOR._config.useKManager?(d=[["kcmd","KC05"]],d.push(["kp1",g.replace(/[+]/g,"%2B")]),g=setManagerParam("{}",d),g=KEDITORTOP.RAONKSolution.Agent.makeEncryptManagerParam(g),sendMessageToAgent(g,function(a){a=KEDITORTOP.RAONKSolution.Agent.parseRtn(a);var b=a.code;a=a.valueArr;if(1E3==b||7777==b)a=a[0].split(KEDITORTOP.RAONKSolution.Agent.formfeed),a=convertImageAgentSrc("file:///"+a[1],!0),
f.src=a},null,!0)):f.src=g:f.src=g;g=KEDITORTOP.RAONKEDITOR.util.makeEncryptParam(JSON.stringify({data:a}));f.setAttribute("raon_chart",g);f.style.width=a.width+"px";f.style.height=a.height+"px"}}};new Chart(canvas,{type:e,data:m,options:k})};c.onClickToolIcon=function(b){if(c.isSupportBrowser)switch(c.G_TABLE_TO_CHART_DATA=null,c.G_TABLE_TO_CHART_COLUMN=null,c.G_TABLE_TO_CHART_ROW=null,c.G_TABLE_TO_CHART_CURSOR=null,b){case "chart":KEDITORTOP.RAONKEDITOR.G_SELECTED_ELEMENT=null;RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,
"chart/editor_popup.html");break;case "tabletochart":c.tableToChart();case "chartproperty":RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,"chart/editor_popup.html")}};c.onDisableToolIcon=function(b){switch(b){case "":case "default":return["p_chart_tabletochart"];case "selectedMultiCell":return["p_chart"];case "focusInCell":return!1;default:return["p_chart","p_chart_tabletochart"]}};c.onCreateContextMenu=function(b){c.isSupportBrowser&&(b.items="paste cut copy  select_all  p_chart_chartproperty".split(" "),
b.disabledItems=["paste"],b.height="300px",b.width="200px")};c.onDbClickImage=function(){c.isSupportBrowser&&(c.G_TABLE_TO_CHART_DATA=null,c.G_TABLE_TO_CHART_COLUMN=null,c.G_TABLE_TO_CHART_ROW=null,c.G_TABLE_TO_CHART_CURSOR=null,RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,"chart/editor_popup.html"))};c.onInit=function(){if(!KEDITORTOP.RAONKEDITOR.browser.canvasSupported||KEDITORTOP.RAONKEDITOR.browser.ie&&9>KEDITORTOP.RAONKEDITOR.browser.ieVersion){c.isSupportBrowser=!1;var b=
_k_editor;b.remove_item.push("p_chart");b.remove_item.push("p_chart_tabletochart")}else B("../plugin/chart/js"+(KEDITORTOP.RAONKEDITOR.isRelease?"":"_dev")+"/chart.js?ver="+KEDITORTOP.RAONKEDITOR.ReleaseVer),B("../plugin/chart/js"+(KEDITORTOP.RAONKEDITOR.isRelease?"":"_dev")+"/grid.js?ver="+KEDITORTOP.RAONKEDITOR.ReleaseVer),b="../plugin/chart/js"+(KEDITORTOP.RAONKEDITOR.isRelease?"":"_dev")+"/config.js",b="1"==KEDITORTOP.G_CURRKEDITOR._config.useConfigTimeStamp?b+("?t="+KEDITORTOP.RAONKEDITOR.util.getTimeStamp()):
b+("?ver="+KEDITORTOP.RAONKEDITOR.ReleaseVer),B(b)};var B=function(b){var c=document.getElementsByTagName("head")[0],g=document.createElement("script");g.type="text/javascript";g.src=b;c.appendChild(g)};c.onInit();c.onLoaded=function(){c.isSupportBrowser&&(KEDITOR_CONTEXT._item_sub_list.table_tool.push("p_chart_tabletochart"),KEDITOR_TOPMENU._item_sub_list.table_tool.push("p_chart_tabletochart"))};var A=0,w=0,G=[],H=[];c.tableToChart=function(){restoreSelection();var b=v(),h,g,f=0;if(c.allowMergedTableToChart)if(g=
C(b),4>=b.length||b.length==g||b.length==b.length/g)alert(c.lang.message.not_enough_data);else{h=b.length;f=0;h=[];for(var a=0,n=0,e=0;b[f];){n=0;rowPos=parseInt(f/g);if(1<b[f].colSpan){for(n=2;n<=b[f].colSpan;n++)b.splice(f+n-1,0,"0");for(var n=0,m=2;m<=b[f].rowSpan;){for(var k=2;k<=b[f].colSpan;k++)rowPos==a?h.push(f+((m-1)*g+k-1)):h.push(f+e+((m-1)*g+k-1)),n++;rowPos==a?h.push(f+(m-1)*g):h.push(f+e+(m-1)*g);n++;m++}e+=n;a=rowPos}else if(1<b[f].rowSpan){for(m=2;m<=b[f].rowSpan;m++)h.push(f+g*(m-
1)),n++;e+=n}f++}h=h.sort(function(a,b){return a-b});for(f=0;f<h.length;f++)b.splice(h[f],0,"0");h=b.length;h/=g;c.G_TABLE_TO_CHART_ROW=h;c.G_TABLE_TO_CHART_DATA=b;c.G_TABLE_TO_CHART_COLUMN=g;h!==parseInt(h)?alert(c.lang.message.incorrect_selection):(c.G_TABLE_TO_CHART_CURSOR=GetParentbyTagName(getFirstRange().range.startContainer,"table",!0),RAONK_EDITOR.prototype.dialog.show(_k_editor._config.webPath.plugin,"chart/editor_popup.html"))}else F()?alert(c.lang.message.merge):E()}}catch(I){}})();
