/*
 Copyright (c) 2014, Raonwiz Technology Inc. All rights reserved.
*/
window.KMINIPHOTO||(window.KMINIPHOTO=function(){var a=window.KMINIPHOTO_ROOTPATH||"";if(!a)for(var b=document.getElementsByTagName("script"),c=b.length,d=null,e=0;e<c;e++)if(d=b[e],d=d.src.match(/(^|.*[\\\/])kminiphoto\.js/i)){a=d[1];break}-1==a.indexOf(":/")&&(a=0===a.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+a:location.href.match(/^[^\?]*\/(?:)/)[0]+a);a=a.substring(0,a.length-1);a=a.substring(0,a.lastIndexOf("/"))+"/";if(!a)throw"K Mini Photo installation path could not be automatically detected.";
return{isRelease:!0,logMode:!1,logLevel:"ALL",logGroupingName:"",isPopUpCssLoaded:!1,version:"K Mini Photo",ReleaseVer:"2018.1196496.1800.01",ServerReleaseVer:"",rootPath:a,RAONKMULTIPLE:{},RAONKHOLDER:{},RAONKMULTIPLEID:[],CUploadID:"",IsUploadLoadedHashTable:null,InitUploadDataHashTable:null,_0_:null,IsCreatedDropZone:!1}}(),KMINIPHOTO.brower||(KMINIPHOTO.browser=function(){var a=navigator.userAgent.toLowerCase(),b=window.opera,b={ie:-1<a.search("trident")||-1<a.search("msie")||/(edge)\/((\d+)?[\w\.]+)/i.test(a)?
!0:!1,edge:/(edge)\/((\d+)?[\w\.]+)/i.test(a)?!0:!1,opera:!!b&&b.version,webkit:-1<a.indexOf(" applewebkit/"),mac:-1<a.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<a.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(a),isCustomDomain:function(a){if(!this.ie)return!1;var b=a.domain;a=KMINIPHOTO.util.getDocWindow(a).location.hostname;return b!=a&&b!="["+a+"]"},isHttps:"https:"==location.protocol,HTML5Supported:!0,HTML5PlusSupported:!1,ajaxOnProgressSupported:!1,G_AP12:9,G_AP24:"i"};
b.gecko="Gecko"==navigator.product&&!b.webkit&&!b.opera;b.ie&&(b.gecko=!1);b.webkit&&(-1<a.indexOf("chrome")?(b.chrome=!0,-1<a.indexOf("opr")&&(b.opera=!0,b.chrome=!1)):b.safari=!0);var c;b.ieVersion=0;b.ie&&(b.quirks||!document.documentMode?-1<a.indexOf("msie")?c=parseFloat(a.match(/msie (\d+)/)[1]):-1<a.indexOf("trident")?c=parseFloat(a.match(/rv:([\d\.]+)/)[1]):/(edge)\/((\d+)?[\w\.]+)/i.test(a)?(c=12,b.chrome=!1):c=7:c=document.documentMode,b.ieVersion=c,b.ie12=12==c,b.ie11=11==c,b.ie10=10==c,
b.ie9=9==c,b.ie8=8==c,b.ie7=7==c,b.ie6=7>c||b.quirks);b.gecko&&(c=a.match(/rv:([\d\.]+)/))&&(c=c[1].split("."),c=1E4*c[0]+100*(c[1]||0)+1*(c[2]||0));b.webkit&&(c=parseFloat(a.match(/ applewebkit\/(\d+)/)[1]));b.HTML5Supported="File"in window&&"FileReader"in window&&"Blob"in window;b.HTML5PlusSupported="File"in window&&"FileReader"in window&&"Blob"in window&&("WebSocket"in window||"MozWebSocket"in window);b.WorkerSupported="Worker"in window;b.imageProcessWorkerSupported="Worker"in window;a=null;try{a=
new XMLHttpRequest,b.ajaxOnProgressSupported=!!(a&&"upload"in a&&"onprogress"in a.upload)}catch(d){b.ajaxOnProgressSupported=!1}a=null;return b}()),KMINIPHOTO.UserAgent||(KMINIPHOTO.UserAgent=function(){var a=window&&window.navigator&&window.navigator.userAgent?window.navigator.userAgent:"",b={extend:function(a,b){for(var c in b)-1!=="browser cpu device engine os".indexOf(c)&&0===b[c].length%2&&(a[c]=b[c].concat(a[c]));return a},has:function(a,b){return"string"===typeof a?-1!==b.toLowerCase().indexOf(a.toLowerCase()):
!1},lowerize:function(a){return a.toLowerCase()},major:function(a){return"string"===typeof a?a.split(".")[0]:void 0}},c=function(){for(var b,c=0,d,e,f,h,r,k,m=arguments;c<m.length&&!r;){var n=m[c],q=m[c+1];if("undefined"===typeof b)for(f in b={},q)h=q[f],"object"===typeof h?b[h[0]]=void 0:b[h]=void 0;for(d=e=0;d<n.length&&!r;)if(r=n[d++].exec(a))for(f=0;f<q.length;f++)k=r[++e],h=q[f],"object"===typeof h&&0<h.length?2==h.length?b[h[0]]="function"==typeof h[1]?h[1].call(this,k):h[1]:3==h.length?b[h[0]]=
"function"!==typeof h[1]||h[1].exec&&h[1].test?k?k.replace(h[1],h[2]):void 0:k?h[1].call(this,k,h[2]):void 0:4==h.length&&(b[h[0]]=k?h[3].call(this,k.replace(h[1],h[2])):void 0):b[h]=k?k:void 0;c+=2}return b},d=function(a,c){for(var d in c)if("object"===typeof c[d]&&0<c[d].length)for(var e=0;e<c[d].length;e++){if(b.has(c[d][e],a))return"?"===d?void 0:d}else if(b.has(c[d],a))return"?"===d?void 0:d;return a},e={ME:"4.90","NT 3.11":"NT3.51","NT 4.0":"NT4.0",2E3:"NT 5.0",XP:["NT 5.1","NT 5.2"],Vista:"NT 6.0",
7:"NT 6.1",8:"NT 6.2","8.1":"NT 6.3",10:["NT 6.4","NT 10.0"],RT:"ARM"},f=[[/\((ipad|playbook);[\w\s\);-]+(rim|apple)/i],["model","vendor",["type","tablet"]],[/applecoremedia\/[\w\.]+ \((ipad)/],["model",["vendor","Apple"],["type","tablet"]],[/(apple\s{0,1}tv)/i],[["model","Apple TV"],["vendor","Apple"]],[/(archos)\s(gamepad2?)/i,/(hp).+(touchpad)/i,/(kindle)\/([\w\.]+)/i,/\s(nook)[\w\s]+build\/(\w+)/i,/(dell)\s(strea[kpr\s\d]*[\dko])/i],["vendor","model",["type","tablet"]],[/(kf[A-z]+)\sbuild\/[\w\.]+.*silk\//i],
["model",["vendor","Amazon"],["type","tablet"]],[/(sd|kf)[0349hijorstuw]+\sbuild\/[\w\.]+.*silk\//i],[["model",d,{"Fire Phone":["SD","KF"]}],["vendor","Amazon"],["type","mobile"]],[/\((ip[honed|\s\w*]+);.+(apple)/i],["model","vendor",["type","mobile"]],[/\((ip[honed|\s\w*]+);/i],["model",["vendor","Apple"],["type","mobile"]],[/(blackberry)[\s-]?(\w+)/i,/(blackberry|benq|palm(?=\-)|sonyericsson|acer|asus|dell|huawei|meizu|motorola|polytron)[\s_-]?([\w-]+)*/i,/(hp)\s([\w\s]+\w)/i,/(asus)-?(\w+)/i],
["vendor","model",["type","mobile"]],[/\(bb10;\s(\w+)/i],["model",["vendor","BlackBerry"],["type","mobile"]],[/android.+(transfo[prime\s]{4,10}\s\w+|eeepc|slider\s\w+|nexus 7)/i],["model",["vendor","Asus"],["type","tablet"]],[/(sony)\s(tablet\s[ps])\sbuild\//i,/(sony)?(?:sgp.+)\sbuild\//i],[["vendor","Sony"],["model","Xperia Tablet"],["type","tablet"]],[/(?:sony)?(?:(?:(?:c|d)\d{4})|(?:so[-l].+))\sbuild\//i],[["vendor","Sony"],["model","Xperia Phone"],["type","mobile"]],[/\s(ouya)\s/i,/(nintendo)\s([wids3u]+)/i],
["vendor","model",["type","console"]],[/android.+;\s(shield)\sbuild/i],["model",["vendor","Nvidia"],["type","console"]],[/(playstation\s[3portablevi]+)/i],["model",["vendor","Sony"],["type","console"]],[/(sprint\s(\w+))/i],[["vendor",d,{HTC:"APA",Sprint:"Sprint"}],["model",d,{"Evo Shift 4G":"7373KT"}],["type","mobile"]],[/(lenovo)\s?(S(?:5000|6000)+(?:[-][\w+]))/i],["vendor","model",["type","tablet"]],[/(htc)[;_\s-]+([\w\s]+(?=\))|\w+)*/i,/(zte)-(\w+)*/i,/(alcatel|geeksphone|huawei|lenovo|nexian|panasonic|(?=;\s)sony)[_\s-]?([\w-]+)*/i],
["vendor",["model",/_/g," "],["type","mobile"]],[/(nexus\s9)/i],["model",["vendor","HTC"],["type","tablet"]],[/[\s\(;](xbox(?:\sone)?)[\s\);]/i],["model",["vendor","Microsoft"],["type","console"]],[/(kin\.[onetw]{3})/i],[["model",/\./g," "],["vendor","Microsoft"],["type","mobile"]],[/\s(milestone|droid(?:[2-4x]|\s(?:bionic|x2|pro|razr))?(:?\s4g)?)[\w\s]+build\//i,/mot[\s-]?(\w+)*/i,/(XT\d{3,4}) build\//i],["model",["vendor","Motorola"],["type","mobile"]],[/android.+\s(mz60\d|xoom[\s2]{0,2})\sbuild\//i],
["model",["vendor","Motorola"],["type","tablet"]],[/android.+((sch-i[89]0\d|shw-m380s|gt-p\d{4}|gt-n8000|sgh-t8[56]9|nexus 10))/i,/((SM-T\w+))/i],[["vendor","Samsung"],"model",["type","tablet"]],[/((s[cgp]h-\w+|gt-\w+|galaxy\snexus|sm-n900))/i,/(sam[sung]*)[\s-]*(\w+-?[\w-]*)*/i,/sec-((sgh\w+))/i],[["vendor","Samsung"],"model",["type","mobile"]],[/(samsung);smarttv/i],["vendor","model",["type","smarttv"]],[/\(dtv[\);].+(aquos)/i],["model",["vendor","Sharp"],["type","smarttv"]],[/sie-(\w+)*/i],["model",
["vendor","Siemens"],["type","mobile"]],[/(maemo|nokia).*(n900|lumia\s\d+)/i,/(nokia)[\s_-]?([\w-]+)*/i],[["vendor","Nokia"],"model",["type","mobile"]],[/android\s3\.[\s\w;-]{10}(a\d{3})/i],["model",["vendor","Acer"],["type","tablet"]],[/android\s3\.[\s\w;-]{10}(lg?)-([06cv9]{3,4})/i],[["vendor","LG"],"model",["type","tablet"]],[/(lg) netcast\.tv/i],["vendor","model",["type","smarttv"]],[/(nexus\s[45])/i,/lg[e;\s\/-]+(\w+)*/i],["model",["vendor","LG"],["type","mobile"]],[/android.+(ideatab[a-z0-9\-\s]+)/i],
["model",["vendor","Lenovo"],["type","tablet"]],[/linux;.+((jolla));/i],["vendor","model",["type","mobile"]],[/((pebble))app\/[\d\.]+\s/i],["vendor","model",["type","wearable"]],[/android.+;\s(glass)\s\d/i],["model",["vendor","Google"],["type","wearable"]],[/android.+(\w+)\s+build\/hm\1/i,/android.+(hm[\s\-_]*note?[\s_]*(?:\d\w)?)\s+build/i,/android.+(mi[\s\-_]*(?:one|one[\s_]plus)?[\s_]*(?:\d\w)?)\s+build/i],[["model",/_/g," "],["vendor","Xiaomi"],["type","mobile"]],[/(mobile|tablet);.+rv\:.+gecko\//i],
[["type",b.lowerize],"vendor","model"]],e=[[/microsoft\s(windows)\s(vista|xp)/i],["name","version"],[/(windows)\snt\s6\.2;\s(arm)/i,/(windows\sphone(?:\sos)*|windows\smobile|windows)[\s\/]?([ntce\d\.\s]+\w)/i],["name",["version",d,e]],[/(win(?=3|9|n)|win\s9x\s)([nt\d\.]+)/i],[["name","Windows"],["version",d,e]],[/\((bb)(10);/i],[["name","BlackBerry"],"version"],[/(blackberry)\w*\/?([\w\.]+)*/i,/(tizen)[\/\s]([\w\.]+)/i,/(android|webos|palm\sos|qnx|bada|rim\stablet\sos|meego|contiki)[\/\s-]?([\w\.]+)*/i,
/linux;.+(sailfish);/i],["name","version"],[/(symbian\s?os|symbos|s60(?=;))[\/\s-]?([\w\.]+)*/i],[["name","Symbian"],"version"],[/\((series40);/i],["name"],[/mozilla.+\(mobile;.+gecko.+firefox/i],[["name","Firefox OS"],"version"],[/(nintendo|playstation)\s([wids3portablevu]+)/i,/(mint)[\/\s\(]?(\w+)*/i,/(mageia|vectorlinux)[;\s]/i,/(joli|[kxln]?ubuntu|debian|[open]*suse|gentoo|arch|slackware|fedora|mandriva|centos|pclinuxos|redhat|zenwalk|linpus)[\/\s-]?([\w\.-]+)*/i,/(hurd|linux)\s?([\w\.]+)*/i,
/(gnu)\s?([\w\.]+)*/i],["name","version"],[/(cros)\s[\w]+\s([\w\.]+\w)/i],[["name","Chromium OS"],"version"],[/(sunos)\s?([\w\.]+\d)*/i],[["name","Solaris"],"version"],[/\s([frentopc-]{0,4}bsd|dragonfly)\s?([\w\.]+)*/i],["name","version"],[/(ip[honead]+)(?:.*os\s*([\w]+)*\slike\smac|;\sopera)/i],[["name","iOS"],["version",/_/g,"."]],[/(mac\sos\sx)\s?([\w\s\.]+\w)*/i,/(macintosh|mac(?=_powerpc)\s)/i],[["name","Mac OS"],["version",/_/g,"."]],[/((?:open)?solaris)[\/\s-]?([\w\.]+)*/i,/(haiku)\s(\w+)/i,
/(aix)\s((\d)(?=\.|\)|\s)[\w\.]*)*/i,/(plan\s9|minix|beos|os\/2|amigaos|morphos|risc\sos|openvms)/i,/(unix)\s?([\w\.]+)*/i],["name","version"]],d=c.apply(this,[[/(opera\smini)\/([\w\.-]+)/i,/(opera\s[mobiletab]+).+version\/([\w\.-]+)/i,/(opera).+version\/([\w\.]+)/i,/(opera)[\/\s]+([\w\.]+)/i],["name","version"],[/\s(opr)\/([\w\.]+)/i],[["name","Opera"],"version"],[/(kindle)\/([\w\.]+)/i,/(lunascape|maxthon|netfront|jasmine|blazer)[\/\s]?([\w\.]+)*/i,/(avant\s|iemobile|slim|baidu)(?:browser)?[\/\s]?([\w\.]*)/i,
/(?:ms|\()(ie)\s([\w\.]+)/i,/(rekonq)\/([\w\.]+)*/i,/(chromium|flock|rockmelt|midori|epiphany|silk|skyfire|ovibrowser|bolt|iron|vivaldi)\/([\w\.-]+)/i],["name","version"],[/(trident).+rv[:\s]([\w\.]+).+like\sgecko/i],[["name","IE"],"version"],[/(edge)\/((\d+)?[\w\.]+)/i],["name","version"],[/(yabrowser)\/([\w\.]+)/i],[["name","Yandex"],"version"],[/(comodo_dragon)\/([\w\.]+)/i],[["name",/_/g," "],"version"],[/(chrome|omniweb|arora|[tizenoka]{5}\s?browser)\/v?([\w\.]+)/i,/(uc\s?browser|qqbrowser)[\/\s]?([\w\.]+)/i],
["name","version"],[/(dolfin)\/([\w\.]+)/i],[["name","Dolphin"],"version"],[/((?:android.+)crmo|crios)\/([\w\.]+)/i],[["name","Chrome"],"version"],[/XiaoMi\/MiuiBrowser\/([\w\.]+)/i],["version",["name","MIUI Browser"]],[/android.+version\/([\w\.]+)\s+(?:mobile\s?safari|safari)/i],["version",["name","Android Browser"]],[/FBAV\/([\w\.]+);/i],["version",["name","Facebook"]],[/version\/([\w\.]+).+?mobile\/\w+\s(safari)/i],["version",["name","Mobile Safari"]],[/version\/([\w\.]+).+?(mobile\s?safari|safari)/i],
["version","name"],[/webkit.+?(mobile\s?safari|safari)(\/[\w\.]+)/i],["name",["version",d,{"1.0":"/8","1.2":"/1","1.3":"/3","2.0":"/412","2.0.2":"/416","2.0.3":"/417","2.0.4":"/419","?":"/"}]],[/(konqueror)\/([\w\.]+)/i,/(webkit|khtml)\/([\w\.]+)/i],["name","version"],[/(navigator|netscape)\/([\w\.-]+)/i],[["name","Netscape"],"version"],[/(swiftfox)/i,/(icedragon|iceweasel|camino|chimera|fennec|maemo\sbrowser|minimo|conkeror)[\/\s]?([\w\.\+]+)/i,/(firefox|seamonkey|k-meleon|icecat|iceape|firebird|phoenix)\/([\w\.-]+)/i,
/(mozilla)\/([\w\.]+).+rv\:.+gecko\/\d+/i,/(polaris|lynx|dillo|icab|doris|amaya|w3m|netsurf)[\/\s]?([\w\.]+)/i,/(links)\s\(([\w\.]+)/i,/(gobrowser)\/?([\w\.]+)*/i,/(ice\s?browser)\/v?([\w\._]+)/i,/(mosaic)[\/\s]([\w\.]+)/i],["name","version"]]);d.major=b.major(d.version);e=c.apply(this,e);if(c=c.apply(this,f))void 0==c.model&&(c.model=""),void 0==c.type&&(c.type=""),void 0==c.vendor&&(c.vendor="");return{browser:d,os:e,device:c}}()),KMINIPHOTO.ajax||(KMINIPHOTO.ajax=function(){var a=function(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return null},
b=function(){},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},d=function(a){var d=null;c(a)&&(d=a.responseText);a&&a.onreadystatechange&&(a.onreadystatechange=b);return d},e=function(a){var d=null;c(a)&&(d=a.responseXML,d||(d=a.responseText));a&&a.onreadystatechange&&(a.onreadystatechange=b);return d},f=function(b,c,d){var e=!!c,h=a();if(!h)return null;h.open("GET",b,e);e&&(h.onreadystatechange=function(){4==h.readyState&&c(d(h))});
try{h.send(null)}catch(f){return null}if(!e){var g=setTimeout(function(){try{h.abort()}catch(a){}clearTimeout(g)},5E3);"undefined"==typeof KMINIPHOTO.RAONKMULTIPLETIMEOUT&&(KMINIPHOTO.RAONKMULTIPLETIMEOUT=[]);KMINIPHOTO.RAONKMULTIPLETIMEOUT.push(g)}return e?"":d(h)},g=function(b,c,d,e){var h=!!d,f=a();if(!f)return null;f.open("POST",b,h);f.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8");h&&(f.onreadystatechange=function(){4==f.readyState&&d(e(f,c))});try{f.send(c)}catch(g){return null}if(!h){var m=
setTimeout(function(){try{f.abort()}catch(a){}clearTimeout(m)},5E3);"undefined"==typeof KMINIPHOTO.RAONKMULTIPLETIMEOUT&&(KMINIPHOTO.RAONKMULTIPLETIMEOUT=[]);KMINIPHOTO.RAONKMULTIPLETIMEOUT.push(m)}return h?"":e(f)};return{load:function(a,b){return f(a,b,d)},loadXml:function(a,b){return f(a,b,e)},postData:function(a,b,c){return g(a,b,c,d)},postFileData:function(b,c){var d;a:if(d=a()){try{d.open("POST",b,!1);var e=KUPLOADTOP.KMINIPHOTO.util.makeGuidTagName("----raonk_");d.setRequestHeader("Content-Type",
"multipart/form-data; boundary="+e);for(var e="--"+e,f="",g=c.split("&"),k=g.length,m=null,n="",q="",p=0;p<k;p++)m=g[p].split("="),"imagedata"==m[0]?n=m[1]:(f+=e+"\r\n",f+='Content-Disposition: form-data; name="'+m[0]+'"\r\n\r\n',f+=m[1]+"\r\n");for(var g=null,k="",u=window.atob(n),v=u.length,g=new Uint8Array(new ArrayBuffer(v)),p=0;p<v;p++)g[p]=u.charCodeAt(p),k+=String.fromCharCode(g[p]);String.fromCharCode.apply([],new Uint8Array(g));new Uint8Array(g);q=k;f+=e+"\r\n";f+='Content-Disposition: form-data; name="Filedata"; filename="'+
(new Date).getTime()+'"\r\n';f+="Content-Type: image/png\r\n";f+="\r\n";f+=q+"\r\n";d.send(f+(e+"--\r\n"))}catch(x){d=null;break a}d=d.responseText}else d=null;return d},urlExists:function(b){var c=a();c?(c.open("HEAD",b,!1),c.send(),b=404!=c.status):b=!1;return b},createXMLHttpRequest:function(){return a()}}}()),KMINIPHOTO.util||(KMINIPHOTO.util={G_IMG_LIST:{},G_AP11:6,G_AP13:7,trim:function(a){return a.trim?a.trim():a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},getDefaultIframeSrc:function(){var a="",
a="document.open();"+(KMINIPHOTO.browser.isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();";return a=KMINIPHOTO.browser.ie?"javascript:void(function(){"+encodeURIComponent(a)+"}())":""},makeIframe:function(){var a;try{a=document.createElement('<iframe frameborder="0" >')}catch(b){a=document.createElement("iframe")}a.style.margin="0px";a.style.padding="0px";a.frameBorder=0;a.style.overflow="auto";a.style.overflowX="hidden";a.style.backgroundColor="#ffffff";a.title=
"KMINIPhoto";a.src=this.getDefaultIframeSrc();return a},addEvent:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&a.attachEvent("on"+b,c);try{""!=KMINIPHOTO.CUploadID?(KMINIPHOTO.RAONKMULTIPLEEVENT={},KMINIPHOTO.RAONKMULTIPLEEVENT[KMINIPHOTO.CUploadID]=[],KMINIPHOTO.RAONKMULTIPLEEVENT[KMINIPHOTO.CUploadID].push({element:a,event:b,func:c}),KMINIPHOTO.CUploadID=""):KUPLOADTOP.G_CURRKUPLOADER&&KMINIPHOTO.RAONKMULTIPLEEVENT[KUPLOADTOP.G_CURRKUPLOADER.ID]&&KMINIPHOTO.RAONKMULTIPLEEVENT[KUPLOADTOP.G_CURRKUPLOADER.ID].push({element:a,
event:b,func:c})}catch(e){}},removeEvent:function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,d):a.detachEvent&&a.detachEvent("on"+b,c)},stopEvent:function(a){"bubbles"in a?a.bubbles&&a.stopPropagation():a.cancelBubble=!0},cancelEvent:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},ajax:{xml_http_request:function(){var a;window.XMLHttpRequest?a=new XMLHttpRequest:window.ActiveXObject&&(a=new ActiveXObject("Microsoft.XMLHTTP"));return a}},url:{full_url:function(a){var b=
"";if(0==a.indexOf("http://")||0==a.indexOf("https://"))b=a;else if(0==a.indexOf("/"))b=location.protocol+"//"+location.host+a;else var b=location.href,c=b.lastIndexOf("/"),b=b.substring(0,c+1),b=b+a;return b}},xml:{count:function(a,b){return a?a.getElementsByTagName(b).length:0},getNode:function(a,b){return null==a||void 0==a?null:this.getNodeIdx(a,b,0)},getNodeIdx:function(a,b,c){return a.getElementsByTagName(b)[c]},getNodeValue:function(a,b){return null==a||void 0==a?"":this.getNodeValueIdx(a,
b,0)},getNodeValueIdx:function(a,b,c){a=this.getNodeIdx(a,b,c);return this.getValue(a)},getValue:function(a){var b="",c="";if(void 0!=a)try{0<a.childNodes.length&&(c=b=a.firstChild.nodeValue);try{("product_key"==a.nodeName||"license_key"==a.nodeName||"license_key_ex"==a.nodeName||"font"==a.nodeName||"encoding"==a.nodeName||"doctype"==a.nodeName)&&2<=a.childNodes.length&&(b=a.textContent?a.textContent:c)}catch(d){b=c}}catch(e){b="parsing error"}return b}},removeEvents:function(a,b,c){a=b.split(",");
b=c.length;for(var d=0,e=0;e<b;e++)for(var d=a.length,f=0;f<d;f++)c[e].removeAttribute(a[f])},removeElementWithChildNodes:function(a){try{if(null!=a){if("1"==a.nodeType&&"iframe"==a.tagName.toLowerCase()){var b=a.contentDocument||a.contentWindow.document||a.document;if(b){if(a.contentWindow)for(var c in a.contentWindow)if(a.contentWindow.hasOwnProperty(c))try{a.contentWindow[c]=null,delete a.contentWindow[c]}catch(d){}for(var e=b.getElementsByTagName("script");0!=e.length;){e[0].parentNode.removeChild(e[0]);
for(var f in e)delete e[f]}b.body&&(b.body.innerHTML="");b.body.parentNode&&(b.body.parentNode.innerHTML="")}a.setAttribute("src","")}for(;a.hasChildNodes();)try{a.removeChild(a.firstChild),a.firstChild=null,delete a.firstChild}catch(g){}a.parentNode.removeChild(a);try{delete null}catch(l){}}}catch(t){}},bytesToSize:function(a){a=parseInt(a,10);var b="0 byte";isNaN(a)&&(a="",b="N/A");b={size:0,unit:"byte",toString:b};if(0==a)return b;var c=parseInt(Math.floor(Math.log(a)/Math.log(1024)));b.size=Math.round(a/
Math.pow(1024,c)*100,2)/100;b.unit=["bytes","KB","MB","GB","TB"][c];b.toString=b.size+" "+b.unit;return b},stringToXML:function(a){var b;try{window.DOMParser?b=(new DOMParser).parseFromString(a,"text/xml"):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(c){b=null}return b},xmlToString:function(a){return window.ActiveXObject?a.xml:(new XMLSerializer).serializeToString(a)},getUnitSize:function(a){var b=1;switch(a.toLowerCase()){case "kb":b*=1024;break;case "mb":b*=1048576;
break;case "gb":b*=1073741824}return b},getUnit:function(a){a=a.toLowerCase();var b="";-1<a.indexOf("mb")?b=a.substring(a.indexOf("mb")):-1<a.indexOf("gb")?b=a.substring(a.indexOf("gb")):-1<a.indexOf("kb")?b=a.substring(a.indexOf("kb")):-1<a.indexOf("b")&&(b=a.substring(a.indexOf("b")));return b},getDate:function(){var a=0,b=new Date,a=""+b.getFullYear(),c=""+(b.getMonth()+1);1==c.length&&(c="0"+c);b=""+b.getDate();1==b.length&&(b="0"+b);return a=parseInt(a+c+b,10)},getMimeFilter:function(a){var b=
"",b=a.split(",").join(",.");""!=b&&(b="."+b);return b},getMimeFilterEx:function(a){var b="",b=a.split(",").join(";*.");""!=b&&(b="*."+b);return b},getExtStringFromExtEx:function(a){a=a.toLowerCase().split("|");for(var b=a.length,c="",d=1;d<b;d+=2){var e=a[d].replace(/\*./gi,""),e=e.replace(/\*/gi,""),e=e.replace(/;$/gi,""),e=e.replace(/;/gi,",");""!=c&&(c+=",");c+=e}return c},parseIntOr0:function(a){a=parseInt(a,10);return isNaN(a)?0:a},makeGuidTagName:function(a){var b=0,c=(new Date).getTime().toString(32),
d;for(d=0;5>d;d++)c+=Math.floor(65535*Math.random()).toString(32);return(a||"o_")+c+(b++).toString(32)},makeGuid:function(a){var b=function(){return(65536*(1+Math.random())|0).toString(16).substring(1)},b=(b()+b()+b()+b()+b()+b()+b()+b()).toLowerCase();void 0!=a&&(b=a+"-"+b);return b},getUserLang:function(a){a=a.toLowerCase();var b="ko-kr";-1<a.indexOf("auto")?b="Auto":-1<a.indexOf("ko")?b="ko-kr":-1<a.indexOf("en")?b="en-us":-1<a.indexOf("ja")?b="ja-jp":-1<a.indexOf("zh-cn")?b="zh-cn":-1<a.indexOf("zh-tw")&&
(b="zh-tw");return b},getDocWindow:function(a){return a.parentWindow||a.defaultView},getClientRect:function(a){var b={left:0,top:0,right:0,bottom:0};try{b=a.getBoundingClientRect()}catch(c){}return b},getParentbyTagName:function(a,b){for(var c=a;null!=c&&(!c.tagName||c.tagName.toLowerCase()!=b);)c=c.parentNode;return c},getElementsByClass:function(a,b,c){var d=[];null==b&&(b=document);null==c&&(c="*");b=b.getElementsByTagName(c);c=b.length;a=new RegExp("(^|\\s)"+a+"(\\s|$)");for(j=i=0;i<c;i++)a.test(b[i].className)&&
(d[j]=b[i],j++);return d},postFormData:function(a,b,c,d){void 0==d&&(d=[]);var e=a.createElement("form");e.method="post";e.action=b;e.target=c;b=d.length;for(c=0;c<b;c++){var f=a.createElement("input");f.type="hidden";f.name=d[c][0];f.value=d[c][1];e.appendChild(f)}a.body.appendChild(e);e.submit();a.body.removeChild(e)},base64_decode:function(a){var b="",c,d,e,f,g,l=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");l<a.length;)c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),
d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),c=c<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|g,b+=String.fromCharCode(c),64!=f&&(b+=String.fromCharCode(d)),64!=g&&(b+=String.fromCharCode(e));return b=KMINIPHOTO.util.utf8_decode(b)},base64_encode:function(a){var b="",c,d,e,f,
g,l,t=0;for(a=KMINIPHOTO.util.utf8_encode(a);t<a.length;)c=a.charCodeAt(t++),d=a.charCodeAt(t++),e=a.charCodeAt(t++),f=c>>2,c=(c&3)<<4|d>>4,g=(d&15)<<2|e>>6,l=e&63,isNaN(d)?g=l=64:isNaN(e)&&(l=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l);
return b},utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},utf8_decode:function(a){for(var b="",c=0,d=c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&
63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return b},dataURItoBlob:function(a){var b=atob(a.split(",")[1]);a=a.split(",")[0].split(":")[1].split(";")[0];for(var c=new ArrayBuffer(b.length),d=new Uint8Array(c),e=0;e<b.length;e++)d[e]=b.charCodeAt(e);b=new DataView(c);return new Blob([b.buffer],{type:a})},makeDecryptReponseMessage:function(a){var b=function(a,b){var e=a.split("");e.splice(b,1);return e=e.join("")};a=a.replace(/ /g,
"");a=a.replace(/\r/g,"");a=a.replace(/\n/g,"");a=a.replace(/%2B/g,"+");15<=a.length?(a=b(a,9),a=b(a,6),a=b(a,8),a=b(a,7),a=b(a,9),a=b(a,6),a=b(a,8)):(a=a.replace(/#/g,""),a=a.replace(/$/g,""));return a=KMINIPHOTO.util.base64_decode(a)},getCodeAndMessage:function(a){var b={code:"",message:""};a=a.split("|");0==a.length?b.message=a[0]:(b.code=a[0],b.message=a[1]);return b},set_handlerUrl:function(a){var b="",b=0==a.length?KMINIPHOTO.rootPath:"/"==a.substring(0,1)?location.protocol+"//"+location.host:
4<a.length&&"http"==a.substring(0,4).toLowerCase()?"":KMINIPHOTO.rootPath;return b+a},buildFormData:function(a,b,c,d){b=""+("--"+a+'\r\nContent-Disposition: form-data; name="'+b+'"')+"\r\n";b+="\r\n";b+=c;b+="\r\n";d&&(b+="--"+a+"--");return b},hashTable:function(a){this.length=0;this.items={};for(var b in a)a.hasOwnProperty(b)&&(this.items[b]=a[b],this.length++);this.setItem=function(a,b){var e=void 0;this.hasItem(a)?e=this.items[a]:this.length++;this.items[a]=b;return e};this.getItem=function(a){return this.hasItem(a)?
this.items[a]:void 0};this.hasItem=function(a){return this.items.hasOwnProperty(a)};this.removeItem=function(a){if(this.hasItem(a))return previous=this.items[a],this.length--,delete this.items[a],previous};this.keys=function(){var a=[],b;for(b in this.items)this.hasItem(b)&&a.push(b);return a};this.values=function(){var a=[],b;for(b in this.items)this.hasItem(b)&&a.push(this.items[b]);return a};this.each=function(a){for(var b in this.items)this.hasItem(b)&&a(b,this.items[b])};this.clear=function(){this.items=
{};this.length=0}},setSecuritySetting:function(a,b,c,d){1==d?"NONE"==c.developLang&&(c.security.encryptParam="0"):(a.Security.EncryptParam&&""!=a.Security.EncryptParam?c.security.encryptParam="1"==a.Security.EncryptParam?"1":"0":(d=KMINIPHOTO.util.xml.getNodeValue(b,"encrypt_param"),c.security.encryptParam="1"==d?"1":"0"),a.Security.FileExtensionDetector&&""!=a.Security.FileExtensionDetector?c.security.fileExtensionDetector="1"==a.Security.FileExtensionDetector?"1":"0":(d=KMINIPHOTO.util.xml.getNodeValue(b,
"file_extension_detector"),c.security.fileExtensionDetector="1"==d?"1":"0"),a.Security.DeleteOpenFile&&""!=a.Security.DeleteOpenFile&&(c.security.deleteOpenFile=a.Security.DeleteOpenFile),a.Security.FileIntegrity&&""!=a.Security.FileIntegrity?c.security.fileIntegrity="1"==a.Security.FileIntegrity?"1":"0":(d=KMINIPHOTO.util.xml.getNodeValue(b,"file_integrity"),c.security.fileIntegrity="1"==d?"1":"0"),"1"!=c.useKManager?c.security.fileEncrypt="0":a.Security.FileEncrypt&&""!=a.Security.FileEncrypt?c.security.fileEncrypt=
a.Security.FileEncrypt:(a=KMINIPHOTO.util.xml.getNodeValue(b,"file_encrypt"),c.security.fileEncrypt=a))},makeEncryptParam:function(a){a=KMINIPHOTO.util.base64_encode(a);a=KMINIPHOTO.util.insertAt(a,RAONKSolution.Agent.G_AP10,KMINIPHOTO.util.G_AP27);a=KMINIPHOTO.util.insertAt(a,KMINIPHOTO.util.G_AP11,RAONKSolution.Agent.G_AP.G_AP22);a=KMINIPHOTO.util.insertAt(a,KMINIPHOTO.browser.G_AP12,KMINIPHOTO.util.G_AP25);a=KMINIPHOTO.util.insertAt(a,KMINIPHOTO.util.G_AP13,RAONKSolution.Agent.G_AP23);a=KMINIPHOTO.util.insertAt(a,
RAONKSolution.Agent.G_AP10,RAONKSolution.Agent.G_AP.G_AP29);a=KMINIPHOTO.util.insertAt(a,KMINIPHOTO.util.G_AP11,KMINIPHOTO.browser.G_AP24);a=KMINIPHOTO.util.insertAt(a,KMINIPHOTO.browser.G_AP12,RAONKSolution.Agent.G_AP20);return a=a.replace(/[+]/g,"%2B")},getIframeDocument:function(a){return"undefined"!=typeof a.contentDocument?a.contentDocument:"undefined"!=typeof a.contentWindow?a.contentWindow.document:null},isExistUploaderName:function(a,b){if(void 0==a||""==a)return 1;var c=KMINIPHOTO.RAONKMULTIPLE["raonkuploader_frame_"+
a];return void 0==c||null==c?0:""!=b.PhotoHolder&&KMINIPHOTO.RAONKHOLDER[a]==b.PhotoHolder?3:2},getNewNextUploaderName:function(a){var b="",b=a.split("_"),c=b.length;1<c&&(a=a.replace("_"+b[c-1],""));b=a+KMINIPHOTO.util.getNextUploaderNumber();0<KMINIPHOTO.util.isExistUploaderName(b)&&(b=KMINIPHOTO.util.getNewNextUploaderName(b));return b},getNextUploaderNumber:function(){var a=0;return function(){return"_"+ ++a}},createEvent:function(a,b,c){var d=document.createElement("script");d.setAttribute("for",
a);d.event=b;d.appendChild(document.createTextNode(c));document.body.appendChild(d)},initHandlerCheck:function(a,b,c){if((a=KMINIPHOTO.util.parseDataFromServer(a))&&-1<a.toLowerCase().indexOf("hello raonk")){-1<a.indexOf("-")&&(KMINIPHOTO.ServerReleaseVer=a.split("-")[1],b.security.keyValue=KMINIPHOTO.ServerReleaseVer.substring(0,11));try{if(window.localStorage){var d=KMINIPHOTO.util.getDate();window.localStorage.RaonKUpload_gabageCall?d>window.localStorage.RaonKUpload_gabageCall&&(window.localStorage.RaonKUpload_gabageCall=
d,KMINIPHOTO.util.gcRequest_postMessage(b)):(window.localStorage.RaonKUpload_gabageCall=d,KMINIPHOTO.util.gcRequest_postMessage(b))}else KMINIPHOTO.util.gcRequest_postMessage(b)}catch(e){}}else a&&0<a.length?-1<a.indexOf(b.unitDelimiter)?(b=a.split(b.unitDelimiter),KMINIPHOTO.ServerReleaseVer=b[1],KMINIPHOTO._0_=b[2],alert(b[0])):alert(a):(a="",c=0<c.InitXml.length?c.InitXml:"raonkupload.config.xml","ko-kr"==b.lang?(a="Uploader\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n"+
(b.handlerUrl+"\n\n"),a+=c+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(a="Uploader's setting is not correct. Access the following URL is not valid.\n\n"+(b.handlerUrl+"\n\n"),a+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+c+'."'),alert(a))},createUploaderIframe:function(a,b,c,d,e,f){var g=document.createElement("iframe");b.appendChild(g);
g.id=d;g.title=e;""==g.title&&(g.title="KMINIPhoto "+f);g.frameBorder=0;g.style.width="100%";g.style.height=KMINIPHOTO.browser.quirks?a.height:"100%";g.style.borderWidth="0px";b=KMINIPHOTO.util.getDefaultIframeSrc();g.src=b;KMINIPHOTO.util.addEvent(g,"load",function(){try{g.contentWindow.raonk_frame_loaded_event(f,a,c);var b=KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameWin.getDialogDocument(),d=b.getElementsByTagName("head")[0],e=d.getElementsByTagName("link"),w=e.length,h="kminiphoto.popup.min.css";KMINIPHOTO.isRelease||
(h="kminiphoto.popup.css");for(var r=!1,k=0;k<w;k++)-1<e[k].href.indexOf(h)&&(r=!0);if(!r){var m=b.createElement("link");m.type="text/css";m.rel="stylesheet";var n=KMINIPHOTO.ReleaseVer;"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.cacheProtectMode&&(n=(new Date).getTime());m.href=KMINIPHOTO.isRelease?a.webPath.css+"kminiphoto.popup.min.css?ver="+n:a.webPath.cssDev+"kminiphoto.popup.css?ver="+n;d.appendChild(m)}c=a=null}catch(q){}},!1);b=KMINIPHOTO.util.getIframeDocument(g);d='<!DOCTYPE html><html lang="ko">';
d+="<head>";d+="<title>K Mini Photo</title>";e=KMINIPHOTO.ReleaseVer;"1"==a.cacheProtectMode&&(e=(new Date).getTime());KMINIPHOTO.isRelease?(d+='<link rel="stylesheet" type="text/css" href="'+a.webPath.css+"kminiphoto.min.css?ver="+e+'" />',d+='<link rel="stylesheet" type="text/css" href="'+a.webPath.css+"cropper.min.css?ver="+e+'" />',KMINIPHOTO.browser.isCustomDomain(document)&&(d+='<script type="text/javascript"> document.domain = "'+document.domain+'"; \x3c/script>'),d+='<script type="text/javascript" src="'+
a.webPath.js+"kminiphoto.core.js?ver="+e+'">\x3c/script>',d+='<script type="text/javascript" src="'+a.webPath.lang+a.lang+".js?ver="+e+'">\x3c/script>'):(d+='<link rel="stylesheet" type="text/css" href="'+a.webPath.cssDev+"kminiphoto.css?ver="+e+'" />',d+='<link rel="stylesheet" type="text/css" href="'+a.webPath.cssDev+"cropper.css?ver="+e+'" />',KMINIPHOTO.browser.isCustomDomain(document)&&(d+='<script type="text/javascript"> document.domain = "'+document.domain+'"; \x3c/script>'),d+='<script type="text/javascript" src="'+
a.webPath.jsDev+"kminiphoto.src.js?ver="+e+'">\x3c/script>',d+='<script type="text/javascript" src="'+a.webPath.jsDev+"undoredo.js?ver="+e+'">\x3c/script>',d+='<script type="text/javascript" src="'+a.webPath.jsDev+"cropper.js?ver="+e+'">\x3c/script>',d+='<script type="text/javascript" src="'+a.webPath.langDev+a.lang+".js?ver="+e+'">\x3c/script>');d+="</head>";d+='<body oncontextmenu="return false" class="RAON-K-imageEditor raonk_'+a.lang+'">';d+="</body>";d+="</html>";b.open("text/html","replace");
b.write(d);b.close();return g},GetUserRunTimeUpload:function(a,b){a=a.toLowerCase();var c="",d=!1;"agent"==a&&(d=!0,a="html5");c="html5plus"==a?1==KMINIPHOTO.browser.HTML5PlusSupported&&"1"==b?"html5plus":1==KMINIPHOTO.browser.HTML5Supported?"html5":"html4":""==a||"html5"==a?1==KMINIPHOTO.browser.HTML5Supported?"html5":"html4":"html4"==a?"html4":1==KMINIPHOTO.browser.HTML5PlusSupported&&"1"==b?"html5plus":1==KMINIPHOTO.browser.HTML5Supported?"html5":"html4";return{isAgent:d,mode:c}},gcRequest_postMessage:function(a){var b;
b=""+("kc"+RAONKSolution.Agent.formfeed+"c20");b=KMINIPHOTO.util.makeEncryptParam(b);if("html4"==a.userRunTimeMode&&a.isCrossDomain){var c=document.createElement("div"),d=KMINIPHOTO.util.getDefaultIframeSrc();c.innerHTML='<iframe name="initCheckframe" id="initCheckframe" style="display:none;" src="'+d+'"></iframe>';c.style.display="none";document.body.appendChild(c);KMINIPHOTO.util.postFormData(document,a.handlerUrl,"initCheckframe",[["k00",b]]);document.body.removeChild(c)}else KMINIPHOTO.ajax.postData(a.handlerUrl,
"k00="+b,function(){})},_setKMiniPhoto:function(a){a=KMINIPHOTO.util._getKMiniPhoto(a);return void 0==a||null==a?!1:a},_getKMiniPhoto:function(a){var b=null,b=KMINIPHOTO.util._getKMiniPhotoByName(a);return void 0==b||null==b?(alert("MiniPhoto's Name is not correct, Please check uploader's name. \ror\rThe MiniPhoto was not initialized, Please check the location of api call"),null):b},_getKMiniPhotoByName:function(a){var b=null;if(void 0==a||""==a)b=KMINIPHOTOTOP.G_CURRKMINIPHOTO;else{try{if(1==KMINIPHOTO.RAONKMULTIPLEID.length){var c=
KMINIPHOTO.RAONKMULTIPLEID[0];a!=c&&KMINIPHOTO.isLoadedUploadEx(c)&&(a=c)}}catch(d){}b=KMINIPHOTO.RAONKMULTIPLE["kminiphoto_frame_"+a];"object"!=typeof b&&(b=null)}return b},prependZero:function(a,b){for(;a.toString().length<b;)a="0"+a;return a},insertAt:function(a,b,c){return String.prototype.insertAt?a.insertAt(b,c):a.substr(0,b)+c+a.substr(b)},G_AP27:"r",G_AP25:"o",rgbToHex:function(){var a,b,c;1==arguments.length?(a=arguments[0].toLowerCase(),a=a.replace("rgb(",""),a=a.replace("rgba(",""),a=a.replace(")",
""),c=a.split(","),a=parseInt(c[0],10),b=parseInt(c[1],10),c=parseInt(c[2],10)):3<=arguments.length&&(a=arguments[0],b=arguments[1],c=arguments[2]);return"#"+(16777216+(a<<16)+(b<<8)+c).toString(16).slice(1)},jsonToString:function(a){return KUPLOADTOP.G_CURRKUPLOADER.frameWin.JSON.stringify(a)},stringToJson:function(a){return KUPLOADTOP.G_CURRKUPLOADER.frameWin.JSON.parse(a)},saveJsonToLocalStorage:function(a,b){var c=KMINIPHOTO.util.jsonToString(b);window.localStorage[a]=c},loadJsonFromLocalStorage:function(a){a=
window.localStorage[a];var b=null;a&&(b=KMINIPHOTO.util.stringToJson(a));return b},langFontStyle:{"ko-kr":"dotum,\ub3cb\uc6c0,tahoma,sans-serif;","en-us":"Arial,Verdana,sans-serif;","zh-cn":"Arial,Verdana,sans-serif;","zh-tw":"Arial,Verdana,sans-serif;","ja-jp":"MS PGothic,MS UI Gothic,Verdana,sans-serif;"},parseDataFromServer:function(a){if(a){var b=a.toLowerCase().indexOf("<raonk>");-1<b&&(a=a.substring(b+7));b=a.toLowerCase().indexOf("</raonk>");-1<b&&(a=a.substring(0,b))}return a},getParamInfoFromUrl:function(a){var b=
[];if((a=a.split("?")[1])&&""!=a){a=a.split("&");for(var c=a.length,d=0;d<c;d++){var e=a[d].split("="),f="";if(2<e.length){for(var g=1;g<e.length;g++)f+=e[g]+"=";f=f.substring(0,f.length-1)}else f=e[1]?e[1]:"";b.push({name:e[0],value:f})}}return b},changeUrlForGetParam:function(a,b){var c=a,d=KMINIPHOTO.util.getParamInfoFromUrl(c),e=d.length;if(0<e)for(var c=a.split("?")[0],c=c+"?",f=0;f<e;f++){0!=f&&(c+="&");var g=d[f].value,g="1"==b?KMINIPHOTO.util.makeEncryptParam(g):encodeURIComponent(g),c=c+
(d[f].name+"="+g)}return c}}),KMINIPHOTO.ShowPhotoPopup=function(a,b){try{var c=KMINIPHOTO.util._setKMiniPhoto(b);if(c){KMINIPHOTO.G_CURRKMINIPHOTO=c;var d=KMINIPHOTO.G_CURRKMINIPHOTO.frameWin;d&&(KMINIPHOTO.G_CURRKMINIPHOTO._config.saveCompleteEvent=a.completeEvent,d.showPhotoPopup({url:a.url,width:a.width?a.width:"",height:a.height?a.height:""}))}}catch(e){}},KMINIPHOTO.Destroy=function(a,b){try{var c=null;"object"==typeof a?c=a:(DEXT5.ShowDestroyAlert=!1,c=KMINIPHOTO.util._setKMiniPhoto(a));if(c){var d=
c.frameWin;d.getDialogWindow();var e=d.getDialogDocument();try{var f=document.createElement("input");f.setAttribute("type","input");document.body.appendChild(f);f.focus();f.parentNode.removeChild(f)}catch(g){}if(KMINIPHOTO.RAONKMULTIPLEEVENT[c.ID]){editorEventList=KMINIPHOTO.RAONKMULTIPLEEVENT[c.ID];for(var l=0,t=editorEventList.length;l<t;l++)try{editorEventList[l].element&&(KMINIPHOTO.util.removeEvent(editorEventList[l].element,editorEventList[l].event,editorEventList[l].func),editorEventList[l].func=
null,delete editorEventList[l].func)}catch(y){}try{editorEventList&&(editorEventList=null,delete editorEventList,KMINIPHOTO.RAONKMULTIPLEEVENT[c.ID]=null,delete KMINIPHOTO.RAONKMULTIPLEEVENT[c.ID])}catch(w){}}try{d.K_MiniPhoto&&(d.K_MiniPhoto.prototype=null,delete d.K_MiniPhoto.prototype)}catch(h){}if(KMINIPHOTO.RAONKMULTIPLE["kminiphoto_frame_"+c.ID]){try{KMINIPHOTO.RAONKMULTIPLETIMEOUT=null,delete KMINIPHOTO.RAONKMULTIPLETIMEOUT}catch(r){}c._config&&delete c._config;var k=c.ID,m=c.FrameID,n;for(n in c)if(c.hasOwnProperty(n))try{c[n]=
null,delete c[n]}catch(q){}KMINIPHOTO.util.removeElementWithChildNodes(document.getElementById(m));try{KMINIPHOTO.util.removeElementWithChildNodes(e.getElementById("kminiphoto_holder_"+k))}catch(p){}var l=0,u;for(u in KMINIPHOTO.RAONKHOLDER)if(u==k)break;else l++;KMINIPHOTO.RAONKMULTIPLEID.splice(l,1);KMINIPHOTO.RAONKMULTIPLE["kminiphoto_frame_"+k]&&delete KMINIPHOTO.RAONKMULTIPLE["kminiphoto_frame_"+k];"undefined"!=typeof KMINIPHOTO.RAONKHOLDER[k]&&delete KMINIPHOTO.RAONKHOLDER[k];if(!(KMINIPHOTO.RAONKMULTIPLEID&&
0<KMINIPHOTO.RAONKMULTIPLEID.length)){try{delete null}catch(v){}try{delete KMINIPHOTO.RAONKMULTIPLEEVENT}catch(x){}}}delete null;if(b){try{KMINIPHOTOTOP=KMINIPHOTODOC=KMINIPHOTOWIN=null,delete KMINIPHOTOTOP,delete KMINIPHOTODOC,delete KMINIPHOTOWIN}catch(z){}for(n in KMINIPHOTO)if(KMINIPHOTO.hasOwnProperty(n))try{KMINIPHOTO[n]=null,delete KMINIPHOTO[n]}catch(A){}try{KMINIPHOTO=null,delete KMINIPHOTO}catch(B){}}}}catch(C){}});
function kminiphoto_user_config(){return{InitVisible:!0,SkinName:"",Width:"",Height:"",Lang:"",Runtimes:"",FolderNameRule:"",PhotoHolder:"",HandlerUrl:"",DevelopLangage:"",AutoDestroy:"",ForceOverwrite:"",Zindex:"",PopupBackgroundStyle:"",FullscreenType:"",CreationCompleteEvent:null,BackgroundColor:"",BackgroundOpacity:""}}
function KMINIPhoto_Config(){this.webPath={image:KMINIPHOTO.rootPath+"images/",js:KMINIPHOTO.rootPath+"js/",jsDev:KMINIPHOTO.rootPath+"js_dev/",lang:KMINIPHOTO.rootPath+"js/lang/",langDev:KMINIPHOTO.rootPath+"js_dev/lang/",css:KMINIPHOTO.rootPath+"css/",cssDev:KMINIPHOTO.rootPath+"css_dev/"};this.initVisible=!1;this.skinName="bluegray";this.width="800px";this.height="600px";this.lang="ko-kr";this.isCrossDomain=!1;this.developLang="NET";this.handlerUrl=KMINIPHOTO.rootPath+"handler/raonkhandler.ashx";
this.folderNameRule="yyyy/mm";this.fileNameRule="GUID";this.fileNameRuleEx="_";this.imageQuality=1;this.forceOverwrite=this.autoDestroy="0";this.zIndex=1E3;this.popupBackgroundStyle="filter:alpha(opacity={1}); opacity:{0}; -moz-opacity:{0}; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity={1}); -khtml-opacity: {0}; background-color:{2};";this.saveCompleteEvent=null;this.fullscreenType="0";this.creationCompleteEvent=null;this.backgroundColor="black";this.backgroundOpacity="0.5"}
function KMINIPhoto(a){var b=a.Id,c=new kminiphoto_user_config,d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);void 0==b&&(b=KMINIPHOTO.util.makeGuidTagName("kminiphoto_"));KMINIPHOTO.CUploadID=b;a=KMINIPHOTO.util.isExistUploaderName(b,c);if(1==a)alert("miniphoto's name is empty. Please, check uploader's name");else{if(2==a)if("1"==c.IgnoreSameUploadName)b=KMINIPHOTO.util.getNewNextUploaderName(b);else{alert("miniphoto's name is already exist. Please, check uploader's name");return}3!=a&&(KMINIPHOTO.RAONKMULTIPLEID.push(b),
KMINIPHOTO.RAONKMULTIPLE["kminiphoto_frame_"+b]=b,KMINIPHOTO.RAONKHOLDER[b]=c.PhotoHolder);this.frameID="kminiphoto_frame_"+b;this.ID=b;a=new KMINIPhoto_Config;c.DialogWindow&&(a.dialogWindow=c.DialogWindow);0==c.InitVisible&&(a.initVisible=c.InitVisible);""!=c.DevelopLangage&&(a.developLang=c.DevelopLangage);switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.handlerUrl=KMINIPHOTO.rootPath+"handler/raonkhandler.jsp";a.viewerUrl=KMINIPHOTO.rootPath+"handler/raonkviewer.jsp";break;case "PHP":a.handlerUrl=
KMINIPHOTO.rootPath+"handler/raonkhandler.php";a.viewerUrl=KMINIPHOTO.rootPath+"handler/raonkviewer.php";break;case "NONE":a.handlerUrl="";a.viewerUrl="";break;default:a.handlerUrl=KMINIPHOTO.rootPath+"handler/raonkhandler.ashx",a.viewerUrl=KMINIPHOTO.rootPath+"handler/raonkviewer.aspx"}""!=c.HandlerUrl&&(a.handlerUrl=c.HandlerUrl);a.handlerUrl=KMINIPHOTO.util.set_handlerUrl(a.handlerUrl);4<a.handlerUrl.length&&"http"==a.handlerUrl.substring(0,4).toLowerCase()&&a.handlerUrl.match(/:\/\/(.[^\/]+)/)[1]!=
window.location.host&&(a.isCrossDomain=!0);""!=c.FolderNameRule&&(a.folderNameRule=c.FolderNameRule);""!=c.FileNameRule&&(a.fileNameRule=c.FileNameRule);null==c.FileNameRuleEx||""!=c.FileNameRuleEx&&"#"!=c.FileNameRuleEx&&"i"!=c.FileNameRuleEx&&"_"!=c.FileNameRuleEx||(a.fileNameRuleEx=c.FileNameRuleEx);""!=c.SkinName&&(a.skinName=c.SkinName);""!=c.Width&&(a.width=c.Width);""!=c.Height&&(a.height=c.Height,a.originHeight=c.Height);""!=c.Lang&&(a.lang=KMINIPHOTO.util.getUserLang(c.Lang));""!=c.Runtimes&&
(a.userRunTimeMode=c.Runtimes);1E3<parseInt(c.ZIndex,10)&&(a.zIndex=parseInt(c.ZIndex,10));""!=c.BackgroundColor&&(a.backgroundColor=c.BackgroundColor);""!=c.BackgroundOpacity&&(a.backgroundOpacity=parseFloat(c.BackgroundOpacity));a.popupBackgroundStyle=a.popupBackgroundStyle.replace(/\{2\}/gi,a.backgroundColor);a.backgroundOpacity=parseFloat(a.backgroundOpacity);d=100*a.backgroundOpacity;a.popupBackgroundStyle=a.popupBackgroundStyle.replace(/\{0\}/gi,a.backgroundOpacity);a.popupBackgroundStyle=a.popupBackgroundStyle.replace(/\{1\}/gi,
d);null!=c.CreationCompleteEvent&&(a.creationCompleteEvent=c.CreationCompleteEvent);""!=c.AutoDestroy&&(a.autoDestroy=c.AutoDestroy);d="";d=a.initVisible?'<div id="kminiphoto_holder_'+b+'" style="width:'+a.width+"; height:"+a.height+"; z-index:"+a.zIndex+';">':'<div id="kminiphoto_holder_'+b+'" style="width:'+a.width+"; height:"+a.height+"; display:none; z-index:"+a.zIndex+';">';d+='<div id="kminiphoto_holder_header_'+b+'" class="K-mini-imageEditor-wrap" style="margin:0px; padding:0px; width: '+(parseInt(a.width,
10)-2)+'px; border-top:1px solid #1f7eef; border-left:1px solid #1f7eef; border-right:1px solid #1f7eef; border-bottom:0px solid #1f7eef; position:absolute;">';d+='<div class="header" style="width:auto; height:29px; border-bottom:1px solid #252f3b; background-color:#3e4d5f; position:relative; color:#ffffff; margin:0px; padding:0px;"><h3 style="position:absolute; top:7px; left:7px; font-size:12px; margin:0px; padding:0px; font-family:Dotum,\ub3cb\uc6c0,Helvetica; line-height:1.5;"></h3>';d+='<div class="btn-right" style="position:absolute; text-align:left; height:29px; width: 80px; right:0; margin:0px; padding:0px;">';
d+='<a id="btn_fullscreen_'+b+'" title="" href="javascript:;" class="maximization" style="width:40px; height:29px; display:inline-block; background-color:#3e4d5f; margin:0px; padding:0px;">';d+='<span class="blind" style="display: block; overflow: hidden; position: absolute; top: 0; left: 0; width: 0; height: 0; border: 0; background: 0 0; font-size: 0; line-height: 0;"></span>';d+="</a>";d+='<a id="btn_close_'+b+'" title="" href="javascript:;" class="close" style="width:40px; height:29px; display:inline-block; background-color:#3e4d5f; background-position:-40px 0; margin:0px; padding:0px;">';
d+='<span class="blind" style="display: block; overflow: hidden; position: absolute; top: 0; left: 0; width: 0; height: 0; border: 0; background: 0 0; font-size: 0; line-height: 0;"></span>';d+="</a>";d+="</div>";d+="</div>";d+='<div id="kminiphoto_holder_body_'+b+'" style="width:100%; height:'+a.height+'; background-color:white; position:absolute; top:30px; display:none; filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0;"></div>';
d+="</div>";""!=c.PhotoHolder?(c=document.getElementById(c.PhotoHolder))?c.innerHTML=d:document.write(d):document.write(d);c=document.getElementById("kminiphoto_holder_"+b);KMINIPHOTO.util.createUploaderIframe(a,c,this,"kminiphoto_frame_"+b,"",b)}};
