(function(a,b){"object"===typeof exports&&"undefined"!==typeof module?module.exports=b():"function"===typeof define&&define.amd?define(b):a.Cropper=b()})(this,function(){function a(d){return"number"===typeof d&&!isNaN(d)}function b(d){return"undefined"===typeof d}function c(d){return"object"===("undefined"===typeof d?"undefined":ja(d))&&null!==d}function e(d){if(!c(d))return!1;try{var g=d.constructor,m=g.prototype;return g&&m&&ka.call(m,"isPrototypeOf")}catch(a){return!1}}function h(d){return"function"===
U.call(d).slice(8,-1).toLowerCase()}function r(d){return Array.isArray?Array.isArray(d):"array"===U.call(d).slice(8,-1).toLowerCase()}function u(d){"string"===typeof d&&(d=d.trim?d.trim():d.replace(la,"$1"));return d}function p(d,g){if(d&&h(g)){var m=void 0;if(r(d)||a(d.length))for(var b=d.length,m=0;m<b&&!1!==g.call(d,d[m],m,d);m+=1);else c(d)&&Object.keys(d).forEach(function(m){g.call(d,d[m],m,d)})}return d}function q(d){for(var g=arguments.length,m=Array(1<g?g-1:0),a=1;a<g;a++)m[a-1]=arguments[a];
if(c(d)&&0<m.length){if(Object.assign)return Object.assign.apply(Object,[d].concat(m));m.forEach(function(g){c(g)&&Object.keys(g).forEach(function(m){d[m]=g[m]})})}return d}function H(d,g){for(var m=arguments.length,a=Array(2<m?m-2:0),b=2;b<m;b++)a[b-2]=arguments[b];return function(){for(var m=arguments.length,b=Array(m),c=0;c<m;c++)b[c]=arguments[c];return d.apply(g,a.concat(b))}}function I(d,g){var m=d.style;p(g,function(d,g){ma.test(g)&&a(d)&&(d+="px");m[g]=d})}function na(d,g){return d.classList?
d.classList.contains(g):-1<d.className.indexOf(g)}function y(d,g){if(g)if(a(d.length))p(d,function(d){y(d,g)});else if(d.classList)d.classList.add(g);else{var m=u(d.className);m?0>m.indexOf(g)&&(d.className=m+" "+g):d.className=g}}function F(d,g){g&&(a(d.length)?p(d,function(d){F(d,g)}):d.classList?d.classList.remove(g):0<=d.className.indexOf(g)&&(d.className=d.className.replace(g,"")))}function K(d,g,m){g&&(a(d.length)?p(d,function(d){K(d,g,m)}):m?y(d,g):F(d,g))}function S(d){return d.replace(oa,
"$1-$2").toLowerCase()}function O(d,g){return c(d[g])?d[g]:d.dataset?d.dataset[g]:d.getAttribute("data-"+S(g))}function L(d,g,m){c(m)?d[g]=m:d.dataset?d.dataset[g]=m:d.setAttribute("data-"+S(g),m)}function V(d,g){if(c(d[g]))delete d[g];else if(d.dataset)try{delete d.dataset[g]}catch(m){d.dataset[g]=null}else d.removeAttribute("data-"+S(g))}function C(d,g,m){var a=u(g).split(W);1<a.length?p(a,function(g){C(d,g,m)}):d.removeEventListener?d.removeEventListener(g,m,!1):d.detachEvent&&d.detachEvent("on"+
g,m)}function D(d,g,m,a){var b=u(g).split(W),c=m;1<b.length?p(b,function(g){D(d,g,m)}):(a&&(m=function(){for(var a=arguments.length,b=Array(a),N=0;N<a;N++)b[N]=arguments[N];C(d,g,m);return c.apply(d,b)}),d.addEventListener?d.addEventListener(g,m,!1):d.attachEvent&&d.attachEvent("on"+g,m))}function J(d,g,m){if(d.dispatchEvent){var a=void 0;h(Event)&&h(CustomEvent)?a=b(m)?new Event(g,{bubbles:!0,cancelable:!0}):new CustomEvent(g,{detail:m,bubbles:!0,cancelable:!0}):b(m)?(a=document.createEvent("Event"),
a.initEvent(g,!0,!0)):(a=document.createEvent("CustomEvent"),a.initCustomEvent(g,!0,!0,m));return d.dispatchEvent(a)}return d.fireEvent?d.fireEvent("on"+g):!0}function P(d){var g=d||window.event;g.target||(g.target=g.srcElement||document);if(!a(g.pageX)&&a(g.clientX)){var m=d.target.ownerDocument||document;d=m.documentElement;m=m.body;g.pageX=g.clientX+((d&&d.scrollLeft||m&&m.scrollLeft||0)-(d&&d.clientLeft||m&&m.clientLeft||0));g.pageY=g.clientY+((d&&d.scrollTop||m&&m.scrollTop||0)-(d&&d.clientTop||
m&&m.clientTop||0))}return g}function X(d){var g=document.documentElement;d=d.getBoundingClientRect();return{left:d.left+((window.scrollX||g&&g.scrollLeft||0)-(g&&g.clientLeft||0)),top:d.top+((window.scrollY||g&&g.scrollTop||0)-(g&&g.clientTop||0))}}function G(d,g){return d.getElementsByClassName?d.getElementsByClassName(g):d.querySelectorAll("."+g)}function T(d){d.parentNode&&d.parentNode.removeChild(d)}function Y(d){return(d=d.match(pa))&&(d[1]!==location.protocol||d[2]!==location.hostname||d[3]!==
location.port)}function Z(d){var g="timestamp="+(new Date).getTime();return d+(-1===d.indexOf("?")?"?":"&")+g}function qa(d,g){if(d.naturalWidth&&!aa)g(d.naturalWidth,d.naturalHeight);else{var m=document.createElement("img");m.onload=function(){g(this.width,this.height)};m.src=d.src}}function M(d){var g=[],m=d.translateX,b=d.translateY,c=d.rotate,k=d.scaleX;d=d.scaleY;a(m)&&0!==m&&g.push("translateX("+m+"px)");a(b)&&0!==b&&g.push("translateY("+b+"px)");a(c)&&0!==c&&g.push("rotate("+c+"deg)");a(k)&&
1!==k&&g.push("scaleX("+k+")");a(d)&&1!==d&&g.push("scaleY("+d+")");g=g.length?g.join(" "):"none";return{WebkitTransform:g,msTransform:g,transform:g}}function Q(d,g){var m=Math.abs(d.degree)%180,a=(90<m?180-m:m)*Math.PI/180,m=Math.sin(a),a=Math.cos(a),b=d.width,c=d.height,f=d.aspectRatio,l=void 0,v=void 0;g?(l=b/(a+m/f),v=l/f):(l=b*a+c*m,v=b*m+c*a);return{width:l,height:v}}function ba(d,g,m){var b=document.createElement("canvas"),c=b.getContext("2d"),k=0,f=0,l=g.naturalWidth,v=g.naturalHeight,n=g.rotate,
e=g.scaleX;g=g.scaleY;var h=a(e)&&a(g)&&(1!==e||1!==g),p=a(n)&&0!==n,q=p||h,x=l*Math.abs(e||1),A=v*Math.abs(g||1),z=void 0,r=void 0,w=void 0;h&&(z=x/2,r=A/2);p&&(w=Q({width:x,height:A,degree:n}),x=w.width,A=w.height,z=x/2,r=A/2);b.width=x;b.height=A;m.fillColor&&(c.fillStyle=m.fillColor,c.fillRect(0,0,x,A));q&&(k=-l/2,f=-v/2,c.save(),c.translate(z,r));p&&c.rotate(n*Math.PI/180);h&&c.scale(e,g);c.imageSmoothingEnabled=!!m.imageSmoothingEnabled;m.imageSmoothingQuality&&(c.imageSmoothingQuality=m.imageSmoothingQuality);
c.drawImage(d,Math.floor(k),Math.floor(f),Math.floor(l),Math.floor(v));q&&c.restore();return b}function ra(d){d=d.replace(sa,"");d=atob(d);for(var g=d.length,m=new ArrayBuffer(g),a=new Uint8Array(m),b=void 0,b=0;b<g;b+=1)a[b]=d.charCodeAt(b);return m}function R(d,g){var m=d.pageX,a=d.pageY,b={endX:m,endY:a};return g?b:q({startX:m,startY:a},b)}function ta(d){var g=q({},d),m=[];p(d,function(d,a){delete g[a];p(g,function(g){var a=Math.abs(d.startX-g.startX),b=Math.abs(d.startY-g.startY),c=Math.abs(d.endX-
g.endX);g=Math.abs(d.endY-g.endY);a=Math.sqrt(a*a+b*b);c=(Math.sqrt(c*c+g*g)-a)/a;m.push(c)})});m.sort(function(d,g){return Math.abs(d)<Math.abs(g)});return m[0]}function ua(d){if(Array.isArray(d)){for(var g=0,m=Array(d.length);g<d.length;g++)m[g]=d[g];return m}return Array.from(d)}function va(d){var g=0,m=0,a=0;p(d,function(d){var b=d.startY;g+=d.startX;m+=b;a+=1});g/=a;m/=a;return{pageX:g,pageY:m}}var ca={viewMode:0,dragMode:"crop",aspectRatio:NaN,data:null,preview:"",responsive:!0,restore:!0,checkCrossOrigin:!0,
checkOrientation:!0,modal:!0,guides:!0,center:!0,highlight:!0,background:!0,autoCrop:!0,autoCropArea:.8,movable:!0,rotatable:!0,scalable:!0,zoomable:!1,zoomOnTouch:!0,zoomOnWheel:!0,wheelZoomRatio:.1,cropBoxMovable:!0,cropBoxResizable:!0,toggleDragModeOnDblclick:!0,minCanvasWidth:0,minCanvasHeight:0,minCropBoxWidth:0,minCropBoxHeight:0,minContainerWidth:1,minContainerHeight:1,ready:null,cropstart:null,cropmove:null,cropend:null,crop:null,zoom:null},ja="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?
function(d){return typeof d}:function(d){return d&&"function"===typeof Symbol&&d.constructor===Symbol&&d!==Symbol.prototype?"symbol":typeof d},sa=/^data:.*,/,oa=/([a-z\d])([A-Z])/g,pa=/^(https?:)\/\/([^:/?#]+):?(\d*)/i,W=/\s+/,ma=/^(width|height|left|top|marginLeft|marginTop)$/,la=/^\s+(.*)\s+$/,E=/(Macintosh|iPhone|iPod|iPad).*AppleWebKit/i,da="undefined"!==typeof window?window.navigator:null,aa=da&&E.test(da.userAgent),E=Object.prototype,U=E.toString,ka=E.hasOwnProperty,ea=String.fromCharCode,fa=
(E="undefined"!==typeof window?window.PointerEvent:null)?"pointerdown":"touchstart mousedown",ga=E?"pointermove":"touchmove mousemove",ha=E?" pointerup pointercancel":"touchend touchcancel mouseup",wa=/^(e|w|s|n|se|sw|ne|nw|all|crop|move|zoom)$/,xa=function(){function d(d,m){for(var a=0;a<m.length;a++){var b=m[a];b.enumerable=b.enumerable||!1;b.configurable=!0;"value"in b&&(b.writable=!0);Object.defineProperty(d,b.key,b)}}return function(g,a,b){a&&d(g.prototype,a);b&&d(g,b);return g}}(),ya=/^data:/,
za=/^data:image\/jpeg;base64,/,ia=void 0,E=function(){function d(g,a){if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");this.element=g;this.options=q({},ca,e(a)&&a);this.isImg=this.wheeling=this.limited=this.replaced=this.disabled=this.cropped=this.rotated=this.complete=this.ready=this.loaded=!1;this.originalUrl="";this.previews=this.cropBoxData=this.canvasData=null;this.pointers={};this.init()}xa(d,[{key:"init",value:function(){var d=this.element,a=d.tagName.toLowerCase(),
b=void 0;if(!O(d,"cropper")){L(d,"cropper",this);if("img"===a){this.isImg=!0;this.originalUrl=b=d.getAttribute("src");if(!b)return;b=d.src}else"canvas"===a&&window.HTMLCanvasElement&&(b=d.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1));this.load(b)}}},{key:"load",value:function(d){var a=this,b=a.options,c=a.element;if(d)if(a.url=d,a.imageData={},b.checkOrientation&&window.ArrayBuffer)if(ya.test(d))za.test(d)?a.read(ra(d)):a.clone();else{var k=new XMLHttpRequest;k.onerror=function(){a.clone()};
k.onload=function(){a.read(k.response)};b.checkCrossOrigin&&Y(d)&&c.crossOrigin&&(d=Z(d));k.open("get",d);k.responseType="arraybuffer";k.withCredentials="use-credentials"===c.crossOrigin;k.send()}else a.clone()}},{key:"read",value:function(d){var a=this.options,b;b=new DataView(d);var c=b.byteLength,k=void 0,f=void 0,l=void 0,e=f=void 0,n=l=f=void 0,h=f=void 0;if(255===b.getUint8(0)&&216===b.getUint8(1))for(f=2;f<c;){if(255===b.getUint8(f)&&225===b.getUint8(f+1)){l=f;break}f+=1}if(l){f=l+4;l+=10;
c="";h=f;for(f=4+f;h<f;h+=1)c+=ea(b.getUint8(h));"Exif"===c&&(f=b.getUint16(l),!(e=18761===f)&&19789!==f||42!==b.getUint16(l+2,e)||(f=b.getUint32(l+4,e),8<=f&&(n=l+f)))}if(n)for(c=b.getUint16(n,e),h=0;h<c;h+=1)if(f=n+12*h+2,274===b.getUint16(f,e)){f+=8;k=b.getUint16(f,e);aa&&b.setUint16(f,1,e);break}b=k;k=this.imageData;e=0;c=n=1;if(1<b){d=new Uint8Array(d);l=d.length;f="";h=void 0;for(h=0;h<l;h+=1)f+=ea(d[h]);this.url="data:image/jpeg;base64,"+btoa(f);switch(b){case 2:n=-1;break;case 3:e=-180;break;
case 4:c=-1;break;case 5:e=90;c=-1;break;case 6:e=90;break;case 7:e=90;n=-1;break;case 8:e=-90}}a.rotatable&&(k.rotate=e);a.scalable&&(k.scaleX=n,k.scaleY=c);this.clone()}},{key:"clone",value:function(){var d=this.element,a=this.url,b=void 0,c=void 0;this.options.checkCrossOrigin&&Y(a)&&((b=d.crossOrigin)?c=a:(b="anonymous",c=Z(a)));this.crossOrigin=b;this.crossOriginUrl=c;var k=document.createElement("img");b&&(k.crossOrigin=b);k.src=c||a;a=H(this.start,this);b=H(this.stop,this);this.image=k;this.onStart=
a;this.onStop=b;this.isImg?d.complete?this.start():D(d,"load",a):(D(k,"load",a),D(k,"error",b),y(k,"cropper-hide"),d.parentNode.insertBefore(k,d.nextSibling))}},{key:"start",value:function(d){var a=this,b=a.isImg?a.element:a.image;d&&(C(b,"load",a.onStart),C(b,"error",a.onStop));qa(b,function(d,g){q(a.imageData,{naturalWidth:d,naturalHeight:g,aspectRatio:d/g});a.loaded=!0;a.build()})}},{key:"stop",value:function(){var d=this.image;C(d,"load",this.onStart);C(d,"error",this.onStop);T(d);this.image=
null}},{key:"build",value:function(){var d=this,a=d.options,b=d.element,c=d.image;if(d.loaded){d.ready&&d.unbuild();var k=b.parentNode,f=document.createElement("div");f.innerHTML='<div class="cropper-container"><div class="cropper-wrap-box"><div class="cropper-canvas"></div></div><div class="cropper-drag-box"></div><div class="cropper-crop-box"><span class="cropper-view-box"></span><span class="cropper-dashed dashed-h"></span><span class="cropper-dashed dashed-v"></span><span class="cropper-center"></span><span class="cropper-face"></span><span class="cropper-line line-e" data-action="e"></span><span class="cropper-line line-n" data-action="n"></span><span class="cropper-line line-w" data-action="w"></span><span class="cropper-line line-s" data-action="s"></span><span class="cropper-point point-e" data-action="e"></span><span class="cropper-point point-n" data-action="n"></span><span class="cropper-point point-w" data-action="w"></span><span class="cropper-point point-s" data-action="s"></span><span class="cropper-point point-ne" data-action="ne"></span><span class="cropper-point point-nw" data-action="nw"></span><span class="cropper-point point-sw" data-action="sw"></span><span class="cropper-point point-se" data-action="se"></span></div></div>';
var f=G(f,"cropper-container")[0],l=G(f,"cropper-canvas")[0],e=G(f,"cropper-drag-box")[0],n=G(f,"cropper-crop-box")[0],p=G(n,"cropper-face")[0];d.container=k;d.cropper=f;d.canvas=l;d.dragBox=e;d.cropBox=n;d.viewBox=G(f,"cropper-view-box")[0];d.face=p;l.appendChild(c);y(b,"cropper-hidden");k.insertBefore(f,b.nextSibling);d.isImg||F(c,"cropper-hide");d.initPreview();d.bind();a.aspectRatio=Math.max(0,a.aspectRatio)||NaN;a.viewMode=Math.max(0,Math.min(3,Math.round(a.viewMode)))||0;(d.cropped=a.autoCrop)?
a.modal&&y(e,"cropper-modal"):y(n,"cropper-hidden");a.guides||y(G(n,"cropper-dashed"),"cropper-hidden");a.center||y(G(n,"cropper-center"),"cropper-hidden");a.background&&y(f,"cropper-bg");a.highlight||y(p,"cropper-invisible");a.cropBoxMovable&&(y(p,"cropper-move"),L(p,"action","all"));a.cropBoxResizable||(y(G(n,"cropper-line"),"cropper-hidden"),y(G(n,"cropper-point"),"cropper-hidden"));d.setDragMode(a.dragMode);d.render();d.ready=!0;d.setData(a.data);d.completing=setTimeout(function(){h(a.ready)&&
D(b,"ready",a.ready,!0);J(b,"ready");J(b,"crop",d.getData());d.complete=!0},0)}}},{key:"unbuild",value:function(){this.ready&&(this.complete||clearTimeout(this.completing),this.complete=this.ready=!1,this.cropBoxData=this.canvasData=this.containerData=this.initialCropBoxData=this.initialCanvasData=this.initialImageData=null,this.unbind(),this.resetPreview(),this.container=this.canvas=this.dragBox=this.cropBox=this.viewBox=this.previews=null,T(this.cropper),this.cropper=null)}}],[{key:"noConflict",
value:function(){window.Cropper=ia;return d}},{key:"setDefaults",value:function(d){q(ca,e(d)&&d)}}]);return d}();q(E.prototype,{render:function(){this.initContainer();this.initCanvas();this.initCropBox();this.renderCanvas();this.cropped&&this.renderCropBox()},initContainer:function(){var d=this.options,a=this.element,b=this.container,c=this.cropper;y(c,"cropper-hidden");F(a,"cropper-hidden");this.containerData=d={width:Math.max(b.offsetWidth,Number(d.minContainerWidth)||200),height:Math.max(b.offsetHeight,
Number(d.minContainerHeight)||100)};I(c,{width:d.width,height:d.height});y(a,"cropper-hidden");F(c,"cropper-hidden")},initCanvas:function(){var d=this.options.viewMode,a=this.containerData,b=this.imageData,c=90===Math.abs(b.rotate)%180,e=c?b.naturalHeight:b.naturalWidth,k=c?b.naturalWidth:b.naturalHeight,f=e/k,c=a.width,l=a.height;a.height*f>a.width?3===d?c=a.height*f:l=a.width/f:3===d?l=a.width/f:c=a.height*f;e={naturalWidth:e,naturalHeight:k,aspectRatio:f,width:c,height:l};e.left=(a.width-c)/2;
e.top=(a.height-l)/2;e.oldLeft=e.left;e.oldTop=e.top;this.canvasData=e;this.limited=1===d||2===d;this.limitCanvas(!0,!0);this.initialImageData=q({},b);this.initialCanvasData=q({},e)},limitCanvas:function(d,a){var b=this.options,c=b.viewMode,e=this.containerData,k=this.canvasData,f=k.aspectRatio,l=this.cropBoxData,h=this.cropped&&l;if(d){var n=Number(b.minCanvasWidth)||0,b=Number(b.minCanvasHeight)||0;1<c?(n=Math.max(n,e.width),b=Math.max(b,e.height),3===c&&(b*f>n?n=b*f:b=n/f)):0<c&&(n?n=Math.max(n,
h?l.width:0):b?b=Math.max(b,h?l.height:0):h&&(n=l.width,b=l.height,b*f>n?n=b*f:b=n/f));n&&b?b*f>n?b=n/f:n=b*f:n?b=n/f:b&&(n=b*f);k.minWidth=n;k.minHeight=b;k.maxWidth=Infinity;k.maxHeight=Infinity}a&&(c?(f=e.width-k.width,n=e.height-k.height,k.minLeft=Math.min(0,f),k.minTop=Math.min(0,n),k.maxLeft=Math.max(0,f),k.maxTop=Math.max(0,n),h&&this.limited&&(k.minLeft=Math.min(l.left,l.left+(l.width-k.width)),k.minTop=Math.min(l.top,l.top+(l.height-k.height)),k.maxLeft=l.left,k.maxTop=l.top,2===c&&(k.width>=
e.width&&(k.minLeft=Math.min(0,f),k.maxLeft=Math.max(0,f)),k.height>=e.height&&(k.minTop=Math.min(0,n),k.maxTop=Math.max(0,n))))):(k.minLeft=-k.width,k.minTop=-k.height,k.maxLeft=e.width,k.maxTop=e.height))},renderCanvas:function(d){var a=this.canvasData,b=this.imageData,c=b.rotate;if(this.rotated){this.rotated=!1;var e=Q({width:b.width,height:b.height,degree:c}),k=e.width/e.height,f=1===b.aspectRatio;if(f||k!==a.aspectRatio){a.left-=(e.width-a.width)/2;a.top-=(e.height-a.height)/2;a.width=e.width;
a.height=e.height;a.aspectRatio=k;a.naturalWidth=b.naturalWidth;a.naturalHeight=b.naturalHeight;if(f&&c%90||c%180)b=Q({width:b.naturalWidth,height:b.naturalHeight,degree:c}),a.naturalWidth=b.width,a.naturalHeight=b.height;this.limitCanvas(!0,!1)}}if(a.width>a.maxWidth||a.width<a.minWidth)a.left=a.oldLeft;if(a.height>a.maxHeight||a.height<a.minHeight)a.top=a.oldTop;a.width=Math.min(Math.max(a.width,a.minWidth),a.maxWidth);a.height=Math.min(Math.max(a.height,a.minHeight),a.maxHeight);this.limitCanvas(!1,
!0);a.left=Math.min(Math.max(a.left,a.minLeft),a.maxLeft);a.top=Math.min(Math.max(a.top,a.minTop),a.maxTop);a.oldLeft=a.left;a.oldTop=a.top;I(this.canvas,q({width:a.width,height:a.height},M({translateX:a.left,translateY:a.top})));this.renderImage();this.cropped&&this.limited&&this.limitCropBox(!0,!0);d&&this.output()},renderImage:function(d){var a=this.canvasData,b=this.imageData,c=void 0,e=void 0,k=void 0,e=void 0;b.rotate&&(e=Q({width:a.width,height:a.height,degree:b.rotate,aspectRatio:b.aspectRatio},
!0),k=e.width,e=e.height,c={width:k,height:e,left:(a.width-k)/2,top:(a.height-e)/2});q(b,c||{width:a.width,height:a.height,left:0,top:0});I(this.image,q({width:b.width,height:b.height},M(q({translateX:b.left,translateY:b.top},b))));d&&this.output()},initCropBox:function(){var d=this.options,a=d.aspectRatio,d=Number(d.autoCropArea)||.8,b=this.canvasData,c={width:b.width,height:b.height};a&&(b.height*a>b.width?c.height=c.width/a:c.width=c.height*a);this.cropBoxData=c;this.limitCropBox(!0,!0);c.width=
Math.min(Math.max(c.width,c.minWidth),c.maxWidth);c.height=Math.min(Math.max(c.height,c.minHeight),c.maxHeight);c.width=Math.max(c.minWidth,c.width*d);c.height=Math.max(c.minHeight,c.height*d);c.left=b.left+(b.width-c.width)/2;c.top=b.top+(b.height-c.height)/2;c.oldLeft=c.left;c.oldTop=c.top;this.initialCropBoxData=q({},c)},limitCropBox:function(d,a){var b=this.options,c=b.aspectRatio,e=this.containerData,k=this.canvasData,f=this.cropBoxData,l=this.limited;if(d){var h=Number(b.minCropBoxWidth)||0,
b=Number(b.minCropBoxHeight)||0,n=Math.min(e.width,l?k.width:e.width),p=Math.min(e.height,l?k.height:e.height),h=Math.min(h,e.width),b=Math.min(b,e.height);c&&(h&&b?b*c>h?b=h/c:h=b*c:h?b=h/c:b&&(h=b*c),p*c>n?p=n/c:n=p*c);f.minWidth=Math.min(h,n);f.minHeight=Math.min(b,p);f.maxWidth=n;f.maxHeight=p}a&&(l?(f.minLeft=Math.max(0,k.left),f.minTop=Math.max(0,k.top),f.maxLeft=Math.min(e.width,k.left+k.width)-f.width,f.maxTop=Math.min(e.height,k.top+k.height)-f.height):(f.minLeft=0,f.minTop=0,f.maxLeft=e.width-
f.width,f.maxTop=e.height-f.height))},renderCropBox:function(){var d=this.options,a=this.containerData,b=this.cropBoxData;if(b.width>b.maxWidth||b.width<b.minWidth)b.left=b.oldLeft;if(b.height>b.maxHeight||b.height<b.minHeight)b.top=b.oldTop;b.width=Math.min(Math.max(b.width,b.minWidth),b.maxWidth);b.height=Math.min(Math.max(b.height,b.minHeight),b.maxHeight);this.limitCropBox(!1,!0);b.left=Math.min(Math.max(b.left,b.minLeft),b.maxLeft);b.top=Math.min(Math.max(b.top,b.minTop),b.maxTop);b.oldLeft=
b.left;b.oldTop=b.top;d.movable&&d.cropBoxMovable&&L(this.face,"action",b.width===a.width&&b.height===a.height?"move":"all");I(this.cropBox,q({width:b.width,height:b.height},M({translateX:b.left,translateY:b.top})));this.cropped&&this.limited&&this.limitCanvas(!0,!0);this.disabled||this.output()},output:function(){this.preview();this.complete&&J(this.element,"crop",this.getData())}});q(E.prototype,{initPreview:function(){var d=this.options.preview,a=document.createElement("img"),b=this.crossOrigin,
c=b?this.crossOriginUrl:this.url;b&&(a.crossOrigin=b);a.src=c;this.viewBox.appendChild(a);this.image2=a;d&&(this.previews=d=d.querySelector?[d]:document.querySelectorAll(d),p(d,function(d){var a=document.createElement("img");L(d,"preview",{width:d.offsetWidth,height:d.offsetHeight,html:d.innerHTML});b&&(a.crossOrigin=b);a.src=c;for(a.style.cssText='display:block;width:100%;height:auto;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;image-orientation:0deg!important;"';d.firstChild;)d.removeChild(d.firstChild);
d.appendChild(a)}))},resetPreview:function(){p(this.previews,function(d){var a=O(d,"preview");I(d,{width:a.width,height:a.height});d.innerHTML=a.html;V(d,"preview")})},preview:function(){var d=this.imageData,a=this.canvasData,b=this.cropBoxData,c=b.width,e=b.height,k=d.width,f=d.height,l=b.left-a.left-d.left,h=b.top-a.top-d.top;this.cropped&&!this.disabled&&(I(this.image2,q({width:k,height:f},M(q({translateX:-l,translateY:-h},d)))),p(this.previews,function(a){var b=O(a,"preview"),g=b.width,b=b.height,
m=g,p=b,x=1;c&&(x=g/c,p=e*x);e&&p>b&&(x=b/e,m=c*x,p=b);I(a,{width:m,height:p});I(a.getElementsByTagName("img")[0],q({width:k*x,height:f*x},M(q({translateX:-l*x,translateY:-h*x},d))))}))}});q(E.prototype,{bind:function(){var a=this.options,b=this.element,c=this.cropper;h(a.cropstart)&&D(b,"cropstart",a.cropstart);h(a.cropmove)&&D(b,"cropmove",a.cropmove);h(a.cropend)&&D(b,"cropend",a.cropend);h(a.crop)&&D(b,"crop",a.crop);h(a.zoom)&&D(b,"zoom",a.zoom);D(c,fa,this.onCropStart=H(this.cropStart,this));
a.zoomable&&a.zoomOnWheel&&D(c,"wheel mousewheel DOMMouseScroll",this.onWheel=H(this.wheel,this));a.toggleDragModeOnDblclick&&D(c,"dblclick",this.onDblclick=H(this.dblclick,this));D(document,ga,this.onCropMove=H(this.cropMove,this));D(document,ha,this.onCropEnd=H(this.cropEnd,this));a.responsive&&D(window,"resize",this.onResize=H(this.resize,this))},unbind:function(){var a=this.options,b=this.element,c=this.cropper;h(a.cropstart)&&C(b,"cropstart",a.cropstart);h(a.cropmove)&&C(b,"cropmove",a.cropmove);
h(a.cropend)&&C(b,"cropend",a.cropend);h(a.crop)&&C(b,"crop",a.crop);h(a.zoom)&&C(b,"zoom",a.zoom);C(c,fa,this.onCropStart);a.zoomable&&a.zoomOnWheel&&C(c,"wheel mousewheel DOMMouseScroll",this.onWheel);a.toggleDragModeOnDblclick&&C(c,"dblclick",this.onDblclick);C(document,ga,this.onCropMove);C(document,ha,this.onCropEnd);a.responsive&&C(window,"resize",this.onResize)}});q(E.prototype,{resize:function(){var a=this.options,b=this.container,c=this.containerData,e=Number(a.minContainerWidth)||200,h=
Number(a.minContainerHeight)||100;if(!this.disabled&&c.width!==e&&c.height!==h){var k=b.offsetWidth/c.width;if(1!==k||b.offsetHeight!==c.height){var f=void 0,l=void 0;a.restore&&(f=this.getCanvasData(),l=this.getCropBoxData());this.render();a.restore&&(this.setCanvasData(p(f,function(a,b){f[b]=a*k})),this.setCropBoxData(p(l,function(a,b){l[b]=a*k})))}}},dblclick:function(){this.disabled||"none"===this.options.dragMode||this.setDragMode(na(this.dragBox,"cropper-crop")?"move":"crop")},wheel:function(a){var b=
this;a=P(a);var c=Number(b.options.wheelZoomRatio)||.1,e=1;b.disabled||(a.preventDefault(),b.wheeling||(b.wheeling=!0,setTimeout(function(){b.wheeling=!1},50),a.deltaY?e=0<a.deltaY?1:-1:a.wheelDelta?e=-a.wheelDelta/120:a.detail&&(e=0<a.detail?1:-1),b.zoom(-e*c,a)))},cropStart:function(a){if(!this.disabled){var b=this.options,c=this.pointers;a=P(a);var e=void 0;a.changedTouches?p(a.changedTouches,function(a){c[a.identifier]=R(a)}):c[a.pointerId||0]=R(a);e=1<Object.keys(c).length&&b.zoomable&&b.zoomOnTouch?
"zoom":O(a.target,"action");wa.test(e)&&!1!==J(this.element,"cropstart",{originalEvent:a,action:e})&&(a.preventDefault(),this.action=e,this.cropping=!1,"crop"===e&&(this.cropping=!0,y(this.dragBox,"cropper-modal")))}},cropMove:function(a){var b=this.action;if(!this.disabled&&b){var c=this.pointers;a=P(a);a.preventDefault();!1!==J(this.element,"cropmove",{originalEvent:a,action:b})&&(a.changedTouches?p(a.changedTouches,function(a){q(c[a.identifier],R(a,!0))}):q(c[a.pointerId||0],R(a,!0)),this.change(a))}},
cropEnd:function(a){if(!this.disabled){var b=this.action,c=this.pointers;a=P(a);a.changedTouches?p(a.changedTouches,function(a){delete c[a.identifier]}):delete c[a.pointerId||0];b&&(a.preventDefault(),Object.keys(c).length||(this.action=""),this.cropping&&(this.cropping=!1,K(this.dragBox,"cropper-modal",this.cropped&&this.options.modal)),J(this.element,"cropend",{originalEvent:a,action:b}))}}});q(E.prototype,{change:function(a){var b=this.containerData,c=this.canvasData,e=this.cropBoxData,h=this.options.aspectRatio,
k=this.action,f=e.width,l=e.height,v=e.left,n=e.top,q=v+f,r=n+l,u=0,B=0,x=b.width,A=b.height,z=!0,y=void 0;!h&&a.shiftKey&&(h=f&&l?f/l:1);this.limited&&(u=e.minLeft,B=e.minTop,x=u+Math.min(b.width,c.width,c.left+c.width),A=B+Math.min(b.height,c.height,c.top+c.height));var b=this.pointers,c=b[Object.keys(b)[0]],w=c.endX-c.startX,t=c.endY-c.startY;switch(k){case "all":v+=w;n+=t;break;case "e":if(0<=w&&(q>=x||h&&(n<=B||r>=A))){z=!1;break}q+w>x&&(w=x-q);f+=w;h&&(l=f/h,n-=w/h/2);0>f&&(k="w",f=0);break;
case "n":if(0>=t&&(n<=B||h&&(v<=u||q>=x))){z=!1;break}n+t<B&&(t=B-n);l-=t;n+=t;h&&(f=l*h,v+=t*h/2);0>l&&(k="s",l=0);break;case "w":if(0>=w&&(v<=u||h&&(n<=B||r>=A))){z=!1;break}v+w<u&&(w=u-v);f-=w;v+=w;h&&(l=f/h,n+=w/h/2);0>f&&(k="e",f=0);break;case "s":if(0<=t&&(r>=A||h&&(v<=u||q>=x))){z=!1;break}r+t>A&&(t=A-r);l+=t;h&&(f=l*h,v-=t*h/2);0>l&&(k="n",l=0);break;case "ne":if(h){if(0>=t&&(n<=B||q>=x)){z=!1;break}l-=t;n+=t;f=l*h}else 0<=w?q<x?f+=w:0>=t&&n<=B&&(z=!1):f+=w,0>=t?n>B&&(l-=t,n+=t):(l-=t,n+=
t);0>f&&0>l?(k="sw",f=l=0):0>f?(k="nw",f=0):0>l&&(k="se",l=0);break;case "nw":if(h){if(0>=t&&(n<=B||v<=u)){z=!1;break}l-=t;n+=t;f=l*h;v+=t*h}else 0>=w?v>u?(f-=w,v+=w):0>=t&&n<=B&&(z=!1):(f-=w,v+=w),0>=t?n>B&&(l-=t,n+=t):(l-=t,n+=t);0>f&&0>l?(k="se",f=l=0):0>f?(k="ne",f=0):0>l&&(k="sw",l=0);break;case "sw":if(h){if(0>=w&&(v<=u||r>=A)){z=!1;break}f-=w;v+=w;l=f/h}else 0>=w?v>u?(f-=w,v+=w):0<=t&&r>=A&&(z=!1):(f-=w,v+=w),0<=t?r<A&&(l+=t):l+=t;0>f&&0>l?(k="ne",f=l=0):0>f?(k="se",f=0):0>l&&(k="nw",l=0);
break;case "se":if(h){if(0<=w&&(q>=x||r>=A)){z=!1;break}f+=w;l=f/h}else 0<=w?q<x?f+=w:0<=t&&r>=A&&(z=!1):f+=w,0<=t?r<A&&(l+=t):l+=t;0>f&&0>l?(k="nw",f=l=0):0>f?(k="sw",f=0):0>l&&(k="ne",l=0);break;case "move":this.move(w,t);z=!1;break;case "zoom":this.zoom(ta(b),a);z=!1;break;case "crop":if(!w||!t){z=!1;break}y=X(this.cropper);v=c.startX-y.left;n=c.startY-y.top;f=e.minWidth;l=e.minHeight;0<w?k=0<t?"se":"ne":0>w&&(v-=f,k=0<t?"sw":"nw");0>t&&(n-=l);this.cropped||(F(this.cropBox,"cropper-hidden"),this.cropped=
!0,this.limited&&this.limitCropBox(!0,!0))}z&&(e.width=parseInt(f,10),e.height=parseInt(l,10),e.left=v,e.top=n,this.action=k,this.renderCropBox());p(b,function(a){a.startX=a.endX;a.startY=a.endY})}});q(E.prototype,{crop:function(){this.ready&&!this.disabled&&(this.cropped||(this.cropped=!0,this.limitCropBox(!0,!0),this.options.modal&&y(this.dragBox,"cropper-modal"),F(this.cropBox,"cropper-hidden")),this.setCropBoxData(this.initialCropBoxData));return this},reset:function(){this.ready&&!this.disabled&&
(this.imageData=q({},this.initialImageData),this.canvasData=q({},this.initialCanvasData),this.cropBoxData=q({},this.initialCropBoxData),this.renderCanvas(),this.cropped&&this.renderCropBox());return this},clear:function(){this.cropped&&!this.disabled&&(q(this.cropBoxData,{left:0,top:0,width:0,height:0}),this.cropped=!1,this.renderCropBox(),this.limitCanvas(!0,!0),this.renderCanvas(),F(this.dragBox,"cropper-modal"),y(this.cropBox,"cropper-hidden"));return this},replace:function(a,b){!this.disabled&&
a&&(this.isImg&&(this.element.src=a),b?(this.url=a,this.image.src=a,this.ready&&(this.image2.src=a,p(this.previews,function(b){b.getElementsByTagName("img")[0].src=a}))):(this.isImg&&(this.replaced=!0),this.options.data=null,this.load(a)));return this},enable:function(){this.ready&&(this.disabled=!1,F(this.cropper,"cropper-disabled"));return this},disable:function(){this.ready&&(this.disabled=!0,y(this.cropper,"cropper-disabled"));return this},destroy:function(){var a=this.element,b=this.image;this.loaded?
(this.isImg&&this.replaced&&(a.src=this.originalUrl),this.unbuild(),F(a,"cropper-hidden")):this.isImg?C(a,"load",this.onStart):b&&T(b);V(a,"cropper");return this},move:function(a,c){var e=this.canvasData;return this.moveTo(b(a)?a:e.left+Number(a),b(c)?c:e.top+Number(c))},moveTo:function(d,c){var e=this.canvasData,h=!1;b(c)&&(c=d);d=Number(d);c=Number(c);this.ready&&!this.disabled&&this.options.movable&&(a(d)&&(e.left=d,h=!0),a(c)&&(e.top=c,h=!0),h&&this.renderCanvas(!0));return this},zoom:function(a,
b){var c=this.canvasData;a=Number(a);return this.zoomTo(c.width*(0>a?1/(1-a):1+a)/c.naturalWidth,b)},zoomTo:function(a,b){var c=this.options,e=this.canvasData,h=e.width,k=e.height,f=e.naturalWidth,l=e.naturalHeight;a=Number(a);if(0<=a&&this.ready&&!this.disabled&&c.zoomable){c=f*a;l*=a;if(!1===J(this.element,"zoom",{originalEvent:b,oldRatio:h/f,ratio:c/f}))return this;if(b){var p=this.pointers,f=X(this.cropper),p=p&&Object.keys(p).length?va(p):{pageX:b.pageX,pageY:b.pageY};e.left-=(p.pageX-f.left-
e.left)/h*(c-h);e.top-=(p.pageY-f.top-e.top)/k*(l-k)}else e.left-=(c-h)/2,e.top-=(l-k)/2;e.width=c;e.height=l;this.renderCanvas(!0)}return this},rotate:function(a){return this.rotateTo((this.imageData.rotate||0)+Number(a))},rotateTo:function(b){b=Number(b);a(b)&&this.ready&&!this.disabled&&this.options.rotatable&&(this.imageData.rotate=b%360,this.rotated=!0,this.renderCanvas(!0));return this},scale:function(c,g){var e=this.imageData,h=!1;b(g)&&(g=c);c=Number(c);g=Number(g);this.ready&&!this.disabled&&
this.options.scalable&&(a(c)&&(e.scaleX=c,h=!0),a(g)&&(e.scaleY=g,h=!0),h&&this.renderImage(!0));return this},scaleX:function(b){var c=this.imageData.scaleY;return this.scale(b,a(c)?c:1)},scaleY:function(b){var c=this.imageData.scaleX;return this.scale(a(c)?c:1,b)},getData:function(a){var b=this.options,c=this.imageData,e=this.canvasData,h=this.cropBoxData,k=void 0,f=void 0;this.ready&&this.cropped?(f={x:h.left-e.left,y:h.top-e.top,width:h.width,height:h.height},k=c.width/c.naturalWidth,p(f,function(b,
c){b/=k;f[c]=a?Math.round(b):b})):f={x:0,y:0,width:0,height:0};b.rotatable&&(f.rotate=c.rotate||0);b.scalable&&(f.scaleX=c.scaleX||1,f.scaleY=c.scaleY||1);return f},setData:function(b){var c=this.options,m=this.imageData,p=this.canvasData,q={},k=void 0,f=void 0,l=void 0;h(b)&&(b=b.call(this.element));this.ready&&!this.disabled&&e(b)&&(c.rotatable&&a(b.rotate)&&b.rotate!==m.rotate&&(m.rotate=b.rotate,this.rotated=k=!0),c.scalable&&(a(b.scaleX)&&b.scaleX!==m.scaleX&&(m.scaleX=b.scaleX,f=!0),a(b.scaleY)&&
b.scaleY!==m.scaleY&&(m.scaleY=b.scaleY,f=!0)),k?this.renderCanvas():f&&this.renderImage(),l=m.width/m.naturalWidth,a(b.x)&&(q.left=b.x*l+p.left),a(b.y)&&(q.top=b.y*l+p.top),a(b.width)&&(q.width=b.width*l),a(b.height)&&(q.height=b.height*l),this.setCropBoxData(q));return this},getContainerData:function(){return this.ready?this.containerData:{}},getImageData:function(){return this.loaded?this.imageData:{}},getCanvasData:function(){var a=this.canvasData,b={};this.ready&&p("left top width height naturalWidth naturalHeight".split(" "),
function(c){b[c]=a[c]});return b},setCanvasData:function(b){var c=this.canvasData,m=c.aspectRatio;h(b)&&(b=b.call(this.element));this.ready&&!this.disabled&&e(b)&&(a(b.left)&&(c.left=b.left),a(b.top)&&(c.top=b.top),a(b.width)?(c.width=b.width,c.height=b.width/m):a(b.height)&&(c.height=b.height,c.width=b.height*m),this.renderCanvas(!0));return this},getCropBoxData:function(){var a=this.cropBoxData,b=void 0;this.ready&&this.cropped&&(b={left:a.left,top:a.top,width:a.width,height:a.height});return b||
{}},setCropBoxData:function(b){var c=this.cropBoxData,m=this.options.aspectRatio,p=void 0,q=void 0;h(b)&&(b=b.call(this.element));this.ready&&this.cropped&&!this.disabled&&e(b)&&(a(b.left)&&(c.left=b.left),a(b.top)&&(c.top=b.top),a(b.width)&&b.width!==c.width&&(p=!0,c.width=b.width),a(b.height)&&b.height!==c.height&&(q=!0,c.height=b.height),m&&(p?c.height=parseInt(c.width/m,10):q&&(c.width=parseInt(c.height*m,10))),this.renderCropBox());return this},getCroppedCanvas:function(a){if(!this.ready||!window.HTMLCanvasElement)return null;
e(a)||(a={});if(!this.cropped)return ba(this.image,this.imageData,a);var b=this.getData(),c=b.width,h=b.height,p=c/h,k=void 0,f=void 0,l=void 0;e(a)&&(k=a.width,f=a.height,k?(f=k/p,l=k/c):f&&(k=f*p,l=f/h));var k=Math.floor(k||c),q=Math.floor(f||h),f=document.createElement("canvas"),p=f.getContext("2d");f.width=k;f.height=q;a.fillColor&&(p.fillStyle=a.fillColor,p.fillRect(0,0,k,q));var n=ba(this.image,this.imageData,a),k=n.width,q=n.height,r=this.canvasData,n=[n],u=b.x+r.naturalWidth*(Math.abs(b.scaleX||
1)-1)/2,b=b.y+r.naturalHeight*(Math.abs(b.scaleY||1)-1)/2,y=r=void 0,B=void 0,x=void 0,A=void 0,z=void 0;u<=-c||u>k?A=B=r=u=0:0>=u?(B=-u,u=0,A=r=Math.min(k,c+u)):u<=k&&(B=0,A=r=Math.min(c,k-u));0>=r||b<=-h||b>q?z=x=y=b=0:0>=b?(x=-b,b=0,z=y=Math.min(q,h+b)):b<=q&&(x=0,z=y=Math.min(h,q-b));n.push(Math.floor(u),Math.floor(b),Math.floor(r),Math.floor(y));l&&(B*=l,x*=l,A*=l,z*=l);0<A&&0<z&&n.push(Math.floor(B),Math.floor(x),Math.floor(A),Math.floor(z));p.imageSmoothingEnabled=!!a.imageSmoothingEnabled;
a.imageSmoothingQuality&&(p.imageSmoothingQuality=a.imageSmoothingQuality);p.drawImage.apply(p,ua(n));return f},setAspectRatio:function(a){var c=this.options;this.disabled||b(a)||(c.aspectRatio=Math.max(0,a)||NaN,this.ready&&(this.initCropBox(),this.cropped&&this.renderCropBox()));return this},setDragMode:function(a){var b=this.options,c=this.dragBox,e=this.face,h=void 0,k=void 0;this.loaded&&!this.disabled&&(h="crop"===a,k=b.movable&&"move"===a,a=h||k?a:"none",L(c,"action",a),K(c,"cropper-crop",
h),K(c,"cropper-move",k),b.cropBoxMovable||(L(e,"action",a),K(e,"cropper-crop",h),K(e,"cropper-move",k)));return this}});"undefined"!==typeof window&&(ia=window.Cropper,window.Cropper=E);return E});var KMINIPHOTOTOP=parent;setMiniPhotoWindow();setMiniPhotoDocument();KMINIPHOTOTOP.KMINIPHOTO=parent.KMINIPHOTO;parent.KMINIPHOTOTOP=KMINIPHOTOTOP;Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;){if(this[b]===a)return b;++b}return-1});String.prototype.insertAt||(String.prototype.insertAt=function(a,b){return this.substr(0,a)+b+this.substr(a)});
String.prototype.replaceAt||(String.prototype.replaceAt=function(a,b){return this.substr(0,a)+b+this.substr(a+b.length)});function setMiniPhotoWindow(){try{topURL=top.location.href,"undefined"==typeof topURL?(KMINIPHOTOTOP.KMINIPHOTOWIN=parent,KMINIPHOTOTOP.IsCrossDomain=!0):(KMINIPHOTOTOP.KMINIPHOTOWIN=parent,KMINIPHOTOTOP.IsCrossDomain=!1)}catch(a){KMINIPHOTOTOP.KMINIPHOTOWIN=parent,KMINIPHOTOTOP.IsCrossDomain=!0}}
function setMiniPhotoDocument(){try{topURL=top.location.href,"undefined"==typeof topURL?(KMINIPHOTOTOP.KMINIPHOTODOC=parent.document,KMINIPHOTOTOP.IsCrossDomain=!0):(KMINIPHOTOTOP.KMINIPHOTODOC=parent.document,KMINIPHOTOTOP.IsCrossDomain=!1)}catch(a){KMINIPHOTOTOP.KMINIPHOTODOC=parent.document,KMINIPHOTOTOP.IsCrossDomain=!0}}function raonk_frame_loaded_event(a,b,c){_raonk_miniphoto=new K_MiniPhoto(a,b,c);_raonk_miniphoto.start(b,_raonk_miniphoto)}
function K_MiniPhoto(a,b,c){this._config=b;this._frame=c;this.frameWin=window;this.ID=a;KMINIPHOTOTOP.KMINIPHOTO.RAONKMULTIPLE[c.frameID]=this;KMINIPHOTOTOP.G_CURRKMINIPHOTO=this;this.currDegree=0;this.flipY=this.flipX=!1;this.initImgHeight=this.initImgWidth=this.initImg=this.cropper=null;this.frameStatus=this.initImgExt="";this.arrBlobUrl=[];try{"function"===typeof KMINIPHOTOTOP.KMINIPHOTOWIN.KMINIPHOTO_OnLanguageDefinition&&KMINIPHOTOTOP.KMINIPHOTOWIN.KMINIPHOTO_OnLanguageDefinition(a,KMiniPhoto_Lang)}catch(e){}}
K_MiniPhoto.prototype={init:function(a){KMINIPHOTOTOP.KMINIPHOTO.util._setKMiniPhoto(a)},reset:function(a){KMINIPHOTOTOP.KMINIPHOTO.util._setKMiniPhoto(a)},start:function(a,b){var c=b._config;getDialogDocument();var e=parseInt(c.height);-1<c.height.indexOf("%")&&(e=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(KMINIPHOTOTOP.KMINIPHOTODOC.getElementById("kminiphoto_holder_"+b.ID)),e=e.bottom-e.top);var h=parseInt(c.width);-1<c.width.indexOf("%")&&(h=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(KMINIPHOTOTOP.KMINIPHOTODOC.getElementById("kminiphoto_holder_"+
b.ID)),h=h.right-h.left);getAreaSize(e,c,b);c=""+('<div id="miniPhoto_holder" class="wrap" style="width: '+(h-2)+'px;">')+'<div id="miniPhoto_header" class="header">';c+="<h3></h3>";c+='<div class="btn-right">';c+='<a id="btn_fullscreen" href="javascript:;" class="maximization" title="'+KMiniPhoto_Lang.fullScreen+'"><span class="blind"></span></a><a href="javascript:;" class="close" title="'+KMiniPhoto_Lang.close+'"><span class="blind"></span></a>';c+="</div>";c+="</div>";c+='<div class="toolbar">';
c+='<input id="open_file" type="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff,.tif" style="display:none;"/>';c+='<a id="btn_open" href="javascript:;" class="btn-function"><span class="img-open"></span><em>'+KMiniPhoto_Lang.open+"</em></a>";c+='<i class="vertical"></i>';c+='<a id="btn_undo" href="javascript:;" class="btn-do" title="'+KMiniPhoto_Lang.undo+'"><i class="undo deact-u"></i><p class="blind"></p></a>';c+='<a id="btn_redo" href="javascript:;" class="btn-do" title="'+KMiniPhoto_Lang.redo+'"><i class="redo deact-r"></i><p class="blind"></p></a>';
c+='<i class="vertical"></i>';c+='<a id="btn_crop" href="javascript:;" class="btn-function"><span class="img-crop"></span><em>'+KMiniPhoto_Lang.crop+"</em></a>";c+='<ul id="crop_tools_area" class="off">';c+='<li class="" title="Free"><a id="crop_ratio_0" href="javascript:;"><span class="img-ratio-free"></span><em>Free</em></a></li>';c+='<li class="" title="4:3"><a id="crop_ratio_1" href="javascript:;"><span class="img-ratio-4-3"></span><em>4:3</em></a></li>';c+='<li class="" title="16:9"><a id="crop_ratio_2" href="javascript:;"><span class="img-ratio-16-9"></span><em>16:9</em></a></li>';
c+='<li class="" title="1:1"><a id="crop_ratio_3" href="javascript:;"><span class="img-ratio-1-1"></span><em>1:1</em></a></li>';c+='<li class="" title="2:3"><a id="crop_ratio_4" href="javascript:;"><span class="img-ratio-2-3"></span><em>2:3</em></a></li>';c+='<li class="" title="3:4"><a id="crop_ratio_5" href="javascript:;"><span class="img-ratio-3-4"></span><em>3:4</em></a></li>';c+='<li class="btnForCrop"><a id="crop_ok" href="javascript:;"><span class="btn-apply" title="'+KMiniPhoto_Lang.cropOk+
'"></span><p class="blind"></p></a></li>';c+='<li class="btnForCrop"><a id="crop_cancel" href="javascript:;"><span class="btn-cancel" title="'+KMiniPhoto_Lang.cropCancel+'"></span><p class="blind"></p></a></li>';c+="</ul>";c+='<a id="img_rotate_l" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.rotate_l_detail+'"><span class="img-rotationL"></span><em>'+KMiniPhoto_Lang.rotate_l+"</em></a>";c+='<a id="img_rotate_r" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.rotate_r_detail+
'"><span class="img-rotationR"></span><em>'+KMiniPhoto_Lang.rotate_r+"</em></a>";c+='<a id="img_flip_h" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.flip_x_detail+'"><span class="img-flipV"></span><em>'+KMiniPhoto_Lang.flip_x+"</em></a>";c+='<a id="img_flip_v" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.flip_y_detail+'"><span class="img-flipH"></span><em>'+KMiniPhoto_Lang.flip_y+"</em></a>";c+='<div class="buttonArea">';c+='<a id="btn_apply" href="javascript:;" class="btnApply" title="'+
KMiniPhoto_Lang.apply+'"><span>'+KMiniPhoto_Lang.apply+'</span></a><a id="btn_reset" href="javascript:;" class="btnCancel" title="'+KMiniPhoto_Lang.reset+'"><span>'+KMiniPhoto_Lang.reset+"</span></a>";c+="</div>";c+="</div>";c+="<table>";c+="<tbody>";c+='<tr class="imageArea"><td><span id="span_processing" class="RAONK_photo_loading_img" style="display:none;">Processing...</span><div id="miniPhoto_image" style="height:'+b.areaSize.imageAreaHeight+'px; border:0; overflow:auto;"><div style="position:relative; background-image:url(\'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA3NCSVQICAjb4U/gAAAABlBMVEXMzMz////TjRV2AAAACXBIWXMAAArrAAAK6wGCiw1aAAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAABFJREFUCJlj+M/AgBVhF/0PAH6/D/HkDxOGAAAAAElFTkSuQmCC\')"></div></div></td></tr>';
c+='<tr class="sizeArea">';c+="<td>";c+='<div class="t-l" style="display:none;">';c+="<span>"+KMiniPhoto_Lang.current_size+"</span>";c+='<em id="crop_box_size">0 x 0 px</em>';c+="</div>";c+='<div class="t-r">';c+='<span class="hhh">'+KMiniPhoto_Lang.original_size+"</span>";c+='<em id="original_size">0 x 0 px</em>';c+="</div>";c+="</td>";c+="</tr>";c+="</tbody>";c+="</table>";c+="</div>";c+="</div>";document.body.style.overflow="hidden";document.body.innerHTML=c;setPage(b)},_raonkCommands:function(a,
b,c,e){G_LAST_CMD=b},_setLazyLoadFrame:function(a){"0"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.hideContextMenu&&KMINIPHOTO_CONTEXT._create(a)}};
function setPage(a){KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+a.ID).getElementsByTagName("h3")[0].innerHTML=KMiniPhoto_Lang.title;KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+a.ID).title=KMiniPhoto_Lang.fullScreen;KMINIPHOTOTOP.document.getElementById("btn_close_"+a.ID).title=KMiniPhoto_Lang.close;setImageArea();try{"function"===typeof a._config.creationCompleteEvent&&a._config.creationCompleteEvent(a.ID)}catch(b){}}
function loadImage(a){null==a.src?(a.isInit&&setEvent(),displayOriginalSize()):(displayProcessing(!0),setTimeout(function(){var b=document.getElementById("miniPhoto_image").firstChild;b&&(b.style.width="0px",b.style.height="0px");b.innerHTML="";KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=null;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=void 0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;var c=new Image;c.style.display="none";b.appendChild(c);var e=document.createElement("canvas");e.id="image_canvas";b.appendChild(e);
c.crossOrigin="anonymous";c.onerror=function(){alert("error load image");fn_close()};c.onload=function(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=c;var b,r,u=c.naturalWidth,p=c.naturalHeight;b=a.width&&""!=a.width?a.width:u;r=a.height&&""!=a.height?a.height:p;e.width=parseInt(b,10);e.height=parseInt(r,10);e.parentNode.style.width=e.width+"px";e.parentNode.style.height=e.height+
"px";e.getContext("2d").drawImage(c,0,0,u,p,0,0,e.width,e.height);c.style.display="none";setCanvasPostionCenter();a.isInit?(setEvent(),G_HISTORY.reset(),KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg=c,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgWidth=a.width,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgHeight=a.height,b=e.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1),loadImage({src:b,isResized:!0})):a.isResized&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg=c);a.isOpen&&(G_HISTORY.reset(),KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg=
c,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgWidth=c.naturalWidth,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgHeight=c.naturalHeight);displayProcessing(!1);try{c=void 0}catch(q){}};0==a.src.indexOf("blob")&&KMINIPHOTOTOP.G_CURRKMINIPHOTO.arrBlobUrl.push(a.src);b=document.getElementById("open_file");b.value="";KMINIPHOTOTOP.KMINIPHOTO.browser.ie&&10==KMINIPHOTOTOP.KMINIPHOTO.browser.ieVersion&&(b.type="text",b.type="file");c.src=a.src},50))}
function displayOriginalSize(){var a=document.getElementById("original_size"),b=document.getElementById("image_canvas");a.innerHTML=b?b.width+" x "+b.height+" px":"0 x 0 px"}function getDialogWindow(){var a=KMINIPHOTOTOP.window;null!=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow&&(a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow);return a}
function getDialogDocument(){var a=KMINIPHOTOTOP.window.document;null!=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow&&(a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow.document);return a}function getAreaSize(a,b,c){c.areaSize={headerHeight:30,toolHeight:56,imageAreaHeight:a-30-56-20-2,footerHeight:20}}
function setImageArea(){var a=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(document.getElementById("miniPhoto_image").parentNode),a=a.right-a.left,b=document.getElementById("miniPhoto_image");b.style.width=a+"px";b.style.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.areaSize.imageAreaHeight+"px"}
function setCanvasPostionCenter(){var a=document.getElementById("image_canvas");if(a){var b=a.parentNode.parentNode,c;b.clientWidth?(c=b.clientWidth,b=b.clientHeight):(b=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(b),c=b.width,b=b.height);b=Math.round(b/2-a.height/2);0>b&&(b=0);c=Math.round(c/2-a.width/2);0>c&&(c=0);a&&(a.parentNode.style.top=b+"px",a.parentNode.style.left=c+"px");displayOriginalSize()}}
function setEvent(){var a=document.getElementById("open_file");a.onchange=function(){var b=a.files[0];if(b){var c=getImageExtensionFromType(b.type),b=(window.URL||window.webkitURL||window).createObjectURL(b);KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt=c;loadImage({isInit:!1,isOpen:!0,src:b})}};document.getElementById("btn_open").onclick=function(){cropCancel();fileOpen()};document.getElementById("btn_undo").onclick=function(){if(null!=document.getElementById("image_canvas")){cropCancel();var a=document.getElementById("image_canvas");
G_HISTORY.undo(a,a.getContext("2d"))}};document.getElementById("btn_redo").onclick=function(){if(null!=document.getElementById("image_canvas")){cropCancel();var a=document.getElementById("image_canvas");G_HISTORY.redo(a,a.getContext("2d"))}};document.getElementById("img_rotate_r").onclick=function(){fn_imageChange({degree:90,flip:0})};document.getElementById("img_rotate_l").onclick=function(){fn_imageChange({degree:-90,flip:0})};document.getElementById("img_flip_h").onclick=function(){fn_imageChange({degree:0,
flip:1})};document.getElementById("img_flip_v").onclick=function(){fn_imageChange({degree:0,flip:-1})};document.getElementById("btn_crop").onclick=function(){null!=document.getElementById("image_canvas")&&null==KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&(displayProcessing(!0),setTimeout(function(){var a=document.getElementById("image_canvas");a.style.left=a.parentNode.style.left;a.style.top=a.parentNode.style.top;a.parentNode.style.width=a.width+"px";a.parentNode.style.height=a.height+"px";KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper=
new Cropper(a,{zoomOnWheel:!1,autoCrop:!1,toggleDragModeOnDblclick:!1,ready:function(){document.getElementById("crop_tools_area").className="";document.getElementById("crop_box_size").parentNode.style.display="";selectCropType(0);displayProcessing(!1)},crop:function(a){a=a.detail;if(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper)try{var b=parseInt(a.width,10),h=parseInt(a.height,10);if(0==b){var r=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData();"undefined"!=typeof r.width&&(b=r.width=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(r))}0==
h&&(r=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),"undefined"!=typeof r.height&&(h=r.height=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(r)));document.getElementById("crop_box_size").innerHTML=b+" x "+h+" px"}catch(u){}}})},50))};document.getElementById("crop_cancel").onclick=function(){cropCancel()};document.getElementById("crop_ok").onclick=function(){cropOk()};document.getElementById("crop_ratio_0").onclick=function(){setCropBox(0);selectCropType(0)};document.getElementById("crop_ratio_1").onclick=
function(){setCropBox(4/3);selectCropType(1)};document.getElementById("crop_ratio_2").onclick=function(){setCropBox(16/9);selectCropType(2)};document.getElementById("crop_ratio_3").onclick=function(){setCropBox(1);selectCropType(3)};document.getElementById("crop_ratio_4").onclick=function(){setCropBox(2/3);selectCropType(4)};document.getElementById("crop_ratio_5").onclick=function(){setCropBox(.75);selectCropType(5)};document.getElementById("btn_reset").onclick=function(){fn_reset()};document.getElementById("btn_apply").onclick=
function(){fn_apply()};KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).onclick=function(){fn_fullscreen()};KMINIPHOTOTOP.document.getElementById("btn_close_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).onclick=function(){fn_close()};KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document,"keydown",document_keydown);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document.body,"paste",fn_pasteEvt);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document,"dragover",function(a){KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a)});
KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document,"drop",insertDropImage);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(window,"unload",_kminiphotoiframe_Unload)}function _kminiphotoiframe_Unload(a){try{var b=getPhotoFromUnloadEvent(a);if("1"==b._config.autoDestroy.use)try{KMINIPHOTOTOP.KMINIPHOTO.Destroy(b)}catch(c){}}catch(e){}}
function document_keydown(a){var b="which"in a?a.which:a.keyCode,c=a.ctrlKey;if(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&0==c)if(37==b){KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a);var e=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData();--e.left;KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(e)}else 39==b?(KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a),e=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),e.left+=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(e)):38==b?(KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a),
e=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),--e.top,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(e)):40==b?(KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a),e=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),e.top+=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(e)):27==b&&cropCancel();1==c&&(a.altKey||86!=b||(KMINIPHOTOTOP.KMINIPHOTO.browser.ie&&11<=KMINIPHOTOTOP.KMINIPHOTO.browser.ieVersion||KMINIPHOTOTOP.KMINIPHOTO.browser.gecko)&&fn_makePasteEvt(a))}
function fileOpen(){document.getElementById("open_file").click()}function setCropBox(a){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.options.aspectRatio=a;var b={};if(0!=a){var c=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData();b.width=parseInt(c.height*a,10);b.height=parseInt(c.height,10)}KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(b)}
function fn_imageChange(a){null!=document.getElementById("image_canvas")&&(displayProcessing(!0),setTimeout(function(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&cropCancel();var b=document.getElementById("image_canvas"),c=b.getContext("2d");G_HISTORY.saveState(b);c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,b.width,b.height);fn_rotate(a.degree,b,c);fn_flip(a.flip,b,c);c.drawImage(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage,0,0);setCanvasPostionCenter();displayProcessing(!1)},50))}
function fn_rotate(a,b,c){a&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree+=a,360==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree?KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0:0>KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=360+KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree));switch(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree){case 90:b.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;b.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;b.parentNode.style.width=
b.width+"px";b.parentNode.style.height=b.height+"px";c.rotate(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree*Math.PI/180);c.translate(0,-b.width);break;case 180:b.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;b.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;b.parentNode.style.width=b.width+"px";b.parentNode.style.height=b.height+"px";c.rotate(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree*Math.PI/180);c.translate(-1*b.width,-1*b.height);break;case 270:b.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;
b.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;b.parentNode.style.width=b.width+"px";b.parentNode.style.height=b.height+"px";c.rotate(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree*Math.PI/180);c.translate(-1*b.height,0);break;case 0:b.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth,b.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight,b.parentNode.style.width=b.width+"px",b.parentNode.style.height=b.height+"px",c.translate(0,0)}}
function fn_flip(a,b,c){var e;e=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;b=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;1==a?90==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree||270==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree?KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?!1:!0:KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?!1:!0:-1==a&&(90==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree||270==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree?
KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?!1:!0:KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?!1:!0);a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?-1*e:0;b=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?-1*b:0;c.scale(KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?-1:1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?-1:1);c.translate(a,b)}
function fn_reset(){null!=document.getElementById("image_canvas")&&(cropCancel(),G_HISTORY.reset(),loadImage({isInit:!1,src:KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg.src,width:KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgWidth,height:KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgHeight}))}
function fn_apply(){if(null!=document.getElementById("image_canvas")){cropCancel();var a={src:"",width:"",height:""},b=document.getElementById("image_canvas");a.src=b.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1);a.width=b.width+"px";a.height=b.height+"px";fn_close();try{"function"===typeof KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.saveCompleteEvent&&KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.saveCompleteEvent(KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID,a)}catch(c){}}}
function closeCropArea(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper=null;document.getElementById("image_canvas");document.getElementById("crop_tools_area").className="off";var a=document.getElementById("crop_box_size");a.innerHTML="0 x 0 px";a.parentNode.style.display="none"}function cropCancel(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.destroy(),closeCropArea())}
function cropOk(){displayProcessing(!0);setTimeout(function(){G_HISTORY.saveState(document.getElementById("image_canvas"));var a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCroppedCanvas();closeCropArea();a=a.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1);loadImage({isInit:!1,src:a})},50)}function displayProcessing(a){document.getElementById("span_processing").style.display=a?"":"none"}var G_originScrollSize,G_originPhotoSize=[],G_originfull={},G_origianPopupPos=[],G_relativePos,G_isRelativePos;
function fn_close(){displayProcessing(!1);cropCancel();var a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.arrBlobUrl.length;if(0<a)for(var b=0;b<a;b++)try{(window.URL||window.webkitURL||window).revokeObjectURL(KMINIPHOTOTOP.G_CURRKMINIPHOTO.arrBlobUrl[b])}catch(c){}if(a=document.getElementById("image_canvas"))b=a.getContext("2d"),b.setTransform(1,0,0,1,0,0),b.clearRect(0,0,a.width,a.height),a=a.parentNode,a.style.width="0px",a.style.height="0px",a.innerHTML="";G_HISTORY.reset();"fullscreen"==KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus&&
fullSreenToOriginalSize();KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="none";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_body_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="none";(a=KMINIPHOTOTOP.document.getElementById("kminiphoto_popup_background"))&&KMINIPHOTOTOP.document.body.removeChild(a)}
function fn_fullscreen(){var a=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID),b=document.getElementById("miniPhoto_holder"),c=document.getElementById("miniPhoto_image");if(""==KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus){G_originScrollSize=getWindowScrollPos(KMINIPHOTOTOP.window);G_originPhotoSize.push(a.style.width);G_originPhotoSize.push(a.style.height);G_originfull.margin1=KMINIPHOTOTOP.document.documentElement.style.margin;G_originfull.padding1=KMINIPHOTOTOP.document.documentElement.style.padding;
G_originfull.border1=KMINIPHOTOTOP.document.documentElement.style.border;G_originfull.height1=KMINIPHOTOTOP.document.documentElement.style.height;G_originfull.overflow1=KMINIPHOTOTOP.document.documentElement.style.overflow;"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(G_originfull.margin2=KMINIPHOTOTOP.document.body.style.margin,G_originfull.padding2=KMINIPHOTOTOP.document.body.style.padding,G_originfull.border2=KMINIPHOTOTOP.document.body.style.border,G_originfull.height2=KMINIPHOTOTOP.document.body.style.height,
G_originfull.overflow2=KMINIPHOTOTOP.document.body.style.overflow);KMINIPHOTOTOP.document.documentElement.style.overflow="hidden";KMINIPHOTOTOP.document.documentElement.style.padding="0";KMINIPHOTOTOP.document.documentElement.style.margin="0";KMINIPHOTOTOP.document.documentElement.style.border="0";KMINIPHOTOTOP.document.documentElement.style.height="100%";"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(KMINIPHOTOTOP.document.body.style.overflow="hidden",KMINIPHOTOTOP.document.body.style.padding=
"0",KMINIPHOTOTOP.document.body.style.margin="0",KMINIPHOTOTOP.document.body.style.border="0",KMINIPHOTOTOP.document.body.style.height="100%");G_originfull.overflow3=a.style.overflow;G_originfull.position3=a.style.position;G_originfull.zIndex=a.style.zIndex;KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(a);a.style.overflow="hidden";a.style.position="absolute";a.style.width="100%";a.style.height="100%";var e=getWindowClientSize(KMINIPHOTOTOP.window);a.style.width=e[0]+"px";a.style.height=e[1]+"px";b.style.width=
e[0]-2+"px";c.style.width=e[0]-2+"px";c.style.height=e[1]-30-56-20-2+"px";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.width=e[0]-2+"px";G_origianPopupPos.push(a.style.left);G_origianPopupPos.push(a.style.top);a.style.left="0px";a.style.top="0px";b=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(a);G_relativePos=isRelativePosition(a);0<b.left||0<b.top?G_isRelativePos=!0:"0"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(0<G_originScrollSize[0]&&
(a.style.left=G_originScrollSize[0]+"px"),0<G_originScrollSize[1]&&(a.style.top=G_originScrollSize[1]+"px"));"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&adjustPopupPosition();setBackupHiddenStyle(a,KMINIPHOTOTOP.window);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(KMINIPHOTOTOP.window,"resize",resizeForFullscreen);KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus="fullscreen";KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.backgroundPosition="0 -50px";
KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).title=KMiniPhoto_Lang.originalScreen;setCanvasPostionCenter()}else fullSreenToOriginalSize()}
function adjustPopupPosition(a){void 0==a&&(a=KMINIPHOTOTOP.document.getElementById("miniPhoto_holder"));var b=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID);b&&(b=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(b),0>b.top&&(a.style.top=KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(a.style.top)-KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(b.top)+"px"))}
function getWindowScrollPos(a){return"number"===typeof a.pageYOffset?[a.pageXOffset,a.pageYOffset]:a.document.body&&(a.document.body.scrollLeft||a.document.body.scrollTop)?[a.document.body.scrollLeft,a.document.body.scrollTop]:a.document.documentElement&&(a.document.documentElement.scrollLeft||a.document.documentElement.scrollTop)?[a.document.documentElement.scrollLeft,a.document.documentElement.scrollTop]:[0,0]}
function getWindowClientSize(a){var b=0,c=0;"number"==typeof a.innerWidth?(b=a.innerWidth,c=a.innerHeight):a.document.documentElement&&(a.document.documentElement.clientWidth||a.document.documentElement.clientHeight)?(b=a.document.documentElement.clientWidth,c=a.document.documentElement.clientHeight):a.document.body&&(a.document.body.clientWidth||a.document.body.clientHeight)&&(b=a.document.body.clientWidth,c=a.document.body.clientHeight);return[b,c]}
function isRelativePosition(a){for(;null!=a&&(!a.tagName||"body"!=a.tagName.toLowerCase());)if(a=a.parentNode,"relative"==a.style.position)return!0;return!1}
function setBackupHiddenStyle(a,b){G_originStylebackup=[];for(var c=a;null!=c&&(!c.tagName||"body"!=c.tagName.toLowerCase());){if(c!=a){var e;(e=b.getComputedStyle?b.getComputedStyle(c,""):c.currentStyle)&&e.overflow&&"hidden"==e.overflow&&(G_originStylebackup.push(c),c.style.setProperty?c.style.setProperty("overflow","visible",null):c.style.setAttribute("overflow","visible"))}c=c.parentNode}}
function resizeForFullscreen(){var a=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID),b=document.getElementById("miniPhoto_holder"),c=document.getElementById("miniPhoto_image"),e=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(a);a.style.left=KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(a.style.left)+-1*e.left+"px";a.style.top=KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(a.style.top)+-1*e.top+"px";e=getWindowClientSize(KMINIPHOTOTOP.window);a.style.width=e[0]+"px";
a.style.height=e[1]+"px";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.width=e[0]-2+"px";b.style.width=e[0]-2+"px";b.style.height=e[1]+"px";c.style.width=e[0]-2+"px";c.style.height=e[1]-30-56-20-2+"px";setCanvasPostionCenter()}
function fullSreenToOriginalSize(){var a=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID),b=document.getElementById("miniPhoto_holder"),c=document.getElementById("miniPhoto_image");KMINIPHOTOTOP.KMINIPHOTO.util.removeEvent(KMINIPHOTOTOP.window,"resize",resizeForFullscreen);KMINIPHOTOTOP.document.documentElement.style.margin=G_originfull.margin1;KMINIPHOTOTOP.document.documentElement.style.padding=G_originfull.padding1;KMINIPHOTOTOP.document.documentElement.style.border=
G_originfull.border1;KMINIPHOTOTOP.document.documentElement.style.height=G_originfull.height1;KMINIPHOTOTOP.document.documentElement.style.overflow=G_originfull.overflow1;"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(KMINIPHOTOTOP.document.body.style.margin=G_originfull.margin2,KMINIPHOTOTOP.document.body.style.padding=G_originfull.padding2,KMINIPHOTOTOP.document.body.style.border=G_originfull.border2,KMINIPHOTOTOP.document.body.style.height=G_originfull.height2,KMINIPHOTOTOP.document.body.style.overflow=
G_originfull.overflow2);a.style.overflow=G_originfull.overflow3;a.style.position=G_originfull.position3;0<G_originPhotoSize.length&&(a.style.width=G_originPhotoSize[0],a.style.height=G_originPhotoSize[1],b.style.width=parseInt(G_originPhotoSize[0],10)-2+"px",KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.width=parseInt(G_originPhotoSize[0],10)-2+"px",c.style.width=parseInt(G_originPhotoSize[0],10)-2+"px",c.style.height=parseInt(G_originPhotoSize[1],
10)-30-56-20-2+"px",G_originPhotoSize=[]);0<G_origianPopupPos.length&&(a.style.left=G_origianPopupPos[0],a.style.top=G_origianPopupPos[1],G_origianPopupPos=[]);setRestorreHiddenStyle();G_toolHeight=0;null!=G_originScrollSize&&(KMINIPHOTOTOP.window.scroll(G_originScrollSize[0],G_originScrollSize[1]),G_originScrollSize=null);KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus="";KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.backgroundPosition="0 0";KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+
KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).title=KMiniPhoto_Lang.fullScreen;setCanvasPostionCenter()}function setRestorreHiddenStyle(){for(var a=G_originStylebackup.length,b=0;b<a;b++){var c=G_originStylebackup[b];c.style.setProperty?c.style.setProperty("overflow","hidden",null):c.style.setAttribute("overflow","hidden")}G_originStylebackup=[]}
function showPhotoPopup(a){var b=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID);b.parentNode.style.display="";document.getElementById("miniPhoto_holder");document.getElementById("miniPhoto_image");var c=getWindowClientSize(KMINIPHOTOTOP.window),e=getWindowScrollPos(KMINIPHOTOTOP.window),h;if(null==document.getElementById("kminiphoto_popup_background")){h=document.createElement("div");h.setAttribute("id","kminiphoto_popup_background");var r='<div style="'+
KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.popupBackgroundStyle+" z-index:"+(KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.zIndex-1)+'; position:fixed; _position:absolute; left:0px; top:0px;overflow:hidden;width:100%;height:100%;"></div>',r=r+('<iframe frameborder="0" scrolling="no" style="filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0; left: 0px; top: 0px; width: 100%; height: 100%; display: block; position: absolute; z-index: '+
(KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.zIndex-2)+';"></iframe>');h.innerHTML=r;KMINIPHOTOTOP.document.body.appendChild(h);h.getElementsByTagName("iframe")[0].style.height=c[1]+e[1]+"px"}b.style.display="";b.style.position="absolute";b.style.zIndex=KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.zIndex;h=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(b);r=h.bottom-h.top;b.style.left=e[0]+c[0]/2-(h.right-h.left)/2+"px";b.style.top=e[1]+c[1]/2-r/2+"px";adjustPopupPosition();makeDragPopup(b);setImageArea();null!=
a.url&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt=getImageExtensionFromUrl(a.url));loadImage({isInit:!0,src:a.url,width:a.width,height:a.height});KMINIPHOTOTOP.KMINIPHOTO.browser.ie?setTimeout(function(){try{window.focus(),document.focus(),document.body.focus()}catch(a){}},0):setTimeout(function(){try{window.focus(),document.body.focus()}catch(a){}},0)}var G_drag=!1,G_dragPopup;
function makeDragPopup(a){G_drag=!1;var b=a.firstChild;KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(b,"mousedown",startDrag);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(b,"mouseover",function(){b.style.cursor="move"});KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(b,"mouseout",function(){b.style.cursor="default"});G_dragPopup=a}
function startDrag(a){""==KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus&&(a||(a=KMINIPHOTOTOP.window.event),G_offsetX=a.clientX,G_offsetY=a.clientY,G_dragPopup.style.left||(G_dragPopup.style.left="0px"),G_dragPopup.style.top||(G_dragPopup.style.top="0px"),G_coordX=parseInt(G_dragPopup.style.left),G_coordY=parseInt(G_dragPopup.style.top),G_drag=!0,KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_body_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="",KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(KMINIPHOTOTOP.document,
"mousemove",dragDiv),KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(KMINIPHOTOTOP.document,"mouseup",stopDrag));KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a)}
function dragDiv(a){if(G_drag){a||(a=KMINIPHOTOTOP.window.event);var b=getWindowClientSize(KMINIPHOTOTOP.window),c=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(G_dragPopup),c=[c.right-c.left||0,c.bottom-c.top||0];currentScrollPos=getWindowScrollPos(KMINIPHOTOTOP.window);var e=G_coordX+a.clientX-G_offsetX,h=G_coordY+a.clientY-G_offsetY;0>=e-currentScrollPos[0]&&(e=currentScrollPos[0]);0>=h-currentScrollPos[1]&&(h=currentScrollPos[1]);e+c[0]>=b[0]+currentScrollPos[0]&&(e=b[0]-c[0]+currentScrollPos[0]);
h+c[1]>=b[1]+currentScrollPos[1]&&(h=b[1]-c[1]+currentScrollPos[1]);G_dragPopup.style.left=e+"px";G_dragPopup.style.top=h+"px";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID);adjustPopupPosition(G_dragPopup);KMINIPHOTOTOP.KMINIPHOTO.util.stopEvent(a);KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a)}}
function stopDrag(a){G_drag=!1;G_dragPopup.style.cursor="";KMINIPHOTOTOP.KMINIPHOTO.util.removeEvent(KMINIPHOTOTOP.document,"mousemove",dragDiv);KMINIPHOTOTOP.KMINIPHOTO.util.removeEvent(KMINIPHOTOTOP.document,"mouseup",stopDrag);KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_body_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="none"}function selectCropType(a){for(var b=0;6>b;b++)document.getElementById("crop_ratio_"+b).parentNode.style.backgroundColor=a==b?"#b5d0f1":""}
function getImageExtensionFromType(a){var b="png";try{a&&""!=a&&(a=a.split("/")[1]),a&&0<a.length&&(b="gif"==a||"png"==a?"png":"jpeg")}catch(c){b="png"}return b}function getImageExtensionFromUrl(a){var b="";try{if(0==a.indexOf("data:")){var c=a.split(",");2==c.length&&(b=getExtFromImageDataSrc(c[0]))}else var e=a.split("?"),h=e[0].lastIndexOf("."),b=e[0].substring(h+1,e[0].length),b=b.toLowerCase();b="gif"==b||"png"==b?"png":"jpeg"}catch(r){b="png"}return b}
function getExtFromImageDataSrc(a){var b="";a=a.replace("data:","").split(";");0<a.length&&(a=a[0].split("/"),2==a.length&&(b=a[1]));return b}
function getPhotoFromUnloadEvent(a){var b=null;try{if(null!=a){var c=a.target?a.target:a.srcElement;if(c)try{a="",c._raonk_miniphoto?a="kminiphoto_frame_"+c._raonk_miniphoto.ID:c.defaultView&&(a="kminiphoto_frame_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO),b=KMINIPHOTOTOP.KMINIPHOTO.RAONKMULTIPLE[a]}catch(e){b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}else b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}else b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}catch(h){b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}return b}
function fn_makePasteEvt(a){try{if(a&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO=getPhotoFromEvent(a)),KMINIPHOTOTOP.KMINIPHOTO.browser.ie){var b=document.createElement("div");b.id="pasteDiv";b.innerHTML=unescape("%uFEFF");b.style.position="absolute";b.style.filter="alpha(opacity=0)";b.style.overflow="hidden";b.style.left="-1000px";b.style.top="-1000px";b.style.width="0px";b.style.height="0px";b.contentEditable=!0;document.body.appendChild(b);b.focus()}else if(KMINIPHOTOTOP.KMINIPHOTO.browser.gecko){var c=document.createElement("iframe");
c.id="pasteIframe";c.frameBorder=0;c.style.width="0px";c.style.height="0px";c.style.position="absolute";c.style.left="0px";c.style.top="0px";if(KMINIPHOTOTOP.KMINIPHOTO.browser.mobile||KMINIPHOTOTOP.KMINIPHOTO.browser.iOS)c.style.overflow="hidden",c.style.display="inline-block";var e="document.open();"+(KMINIPHOTOTOP.KMINIPHOTO.browser.isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();",e=KMINIPHOTOTOP.KMINIPHOTO.browser.ie?"javascript:void(function(){"+encodeURIComponent(e)+
"}())":"";c.src=e;document.body.appendChild(c);var h=KMINIPHOTOTOP.KMINIPHOTO.util.getIframeDocument(c);h.open("text/html","replace");KMINIPHOTOTOP.KMINIPHOTO.browser.isCustomDomain(document)&&(h.domain=document.domain);h.write('<body contenteditable="true">'+unescape("%uFEFF")+"</body>");h.close();h.body.contentEditable=!0;h.body.onpaste=fn_pasteEvt;h.body.focus()}}catch(r){}}
function fn_pasteEvt(a){try{var b=KMINIPHOTOTOP.G_CURRKMINIPHOTO;document.createElement("canvas").getContext("2d");if(KMINIPHOTOTOP.KMINIPHOTO.browser.ie||KMINIPHOTOTOP.KMINIPHOTO.browser.gecko)setTimeout(function(){var a=null,c=null;if(KMINIPHOTOTOP.KMINIPHOTO.browser.ie)c=a=document.getElementById("pasteDiv");else if(KMINIPHOTOTOP.KMINIPHOTO.browser.gecko)try{var e=document.getElementById("pasteIframe");e&&(a=KMINIPHOTOTOP.KMINIPHOTO.util.getIframeDocument(e).body,c=e)}catch(h){a=null}a&&(a.blur(),
a=a.getElementsByTagName("img"),0<a.length&&(b.initImgExt="png",loadImage({isInit:!1,isOpen:!0,src:a[0].src})),c.parentNode.removeChild(c))},0);else if(KMINIPHOTOTOP.KMINIPHOTO.browser.chrome||KMINIPHOTOTOP.KMINIPHOTO.browser.opera){var c=a.clipboardData.items,e=c.length;for(a=0;a<e;++a){var h=c[a].getAsFile(),r=new FileReader;r.onload=function(a){a=a.target.result;b.initImgExt="png";loadImage({isInit:!1,isOpen:!0,src:a});r=void 0};r.readAsDataURL(h)}}}catch(u){}}
function getPhotoFromEvent(a){var b=null;try{if(null!=a){var c=a.target?a.target:a.srcElement;if(c){a=null;a=9!=c.nodeType?c.ownerDocument:c;try{a=a.defaultView?a.defaultView:a.parentWindow,b=KMINIPHOTOTOP.KMINIPHOTO.RAONKMULTIPLE[a.frameElement.id]}catch(e){b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}}else b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}else b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}catch(h){b=KMINIPHOTOTOP.G_CURRKMINIPHOTO}return b}
function insertDropImage(a){var b=a.dataTransfer.files;a.stopPropagation();a.preventDefault();if(0<b.length&&b[0].type&&0==b[0].type.indexOf("image")){var c=getImageExtensionFromType(b[0].type),e=new FileReader;e.onload=function(a){a=a.target.result;"data:"==a.substring(0,5)&&2==a.split(",").length&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt=c,loadImage({isInit:!1,isOpen:!0,src:a}));e=void 0};e.readAsDataURL(b[0])}};var G_HISTORY={redo_list:[],undo_list:[],saveState:function(a,b,c,e){c||(this.redo_list=[]);e?(b||this.undo_list).push(e.src):(a=a.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1),(b||this.undo_list).push(a));this.displayBtn()},undo:function(a,b){this.restoreState(a,b,this.undo_list,this.redo_list)},redo:function(a,b){this.restoreState(a,b,this.redo_list,this.undo_list)},restoreState:function(a,b,c,e){var h=this;c.length&&(displayProcessing(!0),setTimeout(function(){h.saveState(a,e,
!0);var b=c.pop(),u=new Image;u.onload=function(){document.getElementById("miniPhoto_image");var b=a.getContext("2d");b.setTransform(1,0,0,1,0,0);b.clearRect(0,0,a.width,a.height);KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=u;a.width=u.naturalWidth;a.height=u.naturalHeight;a.parentNode.style.width=u.naturalWidth+"px";a.parentNode.style.height=u.naturalHeight+"px";b.drawImage(u,
0,0);u.style.display="none";setCanvasPostionCenter();displayProcessing(!1);try{u=void 0}catch(c){}};u.src=b;h.displayBtn()},50))},reset:function(){this.redo_list=[];this.undo_list=[];this.displayBtn()},displayBtn:function(){document.getElementById("btn_redo").firstChild.className=0<this.redo_list.length?"redo":"redo deact-r";document.getElementById("btn_undo").firstChild.className=0<this.undo_list.length?"undo":"undo deact-u"}};
